PTSLC_CPP Namespace Reference
Classes
struct AudioData
Structure that describes information for audio data.
class CallData
Common utility structure that contains grpc data which are transferring between the grpc async calls.
struct ClearAllMemoryLocationsError
Structure that describes ClearAllMemoryLocations error message.
struct ClearAllMemoryLocationsResponse
Structure that describes ClearAllMemoryLocations response data.
struct ClearMemoryLocationError
Structure that describes ClearMemoryLocation error message.
struct ClearMemoryLocationRequest
Structure that describes ClearMemoryLocation request data.
struct ClearMemoryLocationResponse
Structure that describes ClearMemoryLocation response data.
struct ClearSpecialRequest
Structure that describes ClearSpecial request data.
struct ClientConfig
Structure that describes data needed for client's configuring.
struct CloseSessionRequest
Structure that describes CloseSession request data.
struct CommandError
Structure that describes common data of the error message.
struct CommandHeader
Structure that describes common data of command message (used in a response).
struct CommandRequest
Structure that describes common data of the command data.
struct CommandResponse
Structure that describes common data of the command data.
struct CommandStatus
Structure that describes command status.
struct CopySpecialRequest
Structure that describes Cut request data.
class CppPTSLClient
Async C++ client wrapper for handling gRPC async streaming requests and receiving responses.
class CppPTSLRequest
class CppPTSLResponse
struct CreateFadesBasedOnPresetError
Structure that describes CreateFadesBasedOnPreset error message.
struct CreateFadesBasedOnPresetRequest
Structure that describes CreateFadesBasedOnPreset request data.
struct CreateMemoryLocationRequest
Structure that describes CreateMemoryLocation request data.
struct CreateNewTracksRequest
Structure that describes CreateNewTracks request data.
struct CreateNewTracksResponse
Structure that describes CreateNewTracks response data.
struct CreateSessionRequest
Structure that describes CreateSession request data.
struct CutSpecialRequest
Structure that describes Cut request data.
struct DefaultRequestHandler
Common request handler for processing specific grpc requests and responses.
struct EditMemoryLocationRequest
Structure that describes EditMemoryLocation request data.
struct EditModeOptions
Structure that describes edit mode options.
struct EM_AudioInfo
Structure that describes information for audio section in the Bounce Mix window.
struct EM_CodecInfo
Structure that describes information for codec in video section for Export Mix.
struct EM_DolbyAtmosInfo
Structure that describes information for dolby atmos section in the Bounce Mix window.
struct EM_ImportOptions
Structure that describes information for import options if importAfterBounce is true.
struct EM_LocationInfo
Structure that describes information for location section in the Bounce Mix window.
struct EM_VideoInfo
Structure that describes information for video section in the Bounce Mix window.
struct ExportClipsAsFilesRequest
Structure that describes ExportClipsAsFiles request data.
struct ExportMixRequest
Structure that describes ExportMix request data.
struct ExportSelectedTracksAsAAFOMFRequest
Structure that describes ExportSelectedTracksAsAAFOMF request data.
struct ExportSessionInfoAsTextRequest
Structure that describes ExportSessionInfoAsText request data.
struct ExportSessionInfoAsTextResponse
Structure that describes ExportSessionInfoAsText response data.
struct ExtendSelectionToTargetTracksError
Structure that describes ExtendSelectionToTargetTracks error message.
struct ExtendSelectionToTargetTracksRequest
Structure that describes ExtendSelectionToTargetTracks request data.
struct FileLocation
Structure that describes file location and its info.
struct FileLocationInfo
Structure that describes file location info.
struct GetDynamicPropertiesGroup
Structure that describes GetDynamicProperties group.
struct GetDynamicPropertiesRequest
Structure that describes GetDynamicProperties request data.
struct GetDynamicPropertiesResponse
Structure that describes GetDynamicProperties response data.
struct GetEditModeOptionsResponse
Structure that describes GetEditModeOptions response data.
struct GetEditModeResponse
Structure that describes GetEditMode response data.
struct GetEditToolResponse
Structure that describes GetEditTool response data.
struct GetFileLocationRequest
Structure that describes GetFileLocation request data.
struct GetFileLocationResponse
Structure that describes GetFileLocation response data.
struct GetMainCounterFormatResponse
Structure that describes GetMainCounterFormat response data.
struct GetMemoryLocationsManageModeResponse
Structure that describes GetMemoryLocationsManageMode response data.
struct GetMemoryLocationsRequest
Structure that describes GetMemoryLocation request data.
struct GetMemoryLocationsResponse
Structure that describes GetMemoryLocations response data.
struct GetPlaybackModeResponse
Structure that describes GetPlaybackMode response data.
struct GetPTSLVersionRequest
Structure that describes GetPTSLVersion request data.
struct GetPTSLVersionResponse
Structure that describes GetPTSLVersion response data.
struct GetRecordModeResponse
Structure that describes GetRecordMode response data.
struct GetSessionAudioFormatResponse
Structure that describes GetSessionAudioFormat response data.
struct GetSessionAudioRatePullSettingsResponse
Structure that describes GetSessionAudioRatePullSettings response data.
struct GetSessionBitDepthResponse
Structure that describes GetSessionBitDepth response data.
struct GetSessionFeetFramesRateResponse
Structure that describes GetSessionFeetFramesRate response data.
struct GetSessionIDsResponse
Structure that describes GetSessionIDs response data.
struct GetSessionInterleavedStateResponse
Structure that describes GetSessionInterleavedState response data.
struct GetSessionLengthResponse
Structure that describes GetSessionLength response data.
struct GetSessionNameResponse
Structure that describes GetSessionName response data.
struct GetSessionPathResponse
Structure that describes GetSessionPath response data.
struct GetSessionSampleRateResponse
Structure that describes GetSessionSampleRate response data.
struct GetSessionStartTimeResponse
Structure that describes GetSessionStartTime response data.
struct GetSessionSystemDelayInfoResponse
Structure that describes GetSessionSystemDelayInfo response data.
struct GetSessionTimeCodeRateResponse
Structure that describes GetSessionTimeCodeRate response data.
struct GetSessionVideoRatePullSettingsResponse
Structure that describes GetSessionVideoRatePullSettings response data.
struct GetSubCounterFormatResponse
Structure that describes GetSubCounterFormat response data.
struct GetTaskStatusRequest
Structure that describes GetTaskStatus request data.
struct GetTaskStatusResponse
Structure that describes GetTaskStatus response data.
struct GetTimelineSelectionRequest
Structure that describes GetTimelineSelection request data.
struct GetTimelineSelectionResponse
Structure that describes GetTimelineSelection response data.
struct GetTrackListRequest
Structure that describes GetTrackList request data.
struct GetTrackListResponse
Structure that describes GetTrackList response data.
struct GetTransportArmedResponse
Structure that describes GetTransportArmed response data.
struct GetTransportStateResponse
Structure that describes GetTransportState response data.
struct HostReadyCheckResponse
Structure that describes whether Pro Tools is fully loaded to execute PTSL commands.
struct ImportFailureInfo
A file and the failure related to it during importing.
struct ImportRequest
Structure that describes Import request data.
struct ImportResponse
Structure that describes Import response data.
struct ImportVideoRequest
Structure that describes ImportVideo request data.
struct ImportVideoResponse
Structure that describes ImportVideo response data.
struct MediaTimePosition
Structure that represents an internal position within a piece of media.
struct MemoryLocation
Structure that describes memory location.
struct MemoryLocationProperties
Structure that describes location properties (flags).
struct OpenSessionRequest
Structure that describes OpenSession request data.
struct PaginationRequest
Structure that describes Pagination request data.
struct PasteSpecialRequest
Structure that describes PasteSpecial request data.
struct PropertyContainer
Structure that describes container for property.
struct PropertyDescriptor
Structure that describes property for dynamic data.
class PTSLCommandException
Class that describes common PTSL exception based on runtime_error.
class PTSLException
PTSL specific exception class.
struct RecallZoomPresetRequest
Structure that describes RecallZoomPreset request data.
struct RedoAllResponse
Structure that describes RedoAll response data.
struct RedoRequest
Structure that describes Redo request data.
struct RedoResponse
Structure that describes Redo response data.
struct RefreshTargetAudioFilesError
Structure that describes RefreshTargetAudioFiles error message.
struct RefreshTargetAudioFilesRequest
Structure that describes RefreshTargetAudioFiles request data.
struct RefreshTargetAudioFilesResponse
Structure that describes RefreshTargetAudioFiles response data.
struct RegisterConnectionRequest
Structure that describes RegisterConnection request data.
struct RegisterConnectionResponse
Structure that describes RegisterConnection response data.
struct RenameSelectedClipRequest
Structure that describes RenameSelectedClip request data.
struct RenameTargetClipRequest
Structure that describes RenameTargetClip request data.
struct RenameTargetTrackRequest
Structure that describes RenameTargetTrack request data.
struct RepeatSelectionRequest
Structure that describes RepeatSelection request data.
struct ResponseError
Structure that describes error response during command execution.
class SafeLogger
Utility class for a thread-safe logging and printing error or warning messages.
struct SaveSessionAsRequest
Structure that describes SaveSessionAs request data.
struct SelectAllClipsOnTrackError
Structure that describes SelectAllClipsOnTrack error message.
struct SelectAllClipsOnTrackRequest
Structure that describes SelectAllClipsOnTrack request data.
struct SelectMemoryLocationRequest
Structure that describes SelectMemoryLocation request data.
struct SelectTracksByNameRequest
Structure that describes SelectTracksByName request data.
struct SelectTracksByNameResponse
Structure that describes SelectTracksByName response data.
struct SetEditModeOptionsRequest
Structure that describes SetEditModeOptions request data.
struct SetEditModeRequest
Structure that describes SetEditMode request data.
struct SetEditToolRequest
Structure that describes SetEditTool request data.
struct SetMainCounterFormatRequest
Structure that describes SetMainCounterFormat request data.
struct SetMemoryLocationsManageModeRequest
Structure that describes SetMemoryLocationsManageMode request data.
struct SetPlaybackModeRequest
Structure that describes SetPlaybackMode request data.
struct SetPlaybackModeResponse
Structure that describes SetPlaybackMode response data.
struct SetRecordModeRequest
Structure that describes SetRecordMode request data.
struct SetRecordModeResponse
Structure that describes SetRecordMode response data.
struct SetSessionAudioFormatRequest
Structure that describes SetSessionAudioFormat request data.
struct SetSessionAudioRatePullSettingsRequest
Structure that describes SetSessionAudioRatePullSettings request data.
struct SetSessionBitDepthRequest
Structure that describes SetSessionBitDepth request data.
struct SetSessionFeetFramesRateRequest
Structure that describes SetSessionFeetFramesRate request data.
struct SetSessionInterleavedStateRequest
Structure that describes SetSessionInterleavedState request data.
struct SetSessionLengthRequest
Structure that describes SetSessionLength request data.
struct SetSessionStartTimeRequest
Structure that describes SetSessionStartTime request data.
struct SetSessionTimeCodeRateRequest
Structure that describes SetSessionTimeCodeRate request data.
struct SetSessionVideoRatePullSettingsRequest
Structure that describes SetSessionVideoRatePullSettings request data.
struct SetSubCounterFormatRequest
Structure that describes SetSubCounterFormat request data.
struct SetTimelineSelectionRequest
Structure that describes SetTimelineSelection request data.
struct SetTrackDSPModeSafeStateRequest
Structure that describes SetTrackDSPModeSafeState request data.
struct SetTrackFrozenStateRequest
Structure that describes SetTrackFrozenState request data.
struct SetTrackHiddenStateRequest
Structure that describes SetTrackHiddenState request data.
struct SetTrackInactiveStateRequest
Structure that describes SetTrackInactiveState request data.
struct SetTrackInputMonitorStateRequest
Structure that describes SetTrackInputMonitorState request data.
struct SetTrackMuteStateRequest
Structure that describes SetTrackMuteState request data.
struct SetTrackOnlineStateRequest
Structure that describes SetTrackOnlineState request data.
struct SetTrackOpenStateRequest
Structure that describes SetTrackOpenState request data.
struct SetTrackRecordEnableStateRequest
Structure that describes SetTrackRecordEnableState request data.
struct SetTrackRecordSafeEnableStateRequest
Structure that describes SetTrackRecordSafeEnableState request data.
struct SetTrackSmartDspStateRequest
Structure that describes SetTrackSmartDspState request data.
struct SetTrackSoloSafeStateRequest
Structure that describes SetTrackSoloSafeState request data.
struct SetTrackSoloStateRequest
Structure that describes SetTrackSoloState request data.
struct SpotLocationData
Structure that describes location data.
struct SpotRequest
Structure that describes Spot request data.
class TaskCancelledException
Class that describes specific TaskCanceledException based on runtime_error using to communicate task cancellation.
struct TimeLength
Structure that represents a typed relative time position - can apply to both media and timeline times.
struct TimelineLocation
Structure that represents a time in the Pro Tools timeline; can be expressed in a variety of units.
struct Track
Structure that describes Pro Tools track.
struct TrackAttributes
Structure that describes Pro Tools track attributes.
struct TrackExcludedFromClipGroupInfo
Structure that describes a track on which the clip group could not be created.
struct TrackListInvertibleFilter
Structure that describes track list filter that can be inverted (e.g.
struct UndoAllResponse
Structure that describes UndoAll response data.
struct UndoHistoryOperation
A single Undo/Redo operation (see menu Window -> Undo History in the Pro Tools UI).
struct UndoRequest
Structure that describes Undo request data.
struct UndoResponse
Structure that describes Undo response data.
Typedefs
using CommandType = CommandId
using CommandStatusType = TaskStatus
using FileDestination = EM_FileDestination
using PM_PlaybackMode = PlaybackMode
using RM_RecordMode = RecordMode
using TS_TransportState = TransportState
using CL_ClipLocation = ClipLocation
Enumerations
enum class Mode : int32_t { ProTools
, Mode_ProTools = 0
, Standalone
, Mode_Standalone = 1
 }
enum class SkipHostLaunch : int32_t { Yes
, SHLaunch_Yes = 0
, No
, SHLaunch_No = 1
 }
enum class CommandId : int32_t {
CId_None = -1
, CreateSession
, CId_CreateSession = 0
, OpenSession
,
CId_OpenSession = 1
, Import
, CId_Import = 2
, GetTrackList
,
CId_GetTrackList = 3
, SelectAllClipsOnTrack
, CId_SelectAllClipsOnTrack = 4
, ExtendSelectionToTargetTracks
,
CId_ExtendSelectionToTargetTracks = 5
, TrimToSelection
, CId_TrimToSelection = 6
, CreateFadesBasedOnPreset
,
CId_CreateFadesBasedOnPreset = 7
, RenameTargetTrack
, CId_RenameTargetTrack = 8
, ConsolidateClip
,
CId_ConsolidateClip = 9
, ExportClipsAsFiles
, CId_ExportClipsAsFiles = 10
, ExportSelectedTracksAsAAFOMF
,
CId_ExportSelectedTracksAsAAFOMF = 11
, GetTaskStatus
, CId_GetTaskStatus = 12
, HostReadyCheck
,
CId_HostReadyCheck = 13
, RefreshTargetAudioFiles
, CId_RefreshTargetAudioFiles = 14
, RefreshAllModifiedAudioFiles
,
CId_RefreshAllModifiedAudioFiles = 15
, GetFileLocation
, CId_GetFileLocation = 16
, CloseSession
,
CId_CloseSession = 17
, SaveSession
, CId_SaveSession = 18
, SaveSessionAs
,
CId_SaveSessionAs = 19
, Cut = 20
, CId_Cut = 20
, Copy
,
CId_Copy = 21
, Paste
, CId_Paste = 22
, Clear
,
CId_Clear = 23
, CutSpecial
, CId_CutSpecial = 24
, CopySpecial
,
CId_CopySpecial = 25
, ClearSpecial
, CId_ClearSpecial = 26
, PasteSpecial
,
CId_PasteSpecial = 27
, ExportMix
, CId_ExportMix = 28
, Spot
,
CId_Spot = 29
, ExportSessionInfoAsText
, CId_ExportSessionInfoAsText = 30
, GetDynamicProperties
,
CId_GetDynamicProperties = 31
, SetPlaybackMode
, CId_SetPlaybackMode = 32
, SetRecordMode
,
CId_SetRecordMode = 33
, GetSessionAudioFormat
, CId_GetSessionAudioFormat = 34
, GetSessionSampleRate
,
CId_GetSessionSampleRate = 35
, GetSessionBitDepth
, CId_GetSessionBitDepth = 36
, GetSessionInterleavedState
,
CId_GetSessionInterleavedState = 37
, GetSessionTimeCodeRate
, CId_GetSessionTimeCodeRate = 38
, GetSessionFeetFramesRate
,
CId_GetSessionFeetFramesRate = 39
, GetSessionAudioRatePullSettings
, CId_GetSessionAudioRatePullSettings = 40
, GetSessionVideoRatePullSettings
,
CId_GetSessionVideoRatePullSettings = 41
, GetSessionName
, CId_GetSessionName = 42
, GetSessionPath
,
CId_GetSessionPath = 43
, GetSessionStartTime
, CId_GetSessionStartTime = 44
, GetSessionLength
,
CId_GetSessionLength = 45
, SetSessionAudioFormat
, CId_SetSessionAudioFormat = 46
, SetSessionBitDepth
,
CId_SetSessionBitDepth = 47
, SetSessionInterleavedState
, CId_SetSessionInterleavedState = 48
, SetSessionTimeCodeRate
,
CId_SetSessionTimeCodeRate = 49
, SetSessionFeetFramesRate
, CId_SetSessionFeetFramesRate = 50
, SetSessionAudioRatePullSettings
,
CId_SetSessionAudioRatePullSettings = 51
, SetSessionVideoRatePullSettings
, CId_SetSessionVideoRatePullSettings = 52
, SetSessionStartTime
,
CId_SetSessionStartTime = 53
, SetSessionLength
, CId_SetSessionLength = 54
, GetPTSLVersion
,
CId_GetPTSLVersion = 55
, GetPlaybackMode
, CId_GetPlaybackMode = 56
, GetRecordMode
,
CId_GetRecordMode = 57
, GetTransportArmed
, CId_GetTransportArmed = 58
, GetTransportState
,
CId_GetTransportState = 59
, ClearMemoryLocation
, CId_ClearMemoryLocation = 61
, RenameSelectedClip
,
CId_RenameSelectedClip = 62
, RenameTargetClip
, CId_RenameTargetClip = 63
, TogglePlayState
,
CId_TogglePlayState = 64
, ToggleRecordEnable
, CId_ToggleRecordEnable = 65
, PlayHalfSpeed
,
CId_PlayHalfSpeed = 66
, RecordHalfSpeed
, CId_RecordHalfSpeed = 67
, EditMemoryLocation
,
CId_EditMemoryLocation = 68
, GetMemoryLocations
, CId_GetMemoryLocations = 69
, RegisterConnection
,
CId_RegisterConnection = 70
, CreateMemoryLocation
, CId_CreateMemoryLocation = 71
, CreateNewTracks
,
CId_CreateNewTracks = 72
, SelectTracksByName
, CId_SelectTracksByName = 73
, GetEditMode
,
CId_GetEditMode = 74
, SetEditMode
, CId_SetEditMode = 75
, GetEditTool
,
CId_GetEditTool = 76
, SetEditTool
, CId_SetEditTool = 77
, RecallZoomPreset
,
CId_RecallZoomPreset = 78
, GetEditModeOptions
, CId_GetEditModeOptions = 79
, SetEditModeOptions
,
CId_SetEditModeOptions = 80
, SetTimelineSelection
, CId_SetTimelineSelection = 81
, GetTimelineSelection
,
CId_GetTimelineSelection = 82
, ImportVideo
, CId_ImportVideo = 83
, SelectMemoryLocation
,
CId_SelectMemoryLocation = 84
, SetTrackMuteState
, CId_SetTrackMuteState = 85
, SetTrackSoloState
,
CId_SetTrackSoloState = 86
, SetTrackSoloSafeState
, CId_SetTrackSoloSafeState = 87
, SetTrackRecordEnableState
,
CId_SetTrackRecordEnableState = 88
, SetTrackRecordSafeEnableState
, CId_SetTrackRecordSafeEnableState = 89
, SetTrackInputMonitorState
,
CId_SetTrackInputMonitorState = 90
, SetTrackSmartDspState
, CId_SetTrackSmartDspState = 91
, SetTrackHiddenState
,
CId_SetTrackHiddenState = 92
, SetTrackInactiveState
, CId_SetTrackInactiveState = 93
, SetTrackFrozenState
,
CId_SetTrackFrozenState = 94
, SetTrackOnlineState
, CId_SetTrackOnlineState = 95
, SetTrackOpenState
,
CId_SetTrackOpenState = 96
, GetSessionIDs
, CId_GetSessionIDs = 97
, GetMemoryLocationsManageMode
,
CId_GetMemoryLocationsManageMode = 98
, SetMemoryLocationsManageMode
, CId_SetMemoryLocationsManageMode = 99
, SetMainCounterFormat
,
CId_SetMainCounterFormat = 100
, SetSubCounterFormat
, CId_SetSubCounterFormat = 101
, GetMainCounterFormat
,
CId_GetMainCounterFormat = 102
, GetSubCounterFormat
, CId_GetSubCounterFormat = 103
, Undo
,
CId_Undo = 104
, Redo
, CId_Redo = 105
, UndoAll
,
CId_UndoAll = 106
, RedoAll
, CId_RedoAll = 107
, ClearUndoQueue
,
CId_ClearUndoQueue = 108
, SetTrackDSPModeSafeState
, CId_SetTrackDSPModeSafeState = 109
, GetSessionSystemDelayInfo
,
CId_GetSessionSystemDelayInfo = 110
, GroupClips
, CId_GroupClips = 111
, UngroupClips
,
CId_UngroupClips = 112
, UngroupAllClips
, CId_UngroupAllClips = 113
, RegroupClips
,
CId_RegroupClips = 114
, RepeatSelection
, CId_RepeatSelection = 115
, DuplicateSelection
,
CId_DuplicateSelection = 116
, ClearAllMemoryLocations
, CId_ClearAllMemoryLocations = 117
, CId_GetTimeAsType = 118
,
CId_SubtractLocations = 119
, CId_AddLengthToLocation = 120
, CId_SubtractPositions = 121
, CId_AddLengthToPositions = 122
,
CId_ImportAudioToClipList = 123
, CId_SpotClipsByID = 124
, CId_GetClipList = 125
, CId_GetMediaFileInfo = 126
,
CId_CreateAudioClips = 127
, CId_GetExportMixSourceList = 128
, CId_CreateBatchJob = 129
, CId_GetMonitorOutputPath = 130
,
CId_GetEditSelection = 131
, CId_SubscribeToEvents = 132
, CId_GetBatchJobStatus = 133
, CId_BounceTrack = 134
,
CId_PollEvents = 135
, CId_UnsubscribeFromEvents = 136
, CId_CompleteBatchJob = 137
, CId_CancelBatchJob = 138
,
CId_BeginScrub = 139
, CId_EndScrub = 140
, CId_ContinueScrub = 141
, CId_EnableCueProVideoPlugIn = 142
,
CId_UpdateVideo = 143
, CId_EnableAPI = 144
, CId_ExchangePublicKeys = 145
, CId_CreateSignalPath = 146
,
CId_SetTrackMainOutputAssignments = 147
, CId_GetTrackControlInfo = 148
, CId_GetTrackControlValue = 149
, CId_SetTrackControlValue = 150
,
CId_InstallMenuHandler = 151
, CId_UninstallMenuHandler = 152
, CId_SetTrackColor = 153
, CId_GetTrackPlaylists = 154
,
CId_SetTrackTimebase = 155
, CId_GetColorPalette = 156
, CId_DeleteTracks = 157
, CId_GetPlaylistElements = 158
,
CId_WriteSelectedTranscriptionToJSONFile = 159
 }
Pro Tools command type.
enum class TaskStatus : int32_t {
NoResponseReceived
, TStatus_NoResponseReceived = -1
, Queued
, TStatus_Queued = 0
,
Pending
, TStatus_Pending = 1
, InProgress
, TStatus_InProgress = 2
,
Completed
, TStatus_Completed = 3
, Failed
, TStatus_Failed = 4
,
WaitingForUserInput
, TStatus_WaitingForUserInput = 5
, CompletedWithBadResponse
, TStatus_CompletedWithBadResponse = 6
,
FailedWithBadErrorResponse
, TStatus_FailedWithBadErrorResponse = 7
 }
Status of execution of the Pro Tools task.
enum class CommandErrorType : int32_t {
CEType_None = -1
, OS_WritePermissions
, CEType_OS_WritePermissions = 0
, OS_ErrorCode
,
CEType_OS_ErrorCode = 1
, OS_NoLocationFound
, CEType_OS_NoLocationFound = 2
, OS_NoSessionFound
,
CEType_OS_NoSessionFound = 3
, OS_FilePathLocation
, OS_ReadError
, CEType_OS_ReadError = 5
,
OS_DiskSpace
, CEType_OS_DiskSpace = 6
, OS_DuplicateName
, CEType_OS_DuplicateName = 7
,
OS_IllegalCharacters
, CEType_OS_IllegalCharacters = 8
, OS_CharactersLimit
, CEType_OS_CharactersLimit = 9
,
OS_ProToolsIsNotAvailable
, CEType_OS_ProToolsIsNotAvailable = 10
, OS_NoFilePathFound
, CEType_OS_NoFilePathFound = 11
,
PT_UnknownError
, CEType_PT_UnknownError = 100
, PT_NoTemplateGroup
, CEType_PT_NoTemplateGroup = 101
,
PT_NoTemplate
, CEType_PT_NoTemplate = 102
, PT_SampleRateMismatch
, CEType_PT_SampleRateMismatch
,
PT_NoVideoTrackFound
, CEType_PT_NoVideoTrackFound
, PT_NoTracksFound
, CEType_PT_NoTracksFound = 105
,
PT_NoOpenedSession
, CEType_PT_NoOpenedSession = 106
, PT_NoTrackFound
, CEType_PT_NoTrackFound = 107
,
PT_NoClipsFound
, CEType_PT_NoClipsFound = 108
, PT_NoSelection
, CEType_PT_NoSelection = 109
,
PT_RecordDrive
, CEType_PT_RecordDrive = 110
, PT_NoPresetFound
, CEType_PT_NoPresetFound = 111
,
PT_FileTypeMXF
, CEType_PT_FileTypeMXF = 112
, PT_CopyOptionCopy
, CEType_PT_CopyOptionCopy
,
PT_CopyOptionLink
, CEType_PT_CopyOptionLink
, PT_QuantizeEdits
, CEType_PT_QuantizeEdits
,
PT_ExportAsMultichannel
, CEType_PT_ExportAsMultichannel
, PT_IllegalCharactersComments
, CEType_PT_IllegalCharactersComments = 117
,
PT_IllegalCharactersSequenceName
, CEType_PT_IllegalCharactersSequenceName = 118
, PT_MaxCharactersComments
, CEType_PT_MaxCharactersComments = 119
,
PT_MaxCharactersSequenceName
, CEType_PT_MaxCharactersSequenceName = 120
, PT_NoSequenceName
, CEType_PT_NoSequenceName = 121
,
PT_InvalidTask
, CEType_PT_InvalidTask = 122
, PT_FileNotFound
, CEType_PT_FileNotFound = 123
,
PT_InvalidSelection
, CEType_PT_InvalidSelection = 124
, PT_ReadOnlySession
, CEType_PT_ReadOnlySession
,
PT_InvalidParameter
, CEType_PT_InvalidParameter = 126
, PT_Forbidden
, CEType_PT_Forbidden = 127
,
PT_NoTimelineFound
, CEType_PT_NoTimelineFound = 128
, PT_ArgumentOutOfRange
, CEType_PT_ArgumentOutOfRange = 129
,
PT_ForbiddenTrackType
, CEType_PT_ForbiddenTrackType = 130
, PT_NoVideoEngineFound
, CEType_PT_NoVideoEngineFound = 131
,
PT_NoDspHardwareFound
, CEType_PT_NoDspHardwareFound = 132
, PT_UnsupportedCommand
, CEType_PT_UnsupportedCommand = 133
,
PT_HostNotReady
, CEType_PT_HostNotReady = 134
, PT_CannotBeDone
, CEType_PT_CannotBeDone
,
PT_ResponseLengthExceeded
, CEType_PT_ResponseLengthExceeded = 136
, PT_CommandTimeout
, CEType_PT_CommandTimeout = 137
,
PT_HostIsBusy
, CEType_PT_HostIsBusy = 138
, CEType_PT_DeprecatedParameter = 139
, CEType_PT_DeprecatedParameterValue = 140
,
CEType_PT_GlobalRendererRequired = 141
, PT_Info
, CEType_PT_Info = 200
, SDK_Error
,
CEType_SDK_Error
, SDK_VersionMismatch
, CEType_SDK_VersionMismatch = 401
, SDK_NotImplemented
,
CEType_SDK_NotImplemented = 402
, SDK_SessionIdParseError
, CEType_SDK_SessionIdParseError = 403
, SDK_GrpcGeneric
,
CEType_SDK_GrpcGeneric = 501
 }
Type of the error message which can be returned to user.
enum class FileType : int32_t {
FType_Unknown = 0
, WAVE = 1
, FType_WAVE = 1
, AIFF = 2
,
FType_AIFF = 2
, AAF = 3
, FType_AAF = 3
, OMF = 4
,
FType_OMF = 4
 }
Type of Pro Tools file.
enum class SampleRate : int32_t {
SRate_Unknown = 0
, SR_None = 1
, SRate_None = 1
, SR_44100 = 44100
,
SRate_44100 = 44100
, SR_48000 = 48000
, SRate_48000 = 48000
, SR_88200 = 88200
,
SRate_88200 = 88200
, SR_96000 = 96000
, SRate_96000 = 96000
, SR_176400 = 176400
,
SRate_176400 = 176400
, SR_192000 = 192000
, SRate_192000 = 192000
 }
Type of Pro Tools session/project sample rate.
enum class IOSettings : int32_t {
IOSettings_Unknown = 0
, IO_None = 1
, IOSettings_None = 1
, IO_Last = 2
,
IOSettings_Last = 2
, IO_StereoMix = 3
, IOSettings_StereoMix = 3
, IO_51FilmMix = 4
,
IOSettings_51FilmMix = 4
, IO_51SMPTEMix = 5
, IOSettings_51SMPTEMix = 5
, IO_51DTSMix = 6
,
IOSettings_51DTSMix = 6
, IO_UserDefined = 7
, IOSettings_UserDefined = 7
 }
Type of Pro Tools input/output settings.
enum class BitDepth : int32_t {
BDepth_Unknown = 0
, None = 1
, BDepth_None = 1
, Bit16 = 2
,
BDepth_16 = 2
, Bit24 = 3
, BDepth_24 = 3
, Bit32Float = 4
,
BDepth_32Float = 4
 }
Available bit depth for file.
enum class ImportType : int32_t {
IType_Unknown = 0
, Session = 1
, IType_Session = 1
, Audio = 2
,
IType_Audio = 2
 }
Types of data which can be imported into Pro Tools.
enum class AudioMediaOptions : int32_t {
AMOptions_Unknown = 0
, LinkToSource = 1
, AMOptions_LinkToSource = 1
, CopyFromSource = 2
,
AMOptions_CopyFromSource = 2
, ConsolidateFromSource = 3
, AMOptions_ConsolidateFromSource = 3
, ForceToTargetSessionFormat = 4
,
AMOptions_ForceToTargetSessionFormat = 4
 }
Audio import options.
enum class VideoMediaOptions : int32_t {
VMOptions_Unknown = 0
, LinkToSource = 1
, VMOptions_LinkToSourceVideo = 1
, CopyFromSource = 2
,
VMOptions_CopyFromSourceVideo = 2
 }
Video import options.
enum class MatchTrackOptions : int32_t {
MTOptions_Unknown = 0
, None = 1
, MTOptions_None = 1
, MatchTracks = 2
,
MTOptions_MatchTracks = 2
, ImportAsNewTrack = 3
, MTOptions_ImportAsNewTrack = 3
 }
Options for matching tracks during import.
enum class MainPlaylistOptions : int32_t {
MPOptions_Unknown = 0
, ImportReplaceExistingPlaylists = 1
, MPOptions_ImportReplaceExistingPlaylists = 1
, ImportOverlayNewOnExistingPlaylists = 2
,
MPOptions_ImportOverlayNewOnExistingPlaylists = 2
, DoNotImport = 3
, MPOptions_DoNotImport = 3
 }
Options for playlists import.
enum class AudioOperations : int32_t {
AOperations_Unknown = 0
, AddAudio = 1
, AOperations_AddAudio = 1
, CopyAudio = 2
,
AOperations_CopyAudio = 2
, ConvertAudio = 3
, AOperations_ConvertAudio = 3
, Default = 4
,
AOperations_Default = 4
 }
Operations for audio import.
enum class MediaDestination : int32_t {
MDestination_Unknown = 0
, None = 1
, MDestination_None = 1
, MainVideoTrack = 2
,
MDestination_MainVideoTrack = 2
, NewTrack = 3
, MDestination_NewTrack = 3
, ClipList = 4
,
MDestination_ClipList = 4
 }
Types of destination.
enum class MediaLocation : int32_t {
MLocation_Unknown = 0
, None = 1
, MLocation_None = 1
, SessionStart = 2
,
MLocation_SessionStart = 2
, SongStart = 3
, MLocation_SongStart = 3
, Selection = 4
,
MLocation_Selection = 4
, Spot = 5
, MLocation_Spot = 5
 }
Types of location in the session.
enum class TrackType : int32_t {
TType_Unknown = 0
, TT_Unknown
, Unknown = 0
, TType_Midi = 1
,
TT_Midi
, Midi = 1
, TType_Audio = 2
, TT_Audio
,
AudioTrack = 2
, TType_Aux = 3
, TT_Aux
, Aux = 3
,
TType_Video = 4
, TT_Video
, VideoTrack = 4
, TType_Vca = 5
,
TT_Vca
, Vca = 5
, TType_Tempo = 6
, TT_Tempo
,
Tempo = 6
, TType_Markers = 7
, TT_Markers
, Markers = 7
,
TType_Meter = 8
, TT_Meter
, Meter = 8
, TType_KeySignature = 9
,
TT_KeySignature
, KeySignature = 9
, TType_ChordSymbols = 10
, TT_ChordSymbols
,
ChordSymbols = 10
, TType_Instrument = 11
, TT_Instrument
, Instrument = 11
,
TType_Master = 12
, TT_Master
, Master = 12
, TType_Heat = 13
,
TT_Heat
, Heat = 13
, TType_BasicFolder = 14
, TT_BasicFolder
,
BasicFolder = 14
, TType_RoutingFolder = 15
, TT_RoutingFolder
, RoutingFolder = 15
,
TType_CompLane = 16
, TT_CompLane
, CompLane = 16
 }
Type of Pro Tools track.
enum class TrackFormat : int32_t {
TF_Unknown = 0
, TFormat_Unknown = 0
, TF_Mono = 1
, TFormat_Mono = 1
,
TF_Stereo = 2
, TFormat_Stereo = 2
, TF_LCR = 3
, TFormat_LCR = 3
,
TF_LCRS = 4
, TFormat_LCRS = 4
, TF_Quad = 5
, TFormat_Quad = 5
,
TF_5_0 = 6
, TFormat_5_0 = 6
, TF_5_1 = 7
, TFormat_5_1 = 7
,
TF_5_0_2 = 8
, TFormat_5_0_2 = 8
, TF_5_1_2 = 9
, TFormat_5_1_2 = 9
,
TF_5_0_4 = 10
, TFormat_5_0_4 = 10
, TF_5_1_4 = 11
, TFormat_5_1_4 = 11
,
TF_6_0 = 12
, TFormat_6_0 = 12
, TF_6_1 = 13
, TFormat_6_1 = 13
,
TF_7_0 = 14
, TFormat_7_0 = 14
, TF_7_1 = 15
, TFormat_7_1 = 15
,
TF_7_0_SDDS = 16
, TFormat_7_0_SDDS = 16
, TF_7_1_SDDS = 17
, TFormat_7_1_SDDS = 17
,
TF_7_0_2 = 18
, TFormat_7_0_2 = 18
, TF_7_1_2 = 19
, TFormat_7_1_2 = 19
,
TF_7_0_4 = 20
, TFormat_7_0_4 = 20
, TF_7_1_4 = 21
, TFormat_7_1_4 = 21
,
TF_7_0_6 = 22
, TFormat_7_0_6 = 22
, TF_7_1_6 = 23
, TFormat_7_1_6 = 23
,
TF_9_0_4 = 24
, TFormat_9_0_4 = 24
, TF_9_1_4 = 25
, TFormat_9_1_4 = 25
,
TF_9_0_6 = 26
, TFormat_9_0_6 = 26
, TF_9_1_6 = 27
, TFormat_9_1_6 = 27
,
TF_1stOrderAmbisonics = 28
, TFormat_1stOrderAmbisonics = 28
, TF_2ndOrderAmbisonics = 29
, TFormat_2ndOrderAmbisonics = 29
,
TF_3rdOrderAmbisonics = 30
, TFormat_3rdOrderAmbisonics = 30
, TF_4thOrderAmbisonics = 31
, TFormat_4thOrderAmbisonics = 31
,
TF_5thOrderAmbisonics = 32
, TFormat_5thOrderAmbisonics = 32
, TF_6thOrderAmbisonics = 33
, TFormat_6thOrderAmbisonics = 33
,
TF_7thOrderAmbisonics = 34
, TFormat_7thOrderAmbisonics = 34
, TF_None = 35
, TFormat_None = 35
,
TF_2_1 = 36
, TFormat_2_1 = 36
, TF_Overhead = 37
, TFormat_Overhead = 37
 }
Format of Pro Tools track.
enum class TrackTimebase : int32_t {
TTB_Unknown = 0
, TTimebase_Unknown = 0
, TTB_Samples = 1
, TTimebase_Samples = 1
,
TTB_Ticks = 2
, TTimebase_Ticks = 2
, TTB_None = 3
, TTimebase_None = 3
 }
Timebase of Pro Tools track.
enum class TimeCodeMappingOptions : int32_t {
TCMOptions_Unknown = 0
, MaintainAbsoluteTimeCodeValues = 1
, TCMOptions_MaintainAbsoluteTimeCodeValues = 1
, MaintainRelativeTimeCodeValues = 2
,
TCMOptions_MaintainRelativeTimeCodeValues = 2
, MapStartTimeCodeTo = 3
, TCMOptions_MapStartTimeCodeTo = 3
 }
Options for time code mapping.
enum class TrackOffsetOptions : int32_t {
TOOptions_Unknown = 0
, BarsBeats = 1
, TOOptions_BarsBeats = 1
, MinSecs = 2
,
TOOptions_MinSecs = 2
, TimeCode = 3
, TOOptions_TimeCode = 3
, FeetFrames = 4
,
TOOptions_FeetFrames = 4
, Samples = 5
, TOOptions_Samples = 5
 }
enum class SpotLocationType : int32_t {
SLType_Unknown = 0
, Start = 1
, SLType_Start = 1
, SyncPoint = 2
,
SLType_SyncPoint = 2
, End = 3
, SLType_End = 3
 }
The types of location for Spot Mode.
enum class TimelineLocationType {
TLType_Unknown
, TLType_Samples
, TLType_Ticks
, TLType_Frames
,
TLType_MinSecs
, TLType_TimeCode
, TLType_BarsBeats
, TLType_FeetFrames
,
TLType_Seconds
 }
Types for global timeline times.
enum class TrackAttributeState : int32_t {
TAState_Unknown = 0
, None = 1
, TAState_None = 1
, SetExplicitly = 2
,
TAState_SetExplicitly = 2
, SetImplicitly = 3
, TAState_SetImplicitly = 3
, SetExplicitlyAndImplicitly = 4
,
TAState_SetExplicitlyAndImplicitly = 4
 }
Type of the state and the way a track attribute is set.
enum class TrackListFilter : int32_t {
TLFilter_Unknown = 0
, All = 1
, TLFilter_All = 1
, Selected = 2
,
TLFilter_Selected = 2
, SelectedExplicitly = 3
, TLFilter_SelectedExplicitly = 3
, SelectedImplicitly = 4
,
TLFilter_SelectedImplicitly = 4
, WithClipsOnMainPlaylist = 5
, TLFilter_WithClipsOnMainPlaylist = 5
, WithAutomationOnMainPlaylist = 6
,
TLFilter_WithAutomationOnMainPlaylist = 6
, Inactive = 7
, TLFilter_Inactive = 7
, InactiveExplicitly = 8
,
TLFilter_InactiveExplicitly = 8
, InactiveImplicitly = 9
, TLFilter_InactiveImplicitly = 9
, Hidden = 10
,
TLFilter_Hidden = 10
, HiddenExplicitly = 11
, TLFilter_HiddenExplicitly = 11
, HiddenImplicitly = 12
,
TLFilter_HiddenImplicitly = 12
, Locked = 13
, TLFilter_Locked = 13
, Muted = 14
,
TLFilter_Muted = 14
, Frozen = 15
, TLFilter_Frozen = 15
, Open = 16
,
TLFilter_Open = 16
, Online = 17
, TLFilter_Online = 17
 }
Types of track list filters.
enum class ExportFormat : int32_t {
EFormat_Unknown = 0
, None = 1
, EFormat_None = 1
, Mono = 2
,
EFormat_Mono = 2
, MultipleMono = 3
, EFormat_MultipleMono = 3
, Interleaved = 4
,
EFormat_Interleaved = 4
 }
Exported clips format.
enum class ExportFileType : int32_t {
EFType_Unknown = 0
, WAV = 1
, EFType_WAV = 1
, AIFF = 2
,
EFType_AIFF = 2
, MXF = 3
, EFType_MXF = 3
 }
The types of files which the clips will be exported to.
enum class ResolveDuplicateNamesBy : int32_t {
RDNBy_Unknown = 0
, AutoRenaming = 1
, RDNBy_AutoRenaming = 1
, ReplacingWithNewFiles = 2
,
RDNBy_ReplacingWithNewFiles = 2
 }
Types of possible duplicate names resolution.
enum class ExportAsAAFFileType : int32_t {
EAAFFType_Unknown = 0
, EAAFFType_None = 1
, WAV = 2
, EAAFFType_WAV = 2
,
AIFF = 3
, EAAFFType_AIFF = 3
, MXF = 4
, EAAFFType_MXF = 4
,
Embedded = 5
, EAAFFType_Embedded = 5
 }
The types of files which the tracks will be exported to as AAF/OMF.
enum class AAFFileBitDepth : int32_t {
AAFFBDepth_Unknown = 0
, AAFFBDepth_None = 1
, Bit16 = 2
, AAFFBDepth_Bit16 = 2
,
Bit24 = 3
, AAFFBDepth_Bit24 = 3
 }
Available bit depth for file exported as AAF/OMF.
enum class CopyOption : int32_t {
COption_Unknown = 0
, ConsolidateFromSourceMedia = 1
, COption_ConsolidateFromSourceMedia = 1
, CopyFromSourceMedia = 2
,
COption_CopyFromSourceMedia = 2
, LinkFromSourceMedia = 3
, COption_LinkFromSourceMedia = 3
 }
Available options for copying media while exporting tracks as AAF/OMF files.
enum class FileLocationTypeFilter : int32_t {
FLTFilter_Unknown = 0
, All_Files = 1
, FLTFilter_AllFiles = 1
, OnTimeline_Files = 2
,
FLTFilter_OnTimelineFiles = 2
, NotOnTimeline_Files = 3
, FLTFilter_NotOnTimelineFiles = 3
, Online_Files = 4
,
FLTFilter_OnlineFiles = 4
, Offline_Files = 5
, FLTFilter_OfflineFiles = 5
, Audio_Files = 6
,
FLTFilter_AudioFiles = 6
, Video_Files = 7
, FLTFilter_VideoFiles = 7
, Rendered_Files = 8
,
FLTFilter_RenderedFiles = 8
, SelectedClipsTimeline = 101
, FLTFilter_SelectedClipsTimeline = 101
, SelectedClipsClipsList = 102
,
FLTFilter_SelectedClipsClipsList = 102
, FLTFilter_Count
 }
Types of the filters which can be applied for session file gathering.
enum class AutomationDataOptions : int32_t {
ADOptions_Unknown = 0
, All_Automation = 1
, ADOptions_AllAutomation = 1
, Pan_Automation = 2
,
ADOptions_PanAutomation = 2
, PlugIn_Automation = 3
, ADOptions_PlugInAutomation = 3
, Clip_Gain = 4
,
ADOptions_ClipGain = 4
, Clip_Effects = 5
, ADOptions_ClipEffects = 5
 }
Automation data options used with cut/copy/clear commands.
enum class PasteSpecialOptions : int32_t {
PSOptions_Unknown = 0
, Merge = 1
, MergeMidi = 1
, PSOptions_MergeMidi = 1
,
Repeat_To_Fill_Selection = 2
, PSOptions_RepeatToFillSelection = 2
, To_Current_Automation_Type = 3
, PSOptions_ToCurrentAutomationType = 3
,
MergeMarkers = 4
, PSOptions_MergeMarkers = 4
 }
Options used with the paste special command.
enum class TripleBool : int32_t {
TBool_Unknown = 0
, TB_None = 1
, TBool_None = 1
, TB_False = 2
,
TBool_False = 2
, TB_True = 3
, TBool_True = 3
 }
Boolean with `unset` value.
enum class EM_SourceType : int32_t {
EMSType_Unknown = 0
, PhysicalOut = 1
, EMSType_PhysicalOut = 1
, Bus = 2
,
EMSType_Bus = 2
, Output = 3
, EMSType_Output = 3
 }
Available source types for mix source.
enum class EM_FileType : int32_t {
EMFType_Unknown = 0
, None = 1
, EMFType_None = 1
, MOV = 2
,
EMFType_MOV = 2
, WAV = 3
, EMFType_WAV = 3
, AIFF = 4
,
EMFType_AIFF = 4
, MP3 = 5
, EMFType_MP3 = 5
, MXFOPAtom = 6
,
EMFType_MXFOPAtom = 6
, WAVADM = 7
, EMFType_WAVADM = 7
 }
Available file type for mix export.
enum class CompressionType : int32_t {
CType_Unknown = 0
, None = 1
, CType_None = 1
, PCM = 2
,
CType_PCM = 2
 }
Available compression type for audio.
enum class EM_VideoExportOptions : int32_t {
EMVEOptions_Unknown = 0
, None = 1
, EMVEOptions_None = 1
, SameAsSource = 2
,
EMVEOptions_SameAsSource = 2
, Transcode = 3
, EMVEOptions_Transcode = 3
 }
Available options for export video.
enum class EM_FileDestination : int32_t {
EMFDestination_Unknown = 0
, None = 1
, EMFDestination_None = 1
, SessionFolder = 2
,
EMFDestination_SessionFolder = 2
, Directory = 3
, EMFDestination_Directory = 3
 }
Available types of file destination.
enum class EM_DeliveryFormat : int32_t {
EMDFormat_Unknown = 0
, None = 1
, EMDFormat_None = 1
, FilePerMixSource = 2
,
EMDFormat_FilePerMixSource = 2
, SingleFile = 3
, EMDFormat_SingleFile = 3
 }
Available delivery formats.
enum class DP_ValueTypes : int32_t {
DPVTypes_Unknown = 0
, DP_VT_double = 1
, DPVTypes_Double = 1
, DP_VT_float = 2
,
DPVTypes_Float = 2
, DP_VT_int32 = 3
, DPVTypes_Int32 = 3
, DP_VT_int64 = 4
,
DPVTypes_Int64 = 4
, DP_VT_uint32 = 5
, DPVTypes_Uint32 = 5
, DP_VT_uint64 = 6
,
DPVTypes_Uint64 = 6
, DP_VT_sint32 = 7
, DPVTypes_Sint32 = 7
, DP_VT_sint64 = 8
,
DPVTypes_Sint64 = 8
, DP_VT_fixed32 = 9
, DPVTypes_Fixed32 = 9
, DP_VT_fixed64 = 10
,
DPVTypes_Fixed64 = 10
, DP_VT_sfixed32 = 11
, DPVTypes_Sfixed32 = 11
, DP_VT_sfixed64 = 12
,
DPVTypes_Sfixed64 = 12
, DP_VT_bool = 13
, DPVTypes_Bool = 13
, DP_VT_string = 14
,
DPVTypes_String = 14
, DP_VT_bytes = 15
, DPVTypes_Bytes = 15
, DP_VT_enum = 16
,
DPVTypes_Enum = 16
, DP_VT_object = 17
, DPVTypes_Object = 17
 }
Available data types for dynamic properties.
enum class DynamicPropertyType : int32_t {
DPType_Unknown = 0
, DP_EM_CodecInfo = 1
, DPType_CodecInfo = 1
, DP_EM_DolbyAtmosInfo = 2
,
DPType_DolbyAtmosInfo = 2
 }
Available types of dynamic properties.
enum class TrackListType : int32_t {
TListType_Unknown = 0
, AllTracks = 1
, TListType_AllTracks = 1
, SelectedTracksOnly = 2
,
TListType_SelectedTracksOnly = 2
 }
Available track list types.
enum class FadeHandlingType : int32_t {
FHType_Unknown = 0
, ShowCrossfades = 1
, FHType_ShowCrossfades = 1
, DontShowCrossfades = 2
,
FHType_DontShowCrossfades = 2
, CombineCrossfadedClips = 3
, FHType_CombineCrossfadedClips = 3
 }
Available fade handling types.
enum class TextAsFileFormat : int32_t {
TFFormat_Unknown = 0
, TextEdit = 1
, TFFormat_TextEdit = 1
, UTF8 = 2
,
TFFormat_UTF8 = 2
 }
Available file formats.
enum class ESI_OutputType : int32_t {
ESI_Unknown = 0
, ESIOType_Unknown = 0
, ESI_File = 1
, ESIOType_File = 1
,
ESI_String = 2
, ESIOType_String = 2
 }
Available output types.
enum class PlaybackMode : int32_t {
PMode_Unknown = 0
, PM_Normal = 1
, PMode_Normal = 1
, PM_Loop = 2
,
PMode_Loop = 2
, PM_DynamicTransport = 3
, PMode_DynamicTransport = 3
 }
Types of the playback mode.
enum class RecordMode : int32_t {
RMode_Unknown = 0
, RM_Normal = 1
, RMode_Normal = 1
, RM_Loop = 2
,
RMode_Loop = 2
, RM_Destructive = 3
, RMode_Destructive = 3
, RM_QuickPunch = 4
,
RMode_QuickPunch = 4
, RM_TrackPunch = 5
, RMode_TrackPunch = 5
, RM_DestructivePunch = 6
,
RMode_DestructivePunch = 6
 }
Types of the record mode.
enum class SessionAudioFormat : int32_t {
SAFormat_Unknown = 0
, SAF_WAVE = 1
, SAFormat_WAVE = 1
, SAF_AIFF = 2
,
SAFormat_AIFF = 2
 }
Type of session audio file format.
enum class SessionTimeCodeRate : int32_t {
STCRate_Unknown = 0
, STCR_Fps23976 = 1
, STCRate_Fps23976 = 1
, STCR_Fps24 = 2
,
STCRate_Fps24 = 2
, STCR_Fps25 = 3
, STCRate_Fps25 = 3
, STCR_Fps2997 = 4
,
STCRate_Fps2997 = 4
, STCR_Fps2997Drop = 5
, STCRate_Fps2997Drop = 5
, STCR_Fps30 = 6
,
STCRate_Fps30 = 6
, STCR_Fps30Drop = 7
, STCRate_Fps30Drop = 7
, STCR_Fps47952 = 8
,
STCRate_Fps47952 = 8
, STCR_Fps48 = 9
, STCRate_Fps48 = 9
, STCR_Fps50 = 10
,
STCRate_Fps50 = 10
, STCR_Fps5994 = 11
, STCRate_Fps5994 = 11
, STCR_Fps5994Drop = 12
,
STCRate_Fps5994Drop = 12
, STCR_Fps60 = 13
, STCRate_Fps60 = 13
, STCR_Fps60Drop = 14
,
STCRate_Fps60Drop = 14
, STCR_Fps100 = 15
, STCRate_Fps100 = 15
, STCR_Fps11988 = 16
,
STCRate_Fps11988 = 16
, STCR_Fps11988Drop = 17
, STCRate_Fps11988Drop = 17
, STCR_Fps120 = 18
,
STCRate_Fps120 = 18
, STCR_Fps120Drop = 19
, STCRate_Fps120Drop = 19
 }
Type of session time code rate.
enum class SessionFeetFramesRate : int32_t {
SFFRate_Unknown = 0
, SFFR_Fps23976 = 1
, SFFRate_Fps23976 = 1
, SFFR_Fps24 = 2
,
SFFRate_Fps24 = 2
, SFFR_Fps25 = 3
, SFFRate_Fps25 = 3
 }
Type of session feet+frames rate.
enum class SessionRatePull : int32_t {
SRPull_Unknown = 0
, SRP_None = 1
, SRPull_None = 1
, SRP_Up01 = 2
,
SRPull_Up01 = 2
, SRP_Down01 = 3
, SRPull_Down01 = 3
, SRP_Up4 = 4
,
SRPull_Up4 = 4
, SRP_Up4Up01 = 5
, SRPull_Up4Up01 = 5
, SRP_Up4Down01 = 6
,
SRPull_Up4Down01 = 6
, SRP_Down4 = 7
, SRPull_Down4 = 7
, SRP_Down4Up01 = 8
,
SRPull_Down4Up01 = 8
, SRP_Down4Down01 = 9
, SRPull_Down4Down01 = 9
 }
Type of session audio/video rate pull up/down.
enum class VersionedPTSLComponents : int32_t {
VPTSLComponents_Unknown = 0
, Host = 1
, VPTSLComponents_Host = 1
, Client = 2
,
VPTSLComponents_Client = 2
, ClientAPI = 3
, VPTSLComponents_ClientAPI = 3
 }
We provide versioning of such kinds of PTSL components.
enum class TransportState : int32_t {
TState_Unknown = 0
, TS_TransportPlaying = 1
, TState_TransportPlaying = 1
, TS_TransportStopped = 2
,
TState_TransportStopped = 2
, TS_TransportRecording = 3
, TState_TransportRecording = 3
, TS_TransportPlayingHalfSpeed = 4
,
TState_TransportPlayingHalfSpeed = 4
, TS_TransportRecordingHalfSpeed = 5
, TState_TransportRecordingHalfSpeed = 5
, TS_TransportFastForward = 6
,
TState_TransportFastForward = 6
, TS_TransportRewind = 7
, TState_TransportRewind = 7
, TS_TransportScrub = 8
,
TState_TransportScrub = 8
, TS_TransportShuttle = 9
, TState_TransportShuttle = 9
, TS_TransportPrimed = 10
,
TState_TransportPrimed = 10
, TS_TransportIsCueing = 11
, TState_TransportIsCueing = 11
, TS_TransportIsCued = 12
,
TState_TransportIsCued = 12
, TS_TransportIsCuedForPreview = 13
, TState_TransportIsCuedForPreview = 13
, TS_TransportIsStopping = 14
,
TState_TransportIsStopping = 14
, TS_TransportIsPreviewing = 15
, TState_TransportIsPreviewing = 15
 }
Types of the transport state.
enum class ClipLocation : int32_t {
CLocation_Unknown = 0
, CL_ClipsList = 1
, CLocation_ClipsList = 1
, CL_Timeline = 2
,
CLocation_Timeline = 2
 }
Types of the clip locations.
enum class TimeProperties : int32_t {
TProperties_Unknown = 0
, TP_Marker = 1
, TProperties_Marker = 1
, TP_Selection = 2
,
TProperties_Selection = 2
, TP_None = 3
, TProperties_None = 3
 }
Type of time properties.
enum class MarkerLocation : int32_t {
MLC_Unknown = 0
, MarkerLocation_Unknown = 0
, MLC_MainRuler = 1
, MarkerLocation_MainRuler = 1
,
MLC_Track = 2
, MarkerLocation_Track = 2
 }
Type of marker location.
enum class MemoryLocationReference : int32_t {
MLReference_Unknown = 0
, MLR_BarBeat = 1
, MLReference_BarBeat = 1
, MLR_Absolute = 2
,
MLReference_Absolute = 2
, MLR_FollowTrackTimebase = 3
, MLReference_FollowTrackTimebase = 3
 }
Type of memory location reference.
enum class TrackInsertionPoint {
TIPoint_Unknown = 0
, TIPoint_Before = 1
, TIPoint_After = 2
, TIPoint_First = 3
,
TIPoint_Last = 4
 }
Enumeration that describes the position of the insertion point for creating new tracks.
enum class EditMode : int32_t {
EMO_Unknown = 0
, EMode_Unknown = 0
, EMO_Shuffle = 1
, EMode_Shuffle = 1
,
EMO_Slip = 2
, EMode_Slip = 2
, EMO_Spot = 3
, EMode_Spot = 3
,
EMO_GridAbsolute = 4
, EMode_GridAbsolute = 4
, EMO_GridRelative = 5
, EMode_GridRelative = 5
,
EMO_ShuffleSnapToGridAbsolute = 6
, EMode_ShuffleSnapToGridAbsolute = 6
, EMO_SlipSnapToGridAbsolute = 7
, EMode_SlipSnapToGridAbsolute = 7
,
EMO_SpotSnapToGridAbsolute = 8
, EMode_SpotSnapToGridAbsolute = 8
, EMO_ShuffleSnapToGridRelative = 9
, EMode_ShuffleSnapToGridRelative = 9
,
EMO_SlipSnapToGridRelative = 10
, EMode_SlipSnapToGridRelative = 10
, EMO_SpotSnapToGridRelative = 11
, EMode_SpotSnapToGridRelative = 11
 }
Type of edit mode.
enum class EditTool : int32_t {
ET_Unknown = 0
, ETool_Unknown = 0
, ET_ZoomNormal = 1
, ETool_ZoomNormal = 1
,
ET_ZoomSingle = 2
, ETool_ZoomSingle = 2
, ET_TrimStandard = 3
, ETool_TrimStandard = 3
,
ET_TrimTce = 4
, ETool_TrimTce = 4
, ET_TrimScrub = 5
, ETool_TrimScrub = 5
,
ET_TrimLoop = 6
, ETool_TrimLoop = 6
, ET_Selector = 7
, ETool_Selector = 7
,
ET_GrabberTime = 8
, ETool_GrabberTime = 8
, ET_GrabberSeparation = 9
, ETool_GrabberSeparation = 9
,
ET_GrabberObject = 10
, ETool_GrabberObject = 10
, ET_SmartTool = 11
, ETool_SmartTool = 11
,
ET_Scrubber = 12
, ETool_Scrubber = 12
, ET_PencilFreeHand = 13
, ETool_PencilFreeHand = 13
,
ET_PencilLine = 14
, ETool_PencilLine = 14
, ET_PencilTriangle = 15
, ETool_PencilTriangle = 15
,
ET_PencilSquare = 16
, ETool_PencilSquare = 16
, ET_PencilRandom = 17
, ETool_PencilRandom = 17
,
ET_PencilParabolic = 18
, ETool_PencilParabolic = 18
, ET_PencilSCurve = 19
, ETool_PencilSCurve = 19
 }
Type of edit tool.
enum class TimelineUpdateVideo : int32_t {
TUV_Unknown = 0
, TUVideo_Unknown = 0
, TUV_None = 1
, TUVideo_None = 1
,
TUV_In = 2
, TUVideo_In = 2
, TUV_Out = 3
, TUVideo_Out = 3
 }
enum class SelectionMode : int32_t {
SM_Unknown = 0
, SMode_Unknown = 0
, SM_Replace = 1
, SMode_Replace = 1
,
SM_Add = 2
, SMode_Add = 2
, SM_Subtract = 3
, SMode_Subtract = 3
 }
Type of the track's possible selection.
enum class TrackFromClipGroupExclusionReason {
TCGEReason_Unknown = 0
, TCGEReason_TrackTypeIsNotAllowed = 1
, TCGEReason_TrackIsFrozen = 2
, TCGEReason_TrackIsClosed = 3
,
TCGEReason_TrackIsLocked = 4
, TCGEReason_TrackIsInPlaylistView = 5
, TCGEReason_TrackIsElasticAudioWithFades = 6
 }
Possible reasons why clip groups could not be created on specific tracks.
enum class BasicTimeType { BTType_Unknown
, BTType_Samples
, BTType_Ticks
, BTType_Frames
 }
One of the fundamental time units.
Functions
template<class T >
bool IsCancellationRequested (const std::future< T > &cancellation)
Utility method that checks whether cancellation of Task (std::future<void>) is required.
template<class T >
void AsyncDelay (const std::future< T > &cancellation, std::chrono::milliseconds delay=std::chrono::milliseconds(1))
Utility method that asynchronously waits for the specified task to complete within a specified delay.
template<class Request , class Response , class ClientPtr , class ClientFunctionPtr >
std::shared_ptr< Response > AsyncWait (ClientFunctionPtr func, ClientPtr ptr, const Request &request)
Utility method that runs the function func asynchronously (potentially in a separate thread which might be a part of a thread pool) and waits for the result of this function, and returns the result.
template<class ClientPtr , class ClientFunction , class... Args>
void AsyncWait2 (ClientPtr caller, ClientFunction callerFunc, Args &&... args)
std::vector< unsigned char > encrypt (const std::string &text, const std::string &encryptionKey)
Encrypts a text string with given RSA key.
std::string encodeBase64 (const std::vector< unsigned char > &data)
Encodes byte array into base 64 string.
static google::protobuf::util::JsonOptions DefaultJsonWriteOptions ()
static google::protobuf::util::JsonParseOptions DefaultJsonParseOptions ()
template<class Dest , class Src >
bool Is (const Src *exc)
Utility method that checks object type.
template<typename EnumT , typename DescriptorT >
std::string GetStringFromEnum (const DescriptorT *descriptor, EnumT value)
template<typename EnumT , typename DescriptorT >
std::optional< EnumT > GetEnumFromString (const DescriptorT *descriptor, const std::string &value)
PTSLC_CPP_EXPORT std::vector< std::string > EnumValuesToStrings (const std::string &enumTypeName)
DEFINE_PTSL_ENUM_CONVERSIONS (CommandId)
DEFINE_PTSL_ENUM_CONVERSIONS (CommandErrorType)
DEFINE_PTSL_ENUM_CONVERSIONS (TrackType)
DEFINE_PTSL_ENUM_CONVERSIONS (TrackFormat)
DEFINE_PTSL_ENUM_CONVERSIONS (TrackTimebase)
DEFINE_PTSL_ENUM_CONVERSIONS (TrackOffsetOptions)
DEFINE_PTSL_ENUM_CONVERSIONS (TimelineUpdateVideo)
DEFINE_PTSL_ENUM_CONVERSIONS (TrackFromClipGroupExclusionReason)
DEFINE_PTSL_ENUM_CONVERSIONS (TrackInsertionPoint)
template<> PTSLC_CPP_EXPORT std::string EnumToString< CommandStatusType > (CommandStatusType value)
template<> PTSLC_CPP_EXPORT std::optional< CommandStatusType > StringToEnum< CommandStatusType > (const std::string &value)
template<> PTSLC_CPP_EXPORT std::string EnumToString< TripleBool > (TripleBool value)
template<> PTSLC_CPP_EXPORT std::optional< TripleBool > StringToEnum< TripleBool > (const std::string &value)
template<typename T >
std::string EnumToString (T value)
template<typename T >
std::optional< T > StringToEnum (const std::string &value)
DECLARE_PTSL_ENUM_CONVERSIONS (CommandId)
DECLARE_PTSL_ENUM_CONVERSIONS (CommandStatusType)
DECLARE_PTSL_ENUM_CONVERSIONS (CommandErrorType)
DECLARE_PTSL_ENUM_CONVERSIONS (TrackType)
DECLARE_PTSL_ENUM_CONVERSIONS (TrackFormat)
DECLARE_PTSL_ENUM_CONVERSIONS (TrackTimebase)
DECLARE_PTSL_ENUM_CONVERSIONS (TimelineUpdateVideo)
DECLARE_PTSL_ENUM_CONVERSIONS (TripleBool)
DECLARE_PTSL_ENUM_CONVERSIONS (TrackOffsetOptions)
DECLARE_PTSL_ENUM_CONVERSIONS (TrackFromClipGroupExclusionReason)
DECLARE_PTSL_ENUM_CONVERSIONS (TrackInsertionPoint)
static void ConvertProtoToCommandError (const ptsl::CommandError &in, CommandError &out)
Variables
static ptsl::EmptyMessage sTmpEmptyMessage = ptsl::EmptyMessage()
const int32_t PING_TIMEOUT = 5000
Typedef Documentation
CommandType
using CommandType = CommandId
Deprecated
Deprecated PTSLC_CPP::CommandType is deprecated starting in Pro Tools 2025.06, use PTSLC_CPP::CommandId instead
CommandStatusType
using CommandStatusType = TaskStatus
Deprecated
Deprecated PTSLC_CPP::CommandStatusType is deprecated starting in Pro Tools 2025.06, use PTSLC_CPP::TaskStatus instead
FileDestination
using FileDestination = EM_FileDestination
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
PM_PlaybackMode
using PM_PlaybackMode = PlaybackMode
Deprecated
Deprecated PM_PlaybackMode is deprecated starting in Pro Tools 2024.10, use PTSLC_CPP::PlaybackMode instead
RM_RecordMode
using RM_RecordMode = RecordMode
Deprecated
Deprecated RM_RecordMode is deprecated starting in Pro Tools 2024.10, use PTSLC_CPP::RecordMode instead
TS_TransportState
using TS_TransportState = TransportState
Deprecated
Deprecated TS_TransportState is deprecated starting in Pro Tools 2024.10, use PTSLC_CPP::TransportState instead
CL_ClipLocation
using CL_ClipLocation = ClipLocation
Deprecated
Deprecated CL_ClipLocation is deprecated starting in Pro Tools 2024.10, use PTSLC_CPP::ClipLocation instead
Enumeration Type Documentation
Mode
enum class Mode : int32_t [strong]
Enumerator
ProTools Locate Pro Tools application server.
Mode_ProTools
Standalone Locate server directly from client.
    Use this if you want to test a client without Pro Tools
Mode_Standalone
SkipHostLaunch
enum class SkipHostLaunch : int32_t [strong]
Enumerator
Yes Skip auto launch.
SHLaunch_Yes
No Do not skip auto launch, try to launch Pro Tools if it is not running already.
SHLaunch_No
CommandId
enum class CommandId : int32_t [strong]
Pro Tools command type.
For documentation of each command, see CppPTSLClient
Enumerator
CId_None
CreateSession
CId_CreateSession
OpenSession
CId_OpenSession
Import
CId_Import
GetTrackList
CId_GetTrackList
SelectAllClipsOnTrack
CId_SelectAllClipsOnTrack
ExtendSelectionToTargetTracks
CId_ExtendSelectionToTargetTracks
TrimToSelection
CId_TrimToSelection
CreateFadesBasedOnPreset
CId_CreateFadesBasedOnPreset
RenameTargetTrack
CId_RenameTargetTrack
ConsolidateClip
CId_ConsolidateClip
ExportClipsAsFiles
CId_ExportClipsAsFiles
ExportSelectedTracksAsAAFOMF
CId_ExportSelectedTracksAsAAFOMF
GetTaskStatus
CId_GetTaskStatus
HostReadyCheck
CId_HostReadyCheck
RefreshTargetAudioFiles
CId_RefreshTargetAudioFiles
RefreshAllModifiedAudioFiles
CId_RefreshAllModifiedAudioFiles
GetFileLocation
CId_GetFileLocation
CloseSession
CId_CloseSession
SaveSession
CId_SaveSession
SaveSessionAs
CId_SaveSessionAs
Cut
CId_Cut
Copy
CId_Copy
Paste
CId_Paste
Clear
CId_Clear
CutSpecial
CId_CutSpecial
CopySpecial
CId_CopySpecial
ClearSpecial
CId_ClearSpecial
PasteSpecial
CId_PasteSpecial
ExportMix
CId_ExportMix
Spot
CId_Spot
ExportSessionInfoAsText
CId_ExportSessionInfoAsText
GetDynamicProperties
CId_GetDynamicProperties
SetPlaybackMode
CId_SetPlaybackMode
SetRecordMode
CId_SetRecordMode
GetSessionAudioFormat
CId_GetSessionAudioFormat
GetSessionSampleRate
CId_GetSessionSampleRate
GetSessionBitDepth
CId_GetSessionBitDepth
GetSessionInterleavedState
CId_GetSessionInterleavedState
GetSessionTimeCodeRate
CId_GetSessionTimeCodeRate
GetSessionFeetFramesRate
CId_GetSessionFeetFramesRate
GetSessionAudioRatePullSettings
CId_GetSessionAudioRatePullSettings
GetSessionVideoRatePullSettings
CId_GetSessionVideoRatePullSettings
GetSessionName
CId_GetSessionName
GetSessionPath
CId_GetSessionPath
GetSessionStartTime
CId_GetSessionStartTime
GetSessionLength
CId_GetSessionLength
SetSessionAudioFormat
CId_SetSessionAudioFormat
SetSessionBitDepth
CId_SetSessionBitDepth
SetSessionInterleavedState
CId_SetSessionInterleavedState
SetSessionTimeCodeRate
CId_SetSessionTimeCodeRate
SetSessionFeetFramesRate
CId_SetSessionFeetFramesRate
SetSessionAudioRatePullSettings
CId_SetSessionAudioRatePullSettings
SetSessionVideoRatePullSettings
CId_SetSessionVideoRatePullSettings
SetSessionStartTime
CId_SetSessionStartTime
SetSessionLength
CId_SetSessionLength
GetPTSLVersion
CId_GetPTSLVersion
GetPlaybackMode
CId_GetPlaybackMode
GetRecordMode
CId_GetRecordMode
GetTransportArmed
CId_GetTransportArmed
GetTransportState
CId_GetTransportState
ClearMemoryLocation
CId_ClearMemoryLocation
RenameSelectedClip
CId_RenameSelectedClip
RenameTargetClip
CId_RenameTargetClip
TogglePlayState
CId_TogglePlayState
ToggleRecordEnable
CId_ToggleRecordEnable
PlayHalfSpeed
CId_PlayHalfSpeed
RecordHalfSpeed
CId_RecordHalfSpeed
EditMemoryLocation
CId_EditMemoryLocation
GetMemoryLocations
CId_GetMemoryLocations
RegisterConnection
CId_RegisterConnection
CreateMemoryLocation
CId_CreateMemoryLocation
CreateNewTracks
CId_CreateNewTracks
SelectTracksByName
CId_SelectTracksByName
GetEditMode
CId_GetEditMode
SetEditMode
CId_SetEditMode
GetEditTool
CId_GetEditTool
SetEditTool
CId_SetEditTool
RecallZoomPreset
CId_RecallZoomPreset
GetEditModeOptions
CId_GetEditModeOptions
SetEditModeOptions
CId_SetEditModeOptions
SetTimelineSelection
CId_SetTimelineSelection
GetTimelineSelection
CId_GetTimelineSelection
ImportVideo
CId_ImportVideo
SelectMemoryLocation
CId_SelectMemoryLocation
SetTrackMuteState
CId_SetTrackMuteState
SetTrackSoloState
CId_SetTrackSoloState
SetTrackSoloSafeState
CId_SetTrackSoloSafeState
SetTrackRecordEnableState
CId_SetTrackRecordEnableState
SetTrackRecordSafeEnableState
CId_SetTrackRecordSafeEnableState
SetTrackInputMonitorState
CId_SetTrackInputMonitorState
SetTrackSmartDspState
CId_SetTrackSmartDspState
SetTrackHiddenState
CId_SetTrackHiddenState
SetTrackInactiveState
CId_SetTrackInactiveState
SetTrackFrozenState
CId_SetTrackFrozenState
SetTrackOnlineState
CId_SetTrackOnlineState
SetTrackOpenState
CId_SetTrackOpenState
GetSessionIDs
CId_GetSessionIDs
GetMemoryLocationsManageMode
CId_GetMemoryLocationsManageMode
SetMemoryLocationsManageMode
CId_SetMemoryLocationsManageMode
SetMainCounterFormat
CId_SetMainCounterFormat
SetSubCounterFormat
CId_SetSubCounterFormat
GetMainCounterFormat
CId_GetMainCounterFormat
GetSubCounterFormat
CId_GetSubCounterFormat
Undo
CId_Undo
Redo
CId_Redo
UndoAll
CId_UndoAll
RedoAll
CId_RedoAll
ClearUndoQueue
CId_ClearUndoQueue
SetTrackDSPModeSafeState
CId_SetTrackDSPModeSafeState
GetSessionSystemDelayInfo
CId_GetSessionSystemDelayInfo
GroupClips
CId_GroupClips
UngroupClips
CId_UngroupClips
UngroupAllClips
CId_UngroupAllClips
RegroupClips
CId_RegroupClips
RepeatSelection
CId_RepeatSelection
DuplicateSelection
CId_DuplicateSelection
ClearAllMemoryLocations
CId_ClearAllMemoryLocations
CId_GetTimeAsType
CId_SubtractLocations
CId_AddLengthToLocation
CId_SubtractPositions
CId_AddLengthToPositions
CId_ImportAudioToClipList
CId_SpotClipsByID
CId_GetClipList
CId_GetMediaFileInfo
CId_CreateAudioClips
CId_GetExportMixSourceList
CId_CreateBatchJob
CId_GetMonitorOutputPath
CId_GetEditSelection
CId_SubscribeToEvents
CId_GetBatchJobStatus
CId_BounceTrack
CId_PollEvents
CId_UnsubscribeFromEvents
CId_CompleteBatchJob
CId_CancelBatchJob
CId_BeginScrub
CId_EndScrub
CId_ContinueScrub
CId_EnableCueProVideoPlugIn
CId_UpdateVideo
CId_EnableAPI
CId_ExchangePublicKeys
CId_CreateSignalPath
CId_SetTrackMainOutputAssignments
CId_GetTrackControlInfo
CId_GetTrackControlValue
CId_SetTrackControlValue
CId_InstallMenuHandler
CId_UninstallMenuHandler
CId_SetTrackColor
CId_GetTrackPlaylists
CId_SetTrackTimebase
CId_GetColorPalette
CId_DeleteTracks
CId_GetPlaylistElements
CId_WriteSelectedTranscriptionToJSONFile
TaskStatus
enum class TaskStatus : int32_t [strong]
Status of execution of the Pro Tools task.
Enumerator
NoResponseReceived
TStatus_NoResponseReceived
Queued
TStatus_Queued
Pending
TStatus_Pending
InProgress
TStatus_InProgress
Completed
TStatus_Completed
Failed
TStatus_Failed
WaitingForUserInput
TStatus_WaitingForUserInput
CompletedWithBadResponse
TStatus_CompletedWithBadResponse
FailedWithBadErrorResponse
TStatus_FailedWithBadErrorResponse
CommandErrorType
enum class CommandErrorType : int32_t [strong]
Type of the error message which can be returned to user.
It can be OS error or Pro Tools error.
Enumerator
CEType_None
OS_WritePermissions
CEType_OS_WritePermissions command hits write permissions
OS_ErrorCode
CEType_OS_ErrorCode other OS error
OS_NoLocationFound
CEType_OS_NoLocationFound the specified location does not exist
OS_NoSessionFound
CEType_OS_NoSessionFound the specified session does not exist
OS_FilePathLocation
OS_ReadError
CEType_OS_ReadError command hits read permissions or can not read specified file
OS_DiskSpace
CEType_OS_DiskSpace not enough free space on disk
OS_DuplicateName
CEType_OS_DuplicateName the session name to be created is a duplicate of some existing
OS_IllegalCharacters
CEType_OS_IllegalCharacters the session name contains illegal characters/symbols
OS_CharactersLimit
CEType_OS_CharactersLimit the session/track name is too long (250 characters allowed)
OS_ProToolsIsNotAvailable
CEType_OS_ProToolsIsNotAvailable Pro Tools is not responding during a specified timeout.
OS_NoFilePathFound
CEType_OS_NoFilePathFound the specified file path could not be found
PT_UnknownError
CEType_PT_UnknownError an unspecified error occurred during execution of a command
PT_NoTemplateGroup
CEType_PT_NoTemplateGroup template group does not exist
PT_NoTemplate
CEType_PT_NoTemplate template name does not exist
PT_SampleRateMismatch
CEType_PT_SampleRateMismatch cannot copy/link source media because SRC is on and sample rates don't match
PT_NoVideoTrackFound
CEType_PT_NoVideoTrackFound cannot copy/link source media because no video track found in the session
PT_NoTracksFound
CEType_PT_NoTracksFound warning. no tracks matched because no tracks exist in source
PT_NoOpenedSession
CEType_PT_NoOpenedSession session is not open
PT_NoTrackFound
CEType_PT_NoTrackFound specified track(s) not found
PT_NoClipsFound
CEType_PT_NoClipsFound specified track contains no clips
PT_NoSelection
CEType_PT_NoSelection no selection was found
PT_RecordDrive
CEType_PT_RecordDrive the volume is not designated as a record drive
PT_NoPresetFound
CEType_PT_NoPresetFound preset does not exist in the specified location
PT_FileTypeMXF
CEType_PT_FileTypeMXF MXF is only available when 'Enforce Media Composer compatibility' is on.
PT_CopyOptionCopy
CEType_PT_CopyOptionCopy copy option are unavailable if 'Quantize Edits to Frame Boundaries' is checked
PT_CopyOptionLink
CEType_PT_CopyOptionLink link option are unavailable if 'Quantize Edits to Frame Boundaries' is checked
PT_QuantizeEdits
CEType_PT_QuantizeEdits 'Quantize Edits to Frame Boundaries' can't be false if 'Enforce Media Composer compatibility' is true
PT_ExportAsMultichannel
CEType_PT_ExportAsMultichannel warning. 'Export Stereo, 5.1 and 7.1 Tracks as Multichannel' is not applicable because no tracks of that format are contained within the export selection
PT_IllegalCharactersComments
CEType_PT_IllegalCharactersComments comments contain illegal characters
PT_IllegalCharactersSequenceName
CEType_PT_IllegalCharactersSequenceName sequence name contains illegal characters
PT_MaxCharactersComments
CEType_PT_MaxCharactersComments comments exceed the maximum character limit
PT_MaxCharactersSequenceName
CEType_PT_MaxCharactersSequenceName sequence name exceeds the maximum character limit
PT_NoSequenceName
CEType_PT_NoSequenceName sequence name can't be empty
PT_InvalidTask
CEType_PT_InvalidTask the specified task does not exist
PT_FileNotFound
CEType_PT_FileNotFound specified files were not found
PT_InvalidSelection
CEType_PT_InvalidSelection unable to perform action because of invalid selection
PT_ReadOnlySession
CEType_PT_ReadOnlySession the session is located on a read-only drive and cannot be saved without user intervention
PT_InvalidParameter
CEType_PT_InvalidParameter One or more parameters are invalid.
PT_Forbidden
CEType_PT_Forbidden operation is not allowed
PT_NoTimelineFound
CEType_PT_NoTimelineFound no timeline was found
PT_ArgumentOutOfRange
CEType_PT_ArgumentOutOfRange argument is out of range
PT_ForbiddenTrackType
CEType_PT_ForbiddenTrackType operation is not allowed for the specified track type
PT_NoVideoEngineFound
CEType_PT_NoVideoEngineFound video engine is not installed or unavailable
PT_NoDspHardwareFound
CEType_PT_NoDspHardwareFound DSP hardware is not connected or unavailable.
PT_UnsupportedCommand
CEType_PT_UnsupportedCommand requested command is not supported
PT_HostNotReady
CEType_PT_HostNotReady Pro Tools is not fully ready to execute all PTSL commands.
PT_CannotBeDone
CEType_PT_CannotBeDone Operation cannot be done because of some restrictions, limitations or other reasons.
PT_ResponseLengthExceeded
CEType_PT_ResponseLengthExceeded Result message larger than maximum possible gRPC message size.
PT_CommandTimeout
CEType_PT_CommandTimeout
PT_HostIsBusy
CEType_PT_HostIsBusy
CEType_PT_DeprecatedParameter
CEType_PT_DeprecatedParameterValue
CEType_PT_GlobalRendererRequired
PT_Info
CEType_PT_Info not an error or warning, just some information about command execution
SDK_Error
CEType_SDK_Error Default SDK error used only in Client Wrapper to indicate unknown RPC/Transport issues.
SDK_VersionMismatch
CEType_SDK_VersionMismatch Versions of PTSL Host and PTSL Client are mismatched.
SDK_NotImplemented
CEType_SDK_NotImplemented Some PTSL functional is not implemented at the PT side.
SDK_SessionIdParseError
CEType_SDK_SessionIdParseError Unable to parse the session id from the RegisterConnection response.
SDK_GrpcGeneric
CEType_SDK_GrpcGeneric Generic gRPC error.
FileType
enum class FileType : int32_t [strong]
Type of Pro Tools file.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
FType_Unknown
WAVE
Deprecated
Deprecated PTSLC_CPP::FileType::WAVE is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::FileType::FType_WAVE
FType_WAVE
AIFF
Deprecated
Deprecated PTSLC_CPP::FileType::AIFF is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::FileType::FType_AIFF
FType_AIFF
AAF
Deprecated
Deprecated PTSLC_CPP::FileType::AAF is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::FileType::FType_AAF
FType_AAF
OMF
Deprecated
Deprecated PTSLC_CPP::FileType::OMF is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::FileType::FType_OMF
FType_OMF
SampleRate
enum class SampleRate : int32_t [strong]
Type of Pro Tools session/project sample rate.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
SRate_Unknown
SR_None
Deprecated
Deprecated PTSLC_CPP::SampleRate::SR_None is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SampleRate::SRate_None
SRate_None
SR_44100
Deprecated
Deprecated PTSLC_CPP::SampleRate::SR_44100 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SampleRate::SRate_44100
SRate_44100
SR_48000
Deprecated
Deprecated PTSLC_CPP::SampleRate::SR_48000 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SampleRate::SRate_48000
SRate_48000
SR_88200
Deprecated
Deprecated PTSLC_CPP::SampleRate::SR_88200 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SampleRate::SRate_88200
SRate_88200
SR_96000
Deprecated
Deprecated PTSLC_CPP::SampleRate::SR_96000 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SampleRate::SRate_96000
SRate_96000
SR_176400
Deprecated
Deprecated PTSLC_CPP::SampleRate::SR_176400 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SampleRate::SRate_176400
SRate_176400
SR_192000
Deprecated
Deprecated PTSLC_CPP::SampleRate::SR_192000 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SampleRate::SRate_192000
SRate_192000
IOSettings
enum class IOSettings : int32_t [strong]
Type of Pro Tools input/output settings.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
IOSettings_Unknown
IO_None
Deprecated
Deprecated PTSLC_CPP::IOSettings::IO_None is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::IOSettings::IOSettings_None
IOSettings_None
IO_Last
Deprecated
Deprecated PTSLC_CPP::IOSettings::IO_Last is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::IOSettings::IOSettings_Last
IOSettings_Last
IO_StereoMix
Deprecated
Deprecated PTSLC_CPP::IOSettings::IO_StereoMix is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::IOSettings::IOSettings_StereoMix
IOSettings_StereoMix
IO_51FilmMix
Deprecated
Deprecated PTSLC_CPP::IOSettings::IO_51FilmMix is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::IOSettings::IOSettings_51FilmMix
IOSettings_51FilmMix
IO_51SMPTEMix
Deprecated
Deprecated PTSLC_CPP::IOSettings::IO_51SMPTEMix is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::IOSettings::IOSettings_51SMPTEMix
IOSettings_51SMPTEMix
IO_51DTSMix
Deprecated
Deprecated PTSLC_CPP::IOSettings::IO_51DTSMix is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::IOSettings::IOSettings_51DTSMix
IOSettings_51DTSMix
IO_UserDefined
Deprecated
Deprecated PTSLC_CPP::IOSettings::IO_UserDefined is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::IOSettings::IOSettings_UserDefined
IOSettings_UserDefined
BitDepth
enum class BitDepth : int32_t [strong]
Available bit depth for file.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
BDepth_Unknown
None
Deprecated
Deprecated PTSLC_CPP::BitDepth::None is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::BitDepth::BDepth_None
BDepth_None
Bit16
Deprecated
Deprecated PTSLC_CPP::BitDepth::Bit16 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::BitDepth::BDepth_16
BDepth_16
Bit24
Deprecated
Deprecated PTSLC_CPP::BitDepth::Bit24 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::BitDepth::BDepth_24
BDepth_24
Bit32Float
Deprecated
Deprecated PTSLC_CPP::BitDepth::Bit32Float is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::BitDepth::BDepth_32Float
BDepth_32Float
ImportType
enum class ImportType : int32_t [strong]
Types of data which can be imported into Pro Tools.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
IType_Unknown
Session
Deprecated
Deprecated PTSLC_CPP::ImportType::Session is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::ImportType::IType_Session
IType_Session
Audio
Deprecated
Deprecated PTSLC_CPP::ImportType::Audio is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::ImportType::IType_Audio
IType_Audio
AudioMediaOptions
enum class AudioMediaOptions : int32_t [strong]
Audio import options.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
AMOptions_Unknown
LinkToSource
Deprecated
Deprecated PTSLC_CPP::AudioMediaOptions::LinkToSource is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::AudioMediaOptions::AMOptions_LinkToSource
AMOptions_LinkToSource
CopyFromSource
Deprecated
Deprecated PTSLC_CPP::AudioMediaOptions::CopyFromSource is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::AudioMediaOptions::AMOptions_CopyFromSource
AMOptions_CopyFromSource
ConsolidateFromSource
Deprecated
Deprecated PTSLC_CPP::AudioMediaOptions::ConsolidateFromSource is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::AudioMediaOptions::AMOptions_ConsolidateFromSource
AMOptions_ConsolidateFromSource
ForceToTargetSessionFormat
Deprecated
Deprecated PTSLC_CPP::AudioMediaOptions::ForceToTargetSessionFormat is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::AudioMediaOptions::AMOptions_ForceToTargetSessionFormat
AMOptions_ForceToTargetSessionFormat
VideoMediaOptions
enum class VideoMediaOptions : int32_t [strong]
Video import options.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
VMOptions_Unknown
LinkToSource
Deprecated
Deprecated PTSLC_CPP::VideoMediaOptions::LinkToSource is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::VideoMediaOptions::VMOptions_LinkToSourceVideo
VMOptions_LinkToSourceVideo
CopyFromSource
Deprecated
Deprecated PTSLC_CPP::VideoMediaOptions::CopyFromSource is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::VideoMediaOptions::VMOptions_CopyFromSourceVideo
VMOptions_CopyFromSourceVideo
MatchTrackOptions
enum class MatchTrackOptions : int32_t [strong]
Options for matching tracks during import.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
MTOptions_Unknown
None
Deprecated
Deprecated PTSLC_CPP::MatchTrackOptions::None is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::MatchTrackOptions::MTOptions_None
MTOptions_None
MatchTracks
Deprecated
Deprecated PTSLC_CPP::MatchTrackOptions::MatchTracks is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::MatchTrackOptions::MTOptions_MatchTracks
MTOptions_MatchTracks
ImportAsNewTrack
Deprecated
Deprecated PTSLC_CPP::MatchTrackOptions::ImportAsNewTrack is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::MatchTrackOptions::MTOptions_ImportAsNewTrack
MTOptions_ImportAsNewTrack
MainPlaylistOptions
enum class MainPlaylistOptions : int32_t [strong]
Options for playlists import.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
MPOptions_Unknown
ImportReplaceExistingPlaylists
Deprecated
Deprecated PTSLC_CPP::MainPlaylistOptions::ImportReplaceExistingPlaylists is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::MainPlaylistOptions::MPOptions_ImportReplaceExistingPlaylists
MPOptions_ImportReplaceExistingPlaylists
ImportOverlayNewOnExistingPlaylists
Deprecated
Deprecated PTSLC_CPP::MainPlaylistOptions::ImportOverlayNewOnExistingPlaylists is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::MainPlaylistOptions::MPOptions_ImportOverlayNewOnExistingPlaylists
MPOptions_ImportOverlayNewOnExistingPlaylists
DoNotImport
Deprecated
Deprecated PTSLC_CPP::MainPlaylistOptions::DoNotImport is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::MainPlaylistOptions::MPOptions_DoNotImport
MPOptions_DoNotImport
AudioOperations
enum class AudioOperations : int32_t [strong]
Operations for audio import.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
AOperations_Unknown
AddAudio
Deprecated
Deprecated PTSLC_CPP::AudioOperations::AddAudio is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::AudioOperations::AOperations_AddAudio
AOperations_AddAudio
CopyAudio
Deprecated
Deprecated PTSLC_CPP::AudioOperations::CopyAudio is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::AudioOperations::AOperations_CopyAudio
AOperations_CopyAudio
ConvertAudio
Deprecated
Deprecated PTSLC_CPP::AudioOperations::ConvertAudio is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::AudioOperations::AOperations_ConvertAudio
AOperations_ConvertAudio
Default
Deprecated
Deprecated PTSLC_CPP::AudioOperations::Default is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::AudioOperations::AOperations_Default
AOperations_Default
MediaDestination
enum class MediaDestination : int32_t [strong]
Types of destination.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
MDestination_Unknown
None
Deprecated
Deprecated PTSLC_CPP::MediaDestination::None is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::MediaDestination::MDestination_None
MDestination_None
MainVideoTrack
Deprecated
Deprecated PTSLC_CPP::MediaDestination::MainVideoTrack is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::MediaDestination::MDestination_MainVideoTrack
MDestination_MainVideoTrack
NewTrack
Deprecated
Deprecated PTSLC_CPP::MediaDestination::NewTrack is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::MediaDestination::MDestination_NewTrack
MDestination_NewTrack
ClipList
Deprecated
Deprecated PTSLC_CPP::MediaDestination::ClipList is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::MediaDestination::MDestination_ClipList
MDestination_ClipList
MediaLocation
enum class MediaLocation : int32_t [strong]
Types of location in the session.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
MLocation_Unknown
None
Deprecated
Deprecated PTSLC_CPP::MediaLocation::None is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::MediaLocation::MLocation_None
MLocation_None
SessionStart
Deprecated
Deprecated PTSLC_CPP::MediaLocation::SessionStart is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::MediaLocation::MLocation_SessionStart
MLocation_SessionStart
SongStart
Deprecated
Deprecated PTSLC_CPP::MediaLocation::SongStart is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::MediaLocation::MLocation_SongStart
MLocation_SongStart
Selection
Deprecated
Deprecated PTSLC_CPP::MediaLocation::Selection is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::MediaLocation::MLocation_Selection
MLocation_Selection
Spot
Deprecated
Deprecated PTSLC_CPP::MediaLocation::Spot is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::MediaLocation::MLocation_Spot
MLocation_Spot
TrackType
enum class TrackType : int32_t [strong]
Type of Pro Tools track.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
TType_Unknown
TT_Unknown
Unknown
TType_Midi
TT_Midi
Midi
TType_Audio
TT_Audio
AudioTrack
TType_Aux
TT_Aux
Aux
TType_Video
TT_Video
VideoTrack
TType_Vca
TT_Vca
Vca
TType_Tempo This track type is included for informational purposes only and has limited functionality in the SDK.
TT_Tempo
Tempo
TType_Markers This track type is included for informational purposes only and has limited functionality in the SDK.
TT_Markers
Markers
TType_Meter This track type is included for informational purposes only and has limited functionality in the SDK.
TT_Meter
Meter
TType_KeySignature This track type is included for informational purposes only and has limited functionality in the SDK.
TT_KeySignature
KeySignature
TType_ChordSymbols This track type is included for informational purposes only and has limited functionality in the SDK.
TT_ChordSymbols
ChordSymbols
TType_Instrument
TT_Instrument
Instrument
TType_Master
TT_Master
Master
TType_Heat This track type is included for informational purposes only and has limited functionality in the SDK.
TT_Heat
Heat
TType_BasicFolder
TT_BasicFolder
BasicFolder
TType_RoutingFolder
TT_RoutingFolder
RoutingFolder
TType_CompLane
TT_CompLane
CompLane
TrackFormat
enum class TrackFormat : int32_t [strong]
Format of Pro Tools track.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
TF_Unknown
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_Unknown is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_Unknown
TFormat_Unknown
TF_Mono
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_Mono is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_Mono
TFormat_Mono
TF_Stereo
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_Stereo is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_Stereo
TFormat_Stereo
TF_LCR
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_LCR is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_LCR
TFormat_LCR
TF_LCRS
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_LCRS is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_LCRS
TFormat_LCRS
TF_Quad
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_Quad is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_Quad
TFormat_Quad
TF_5_0
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_5_0 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_5_0
TFormat_5_0
TF_5_1
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_5_1 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_5_1
TFormat_5_1
TF_5_0_2
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_5_0_2 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_5_0_2
TFormat_5_0_2
TF_5_1_2
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_5_1_2 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_5_1_2
TFormat_5_1_2
TF_5_0_4
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_5_0_4 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_5_0_4
TFormat_5_0_4
TF_5_1_4
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_5_1_4 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_5_1_4
TFormat_5_1_4
TF_6_0
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_6_0 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_6_0
TFormat_6_0
TF_6_1
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_6_1 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_6_1
TFormat_6_1
TF_7_0
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_7_0 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_7_0
TFormat_7_0
TF_7_1
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_7_1 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_7_1
TFormat_7_1
TF_7_0_SDDS
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_7_0_SDDS is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_7_0_SDDS
TFormat_7_0_SDDS
TF_7_1_SDDS
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_7_1_SDDS is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_7_1_SDDS
TFormat_7_1_SDDS
TF_7_0_2
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_7_0_2 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_7_0_2
TFormat_7_0_2
TF_7_1_2
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_7_1_2 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_7_1_2
TFormat_7_1_2
TF_7_0_4
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_7_0_4 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_7_0_4
TFormat_7_0_4
TF_7_1_4
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_7_1_4 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_7_1_4
TFormat_7_1_4
TF_7_0_6
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_7_0_6 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_7_0_6
TFormat_7_0_6
TF_7_1_6
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_7_1_6 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_7_1_6
TFormat_7_1_6
TF_9_0_4
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_9_0_4 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_9_0_4
TFormat_9_0_4
TF_9_1_4
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_9_1_4 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_9_1_4
TFormat_9_1_4
TF_9_0_6
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_9_0_6 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_9_0_6
TFormat_9_0_6
TF_9_1_6
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_9_1_6 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_9_1_6
TFormat_9_1_6
TF_1stOrderAmbisonics
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_1stOrderAmbisonics is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_1stOrderAmbisonics
TFormat_1stOrderAmbisonics
TF_2ndOrderAmbisonics
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_2ndOrderAmbisonics is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_2ndOrderAmbisonics
TFormat_2ndOrderAmbisonics
TF_3rdOrderAmbisonics
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_3rdOrderAmbisonics is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_3rdOrderAmbisonics
TFormat_3rdOrderAmbisonics
TF_4thOrderAmbisonics
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_4thOrderAmbisonics is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_4thOrderAmbisonics
TFormat_4thOrderAmbisonics
TF_5thOrderAmbisonics
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_5thOrderAmbisonics is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_5thOrderAmbisonics
TFormat_5thOrderAmbisonics
TF_6thOrderAmbisonics
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_6thOrderAmbisonics is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_6thOrderAmbisonics
TFormat_6thOrderAmbisonics
TF_7thOrderAmbisonics
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_7thOrderAmbisonics is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_7thOrderAmbisonics
TFormat_7thOrderAmbisonics
TF_None
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_None is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_None
TFormat_None
TF_2_1
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_2_1 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_2_1
TFormat_2_1
TF_Overhead
Deprecated
Deprecated PTSLC_CPP::TrackFormat::TF_Overhead is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackFormat::TFormat_Overhead
TFormat_Overhead
TrackTimebase
enum class TrackTimebase : int32_t [strong]
Timebase of Pro Tools track.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
TTB_Unknown
Deprecated
Deprecated PTSLC_CPP::TrackTimebase::TTB_Unknown is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackTimebase::TTimebase_Unknown
TTimebase_Unknown
TTB_Samples
Deprecated
Deprecated PTSLC_CPP::TrackTimebase::TTB_Samples is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackTimebase::TTimebase_Samples
TTimebase_Samples
TTB_Ticks
Deprecated
Deprecated PTSLC_CPP::TrackTimebase::TTB_Ticks is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackTimebase::TTimebase_Ticks
TTimebase_Ticks
TTB_None
Deprecated
Deprecated PTSLC_CPP::TrackTimebase::TTB_None is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackTimebase::TTimebase_None
TTimebase_None
TimeCodeMappingOptions
enum class TimeCodeMappingOptions : int32_t [strong]
Options for time code mapping.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
TCMOptions_Unknown
MaintainAbsoluteTimeCodeValues
Deprecated
Deprecated PTSLC_CPP::TimeCodeMappingOptions::MaintainAbsoluteTimeCodeValues is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TimeCodeMappingOptions::TCMOptions_MaintainAbsoluteTimeCodeValues
TCMOptions_MaintainAbsoluteTimeCodeValues
MaintainRelativeTimeCodeValues
Deprecated
Deprecated PTSLC_CPP::TimeCodeMappingOptions::MaintainRelativeTimeCodeValues is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TimeCodeMappingOptions::TCMOptions_MaintainRelativeTimeCodeValues
TCMOptions_MaintainRelativeTimeCodeValues
MapStartTimeCodeTo
Deprecated
Deprecated PTSLC_CPP::TimeCodeMappingOptions::MapStartTimeCodeTo is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TimeCodeMappingOptions::TCMOptions_MapStartTimeCodeTo
TCMOptions_MapStartTimeCodeTo
TrackOffsetOptions
enum class TrackOffsetOptions : int32_t [strong]
Enumerator
TOOptions_Unknown
BarsBeats
Deprecated
Deprecated PTSLC_CPP::TrackOffsetOptions::BarsBeats is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackOffsetOptions::TOOptions_BarsBeats
TOOptions_BarsBeats
MinSecs
Deprecated
Deprecated PTSLC_CPP::TrackOffsetOptions::MinSecs is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackOffsetOptions::TOOptions_MinSecs
TOOptions_MinSecs
TimeCode
Deprecated
Deprecated PTSLC_CPP::TrackOffsetOptions::TimeCode is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackOffsetOptions::TOOptions_TimeCode
TOOptions_TimeCode
FeetFrames
Deprecated
Deprecated PTSLC_CPP::TrackOffsetOptions::FeetFrames is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackOffsetOptions::TOOptions_FeetFrames
TOOptions_FeetFrames
Samples
Deprecated
Deprecated PTSLC_CPP::TrackOffsetOptions::Samples is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackOffsetOptions::TOOptions_Samples
TOOptions_Samples
SpotLocationType
enum class SpotLocationType : int32_t [strong]
The types of location for Spot Mode.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
SLType_Unknown
Start
Deprecated
Deprecated PTSLC_CPP::SpotLocationType::Start is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SpotLocationType::SLType_Start
SLType_Start
SyncPoint
Deprecated
Deprecated PTSLC_CPP::SpotLocationType::SyncPoint is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SpotLocationType::SLType_SyncPoint
SLType_SyncPoint
End
Deprecated
Deprecated PTSLC_CPP::SpotLocationType::End is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SpotLocationType::SLType_End
SLType_End
TimelineLocationType
enum class TimelineLocationType [strong]
Types for global timeline times.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
TLType_Unknown
TLType_Samples
TLType_Ticks
TLType_Frames
TLType_MinSecs
TLType_TimeCode
TLType_BarsBeats
TLType_FeetFrames
TLType_Seconds
TrackAttributeState
enum class TrackAttributeState : int32_t [strong]
Type of the state and the way a track attribute is set.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
TAState_Unknown
None
Deprecated
Deprecated PTSLC_CPP::TrackAttributeState::None is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackAttributeState::TAState_None
TAState_None
SetExplicitly
Deprecated
Deprecated PTSLC_CPP::TrackAttributeState::SetExplicitly is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackAttributeState::TAState_SetExplicitly
TAState_SetExplicitly
SetImplicitly
Deprecated
Deprecated PTSLC_CPP::TrackAttributeState::SetImplicitly is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackAttributeState::TAState_SetImplicitly
TAState_SetImplicitly
SetExplicitlyAndImplicitly
Deprecated
Deprecated PTSLC_CPP::TrackAttributeState::SetExplicitlyAndImplicitly is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackAttributeState::TAState_SetExplicitlyAndImplicitly
TAState_SetExplicitlyAndImplicitly
TrackListFilter
enum class TrackListFilter : int32_t [strong]
Types of track list filters.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
TLFilter_Unknown
All
Deprecated
Deprecated PTSLC_CPP::TrackListFilter::All is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackListFilter::TLFilter_All
TLFilter_All
Selected
Deprecated
Deprecated PTSLC_CPP::TrackListFilter::Selected is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackListFilter::TLFilter_Selected
TLFilter_Selected
SelectedExplicitly
Deprecated
Deprecated PTSLC_CPP::TrackListFilter::SelectedExplicitly is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackListFilter::TLFilter_SelectedExplicitly
TLFilter_SelectedExplicitly
SelectedImplicitly
Deprecated
Deprecated PTSLC_CPP::TrackListFilter::SelectedImplicitly is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackListFilter::TLFilter_SelectedImplicitly
TLFilter_SelectedImplicitly
WithClipsOnMainPlaylist
Deprecated
Deprecated PTSLC_CPP::TrackListFilter::WithClipsOnMainPlaylist is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackListFilter::TLFilter_WithClipsOnMainPlaylist
TLFilter_WithClipsOnMainPlaylist
WithAutomationOnMainPlaylist
Deprecated
Deprecated PTSLC_CPP::TrackListFilter::WithAutomationOnMainPlaylist is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackListFilter::TLFilter_WithAutomationOnMainPlaylist
TLFilter_WithAutomationOnMainPlaylist
Inactive
Deprecated
Deprecated PTSLC_CPP::TrackListFilter::Inactive is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackListFilter::TLFilter_Inactive
TLFilter_Inactive
InactiveExplicitly
Deprecated
Deprecated PTSLC_CPP::TrackListFilter::InactiveExplicitly is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackListFilter::TLFilter_InactiveExplicitly
TLFilter_InactiveExplicitly
InactiveImplicitly
Deprecated
Deprecated PTSLC_CPP::TrackListFilter::InactiveImplicitly is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackListFilter::TLFilter_InactiveImplicitly
TLFilter_InactiveImplicitly
Hidden
Deprecated
Deprecated PTSLC_CPP::TrackListFilter::Hidden is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackListFilter::TLFilter_Hidden
TLFilter_Hidden
HiddenExplicitly
Deprecated
Deprecated PTSLC_CPP::TrackListFilter::HiddenExplicitly is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackListFilter::TLFilter_HiddenExplicitly
TLFilter_HiddenExplicitly
HiddenImplicitly
Deprecated
Deprecated PTSLC_CPP::TrackListFilter::HiddenImplicitly is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackListFilter::TLFilter_HiddenImplicitly
TLFilter_HiddenImplicitly
Locked
Deprecated
Deprecated PTSLC_CPP::TrackListFilter::Locked is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackListFilter::TLFilter_Locked
TLFilter_Locked
Muted
Deprecated
Deprecated PTSLC_CPP::TrackListFilter::Muted is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackListFilter::TLFilter_Muted
TLFilter_Muted
Frozen
Deprecated
Deprecated PTSLC_CPP::TrackListFilter::Frozen is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackListFilter::TLFilter_Frozen
TLFilter_Frozen
Open
Deprecated
Deprecated PTSLC_CPP::TrackListFilter::Open is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackListFilter::TLFilter_Open
TLFilter_Open
Online
Deprecated
Deprecated PTSLC_CPP::TrackListFilter::Online is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackListFilter::TLFilter_Online
TLFilter_Online
ExportFormat
enum class ExportFormat : int32_t [strong]
Exported clips format.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
EFormat_Unknown
None
Deprecated
Deprecated PTSLC_CPP::ExportFormat::None is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::ExportFormat::EFormat_None
EFormat_None
Mono
Deprecated
Deprecated PTSLC_CPP::ExportFormat::Mono is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::ExportFormat::EFormat_Mono
EFormat_Mono
MultipleMono
Deprecated
Deprecated PTSLC_CPP::ExportFormat::MultipleMono is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::ExportFormat::EFormat_MultipleMono
EFormat_MultipleMono
Interleaved
Deprecated
Deprecated PTSLC_CPP::ExportFormat::Interleaved is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::ExportFormat::EFormat_Interleaved
EFormat_Interleaved
ExportFileType
enum class ExportFileType : int32_t [strong]
The types of files which the clips will be exported to.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
EFType_Unknown
WAV
Deprecated
Deprecated PTSLC_CPP::ExportFileType::WAV is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::ExportFileType::EFType_WAV
EFType_WAV
AIFF
Deprecated
Deprecated PTSLC_CPP::ExportFileType::AIFF is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::ExportFileType::EFType_AIFF
EFType_AIFF
MXF
Deprecated
Deprecated PTSLC_CPP::ExportFileType::MXF is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::ExportFileType::EFType_MXF
EFType_MXF
ResolveDuplicateNamesBy
enum class ResolveDuplicateNamesBy : int32_t [strong]
Types of possible duplicate names resolution.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
RDNBy_Unknown
AutoRenaming
Deprecated
Deprecated PTSLC_CPP::ResolveDuplicateNamesBy::AutoRenaming is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::ResolveDuplicateNamesBy::RDNBy_AutoRenaming
RDNBy_AutoRenaming
ReplacingWithNewFiles
Deprecated
Deprecated PTSLC_CPP::ResolveDuplicateNamesBy::ReplacingWithNewFiles is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::ResolveDuplicateNamesBy::RDNBy_ReplacingWithNewFiles
RDNBy_ReplacingWithNewFiles
ExportAsAAFFileType
enum class ExportAsAAFFileType : int32_t [strong]
The types of files which the tracks will be exported to as AAF/OMF.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
EAAFFType_Unknown
EAAFFType_None
WAV
Deprecated
Deprecated PTSLC_CPP::ExportAsAAFFileType::WAV is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::ExportAsAAFFileType::EAAFFType_WAV
EAAFFType_WAV
AIFF
Deprecated
Deprecated PTSLC_CPP::ExportAsAAFFileType::AIFF is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::ExportAsAAFFileType::EAAFFType_AIFF
EAAFFType_AIFF
MXF
Deprecated
Deprecated PTSLC_CPP::ExportAsAAFFileType::MXF is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::ExportAsAAFFileType::EAAFFType_MXF
EAAFFType_MXF
Embedded
Deprecated
Deprecated PTSLC_CPP::ExportAsAAFFileType::Embedded is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::ExportAsAAFFileType::EAAFFType_Embedded
EAAFFType_Embedded
AAFFileBitDepth
enum class AAFFileBitDepth : int32_t [strong]
Available bit depth for file exported as AAF/OMF.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
AAFFBDepth_Unknown
AAFFBDepth_None
Bit16
Deprecated
Deprecated PTSLC_CPP::AAFFileBitDepth::Bit16 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::AAFFileBitDepth::AAFFBDepth_Bit16
AAFFBDepth_Bit16
Bit24
Deprecated
Deprecated PTSLC_CPP::AAFFileBitDepth::Bit24 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::AAFFileBitDepth::AAFFBDepth_Bit24
AAFFBDepth_Bit24
CopyOption
enum class CopyOption : int32_t [strong]
Available options for copying media while exporting tracks as AAF/OMF files.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
COption_Unknown
ConsolidateFromSourceMedia
Deprecated
Deprecated PTSLC_CPP::CopyOption::ConsolidateFromSourceMedia is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::CopyOption::COption_ConsolidateFromSourceMedia
COption_ConsolidateFromSourceMedia
CopyFromSourceMedia
Deprecated
Deprecated PTSLC_CPP::CopyOption::CopyFromSourceMedia is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::CopyOption::COption_CopyFromSourceMedia
COption_CopyFromSourceMedia
LinkFromSourceMedia
Deprecated
Deprecated PTSLC_CPP::CopyOption::LinkFromSourceMedia is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::CopyOption::COption_LinkFromSourceMedia
COption_LinkFromSourceMedia
FileLocationTypeFilter
enum class FileLocationTypeFilter : int32_t [strong]
Types of the filters which can be applied for session file gathering.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
FLTFilter_Unknown
All_Files
Deprecated
Deprecated PTSLC_CPP::FileLocationTypeFilter::All_Files is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::FileLocationTypeFilter::FLTFilter_AllFiles
FLTFilter_AllFiles
OnTimeline_Files
Deprecated
Deprecated PTSLC_CPP::FileLocationTypeFilter::OnTimeline_Files is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::FileLocationTypeFilter::FLTFilter_OnTimelineFiles
FLTFilter_OnTimelineFiles
NotOnTimeline_Files
Deprecated
Deprecated PTSLC_CPP::FileLocationTypeFilter::NotOnTimeline_Files is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::FileLocationTypeFilter::FLTFilter_NotOnTimelineFiles
FLTFilter_NotOnTimelineFiles
Online_Files
Deprecated
Deprecated PTSLC_CPP::FileLocationTypeFilter::Online_Files is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::FileLocationTypeFilter::FLTFilter_OnlineFiles
FLTFilter_OnlineFiles
Offline_Files
Deprecated
Deprecated PTSLC_CPP::FileLocationTypeFilter::Offline_Files is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::FileLocationTypeFilter::FLTFilter_OfflineFiles
FLTFilter_OfflineFiles
Audio_Files
Deprecated
Deprecated PTSLC_CPP::FileLocationTypeFilter::Audio_Files is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::FileLocationTypeFilter::FLTFilter_AudioFiles
FLTFilter_AudioFiles
Video_Files
Deprecated
Deprecated PTSLC_CPP::FileLocationTypeFilter::Video_Files is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::FileLocationTypeFilter::FLTFilter_VideoFiles
FLTFilter_VideoFiles
Rendered_Files
Deprecated
Deprecated PTSLC_CPP::FileLocationTypeFilter::Rendered_Files is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::FileLocationTypeFilter::FLTFilter_RenderedFiles
FLTFilter_RenderedFiles
SelectedClipsTimeline
Deprecated
Deprecated PTSLC_CPP::FileLocationTypeFilter::SelectedClipsTimeline is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::FileLocationTypeFilter::FLTFilter_SelectedClipsTimeline
FLTFilter_SelectedClipsTimeline
SelectedClipsClipsList
Deprecated
Deprecated PTSLC_CPP::FileLocationTypeFilter::SelectedClipsClipsList is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::FileLocationTypeFilter::FLTFilter_SelectedClipsClipsList
FLTFilter_SelectedClipsClipsList
FLTFilter_Count
AutomationDataOptions
enum class AutomationDataOptions : int32_t [strong]
Automation data options used with cut/copy/clear commands.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
ADOptions_Unknown
All_Automation
Deprecated
Deprecated PTSLC_CPP::AutomationDataOptions::All_Automation is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::AutomationDataOptions::ADOptions_AllAutomation
ADOptions_AllAutomation
Pan_Automation
Deprecated
Deprecated PTSLC_CPP::AutomationDataOptions::Pan_Automation is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::AutomationDataOptions::ADOptions_PanAutomation
ADOptions_PanAutomation
PlugIn_Automation
Deprecated
Deprecated PTSLC_CPP::AutomationDataOptions::PlugIn_Automation is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::AutomationDataOptions::ADOptions_PlugInAutomation
ADOptions_PlugInAutomation
Clip_Gain
Deprecated
Deprecated PTSLC_CPP::AutomationDataOptions::Clip_Gain is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::AutomationDataOptions::ADOptions_ClipGain
ADOptions_ClipGain
Clip_Effects
Deprecated
Deprecated PTSLC_CPP::AutomationDataOptions::Clip_Effects is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::AutomationDataOptions::ADOptions_ClipEffects
ADOptions_ClipEffects
PasteSpecialOptions
enum class PasteSpecialOptions : int32_t [strong]
Options used with the paste special command.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
PSOptions_Unknown
Merge
MergeMidi
Deprecated
Deprecated PTSLC_CPP::PasteSpecialOptions::MergeMidi is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::PasteSpecialOptions::PSOptions_MergeMidi
PSOptions_MergeMidi
Repeat_To_Fill_Selection
Deprecated
Deprecated PTSLC_CPP::PasteSpecialOptions::Repeat_To_Fill_Selection is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::PasteSpecialOptions::PSOptions_RepeatToFillSelection
PSOptions_RepeatToFillSelection
To_Current_Automation_Type
Deprecated
Deprecated PTSLC_CPP::PasteSpecialOptions::To_Current_Automation_Type is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::PasteSpecialOptions::PSOptions_ToCurrentAutomationType
PSOptions_ToCurrentAutomationType
MergeMarkers
Deprecated
Deprecated PTSLC_CPP::PasteSpecialOptions::MergeMarkers is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::PasteSpecialOptions::PSOptions_MergeMarkers
PSOptions_MergeMarkers
TripleBool
enum class TripleBool : int32_t [strong]
Boolean with `unset` value.
TODO: C++17 transition std::optional<bool>
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
TBool_Unknown
TB_None
TBool_None
TB_False
TBool_False
TB_True
TBool_True
EM_SourceType
enum class EM_SourceType : int32_t [strong]
Available source types for mix source.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
EMSType_Unknown
PhysicalOut
Deprecated
Deprecated PTSLC_CPP::EM_SourceType::PhysicalOut is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EM_SourceType::EMSType_PhysicalOut
EMSType_PhysicalOut
Bus
Deprecated
Deprecated PTSLC_CPP::EM_SourceType::Bus is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EM_SourceType::EMSType_Bus
EMSType_Bus
Output
Deprecated
Deprecated PTSLC_CPP::EM_SourceType::Output is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EM_SourceType::EMSType_Output
EMSType_Output
EM_FileType
enum class EM_FileType : int32_t [strong]
Available file type for mix export.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
EMFType_Unknown
None
Deprecated
Deprecated PTSLC_CPP::EM_FileType::None is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EM_FileType::EMFType_None
EMFType_None
MOV
Deprecated
Deprecated PTSLC_CPP::EM_FileType::MOV is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EM_FileType::EMFType_MOV
EMFType_MOV
WAV
Deprecated
Deprecated PTSLC_CPP::EM_FileType::WAV is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EM_FileType::EMFType_WAV
EMFType_WAV
AIFF
Deprecated
Deprecated PTSLC_CPP::EM_FileType::AIFF is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EM_FileType::EMFType_AIFF
EMFType_AIFF
MP3
Deprecated
Deprecated PTSLC_CPP::EM_FileType::MP3 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EM_FileType::EMFType_MP3
EMFType_MP3
MXFOPAtom
Deprecated
Deprecated PTSLC_CPP::EM_FileType::MXFOPAtom is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EM_FileType::EMFType_MXFOPAtom
EMFType_MXFOPAtom
WAVADM
Deprecated
Deprecated PTSLC_CPP::EM_FileType::WAVADM is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EM_FileType::EMFType_WAVADM
EMFType_WAVADM
CompressionType
enum class CompressionType : int32_t [strong]
Available compression type for audio.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
CType_Unknown
None
Deprecated
Deprecated PTSLC_CPP::CompressionType::None is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::CompressionType::CType_None
CType_None
PCM
Deprecated
Deprecated PTSLC_CPP::CompressionType::PCM is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::CompressionType::CType_PCM
CType_PCM
EM_VideoExportOptions
enum class EM_VideoExportOptions : int32_t [strong]
Available options for export video.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
EMVEOptions_Unknown
None
Deprecated
Deprecated PTSLC_CPP::EM_VideoExportOptions::None is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EM_VideoExportOptions::EMVEOptions_None
EMVEOptions_None
SameAsSource
Deprecated
Deprecated PTSLC_CPP::EM_VideoExportOptions::SameAsSource is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EM_VideoExportOptions::EMVEOptions_SameAsSource
EMVEOptions_SameAsSource
Transcode
Deprecated
Deprecated PTSLC_CPP::EM_VideoExportOptions::Transcode is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EM_VideoExportOptions::EMVEOptions_Transcode
EMVEOptions_Transcode
EM_FileDestination
enum class EM_FileDestination : int32_t [strong]
Available types of file destination.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
EMFDestination_Unknown
None
Deprecated
Deprecated PTSLC_CPP::EM_FileDestination::None is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EM_FileDestination::EMFDestination_None
EMFDestination_None
SessionFolder
Deprecated
Deprecated PTSLC_CPP::EM_VideoExportOptions::SessionFolder is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EM_VideoExportOptions::EMFDestination_SessionFolder
EMFDestination_SessionFolder
Directory
Deprecated
Deprecated PTSLC_CPP::EM_VideoExportOptions::Directory is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EM_VideoExportOptions::EMFDestination_Directory
EMFDestination_Directory
EM_DeliveryFormat
enum class EM_DeliveryFormat : int32_t [strong]
Available delivery formats.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
EMDFormat_Unknown
None
Deprecated
Deprecated PTSLC_CPP::EM_DeliveryFormat::None is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EM_DeliveryFormat::EMDFormat_None
EMDFormat_None
FilePerMixSource
Deprecated
Deprecated PTSLC_CPP::EM_DeliveryFormat::FilePerMixSource is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EM_DeliveryFormat::EMDFormat_FilePerMixSource
EMDFormat_FilePerMixSource
SingleFile
Deprecated
Deprecated PTSLC_CPP::EM_DeliveryFormat::SingleFile is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EM_DeliveryFormat::EMDFormat_SingleFile
EMDFormat_SingleFile
DP_ValueTypes
enum class DP_ValueTypes : int32_t [strong]
Available data types for dynamic properties.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
DPVTypes_Unknown
DP_VT_double
Deprecated
Deprecated PTSLC_CPP::DP_ValueTypes::DP_VT_double is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::DP_ValueTypes::DPVTypes_Double
DPVTypes_Double
DP_VT_float
Deprecated
Deprecated PTSLC_CPP::DP_ValueTypes::DP_VT_float is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::DP_ValueTypes::DPVTypes_Float
DPVTypes_Float
DP_VT_int32
Deprecated
Deprecated PTSLC_CPP::DP_ValueTypes::DP_VT_int32 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::DP_ValueTypes::DPVTypes_Int32
DPVTypes_Int32
DP_VT_int64
Deprecated
Deprecated PTSLC_CPP::DP_ValueTypes::DP_VT_int64 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::DP_ValueTypes::DPVTypes_Int64
DPVTypes_Int64
DP_VT_uint32
Deprecated
Deprecated PTSLC_CPP::DP_ValueTypes::DP_VT_uint32 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::DP_ValueTypes::DPVTypes_Uint32
DPVTypes_Uint32
DP_VT_uint64
Deprecated
Deprecated PTSLC_CPP::DP_ValueTypes::DP_VT_uint64 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::DP_ValueTypes::DPVTypes_Uint64
DPVTypes_Uint64
DP_VT_sint32
Deprecated
Deprecated PTSLC_CPP::DP_ValueTypes::DP_VT_sint32 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::DP_ValueTypes::DPVTypes_Sint32
DPVTypes_Sint32
DP_VT_sint64
Deprecated
Deprecated PTSLC_CPP::DP_ValueTypes::DP_VT_sint64 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::DP_ValueTypes::DPVTypes_Sint64
DPVTypes_Sint64
DP_VT_fixed32
Deprecated
Deprecated PTSLC_CPP::DP_ValueTypes::DP_VT_fixed32 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::DP_ValueTypes::DPVTypes_Fixed32
DPVTypes_Fixed32
DP_VT_fixed64
Deprecated
Deprecated PTSLC_CPP::DP_ValueTypes::DP_VT_fixed64 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::DP_ValueTypes::DPVTypes_Fixed64
DPVTypes_Fixed64
DP_VT_sfixed32
Deprecated
Deprecated PTSLC_CPP::DP_ValueTypes::DP_VT_sfixed32 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::DP_ValueTypes::DPVTypes_Sfixed32
DPVTypes_Sfixed32
DP_VT_sfixed64
Deprecated
Deprecated PTSLC_CPP::DP_ValueTypes::DP_VT_sfixed64 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::DP_ValueTypes::DPVTypes_Sfixed64
DPVTypes_Sfixed64
DP_VT_bool
Deprecated
Deprecated PTSLC_CPP::DP_ValueTypes::DP_VT_bool is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::DP_ValueTypes::DPVTypes_Bool
DPVTypes_Bool
DP_VT_string
Deprecated
Deprecated PTSLC_CPP::DP_ValueTypes::DP_VT_string is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::DP_ValueTypes::DPVTypes_String
DPVTypes_String
DP_VT_bytes
Deprecated
Deprecated PTSLC_CPP::DP_ValueTypes::DP_VT_bytes is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::DP_ValueTypes::DPVTypes_Bytes
DPVTypes_Bytes
DP_VT_enum
Deprecated
Deprecated PTSLC_CPP::DP_ValueTypes::DP_VT_enum is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::DP_ValueTypes::DPVTypes_Enum
DPVTypes_Enum
DP_VT_object
Deprecated
Deprecated PTSLC_CPP::DP_ValueTypes::DP_VT_object is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::DP_ValueTypes::DPVTypes_Object
DPVTypes_Object
DynamicPropertyType
enum class DynamicPropertyType : int32_t [strong]
Available types of dynamic properties.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
DPType_Unknown
DP_EM_CodecInfo
Deprecated
Deprecated PTSLC_CPP::DynamicPropertyType::DP_EM_CodecInfo is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::DynamicPropertyType::DPType_CodecInfo
DPType_CodecInfo
DP_EM_DolbyAtmosInfo
Deprecated
Deprecated PTSLC_CPP::DynamicPropertyType::DP_EM_DolbyAtmosInfo is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::DynamicPropertyType::DPType_DolbyAtmosInfo
DPType_DolbyAtmosInfo
TrackListType
enum class TrackListType : int32_t [strong]
Available track list types.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
TListType_Unknown
AllTracks
Deprecated
Deprecated PTSLC_CPP::TrackListType::AllTracks is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackListType::TListType_AllTracks
TListType_AllTracks
SelectedTracksOnly
Deprecated
Deprecated PTSLC_CPP::TrackListType::SelectedTracksOnly is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TrackListType::TListType_SelectedTracksOnly
TListType_SelectedTracksOnly
FadeHandlingType
enum class FadeHandlingType : int32_t [strong]
Available fade handling types.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
FHType_Unknown
ShowCrossfades
Deprecated
Deprecated PTSLC_CPP::FadeHandlingType::ShowCrossfades is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::FadeHandlingType::FHType_ShowCrossfades
FHType_ShowCrossfades
DontShowCrossfades
Deprecated
Deprecated PTSLC_CPP::FadeHandlingType::DontShowCrossfades is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::FadeHandlingType::FHType_DontShowCrossfades
FHType_DontShowCrossfades
CombineCrossfadedClips
Deprecated
Deprecated PTSLC_CPP::FadeHandlingType::CombineCrossfadedClips is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::FadeHandlingType::FHType_CombineCrossfadedClips
FHType_CombineCrossfadedClips
TextAsFileFormat
enum class TextAsFileFormat : int32_t [strong]
Available file formats.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
TFFormat_Unknown
TextEdit
Deprecated
Deprecated PTSLC_CPP::TextAsFileFormat::TextEdit is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TextAsFileFormat::TFFormat_TextEdit
TFFormat_TextEdit
UTF8
Deprecated
Deprecated PTSLC_CPP::TextAsFileFormat::UTF8 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TextAsFileFormat::TFFormat_UTF8
TFFormat_UTF8
ESI_OutputType
enum class ESI_OutputType : int32_t [strong]
Available output types.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
ESI_Unknown
Deprecated
Deprecated PTSLC_CPP::ESI_OutputType::ESI_Unknown is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::ESI_OutputType::ESIOType_Unknown
ESIOType_Unknown
ESI_File
Deprecated
Deprecated PTSLC_CPP::ESI_OutputType::ESI_File is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::ESI_OutputType::ESIOType_File
ESIOType_File
ESI_String
Deprecated
Deprecated PTSLC_CPP::ESI_OutputType::ESI_String is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::ESI_OutputType::ESIOType_String
ESIOType_String
PlaybackMode
enum class PlaybackMode : int32_t [strong]
Types of the playback mode.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
PMode_Unknown
PM_Normal
Deprecated
Deprecated PTSLC_CPP::PM_PlaybackMode::PM_Normal is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::PlaybackMode::PMode_Normal
PMode_Normal
PM_Loop
Deprecated
Deprecated PTSLC_CPP::PM_PlaybackMode::PM_Loop is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::PlaybackMode::PMode_Loop
PMode_Loop
PM_DynamicTransport
Deprecated
Deprecated PTSLC_CPP::PM_PlaybackMode::PM_DynamicTransport is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::PlaybackMode::PMode_DynamicTransport
PMode_DynamicTransport
RecordMode
enum class RecordMode : int32_t [strong]
Types of the record mode.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
RMode_Unknown
RM_Normal
Deprecated
Deprecated PTSLC_CPP::RM_RecordMode::RM_Normal is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::RecordMode::RMode_Normal
RMode_Normal
RM_Loop
Deprecated
Deprecated PTSLC_CPP::RM_RecordMode::RM_Loop is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::RecordMode::RMode_Loop
RMode_Loop
RM_Destructive
Deprecated
Deprecated PTSLC_CPP::RM_RecordMode::RM_Destructive is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::RecordMode::RMode_Destructive
RMode_Destructive
RM_QuickPunch
Deprecated
Deprecated PTSLC_CPP::RM_RecordMode::RM_QuickPunch is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::RecordMode::RMode_QuickPunch
RMode_QuickPunch
RM_TrackPunch
Deprecated
Deprecated PTSLC_CPP::RM_RecordMode::RM_TrackPunch is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::RecordMode::RMode_TrackPunch
RMode_TrackPunch
RM_DestructivePunch
Deprecated
Deprecated PTSLC_CPP::RM_RecordMode::RM_DestructivePunch is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::RecordMode::RMode_DestructivePunch
RMode_DestructivePunch
SessionAudioFormat
enum class SessionAudioFormat : int32_t [strong]
Type of session audio file format.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
SAFormat_Unknown
SAF_WAVE
Deprecated
Deprecated PTSLC_CPP::SessionAudioFormat::SAF_WAVE is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionAudioFormat::SAFormat_WAVE
SAFormat_WAVE
SAF_AIFF
Deprecated
Deprecated PTSLC_CPP::SessionAudioFormat::SAF_AIFF is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionAudioFormat::SAFormat_AIFF
SAFormat_AIFF
SessionTimeCodeRate
enum class SessionTimeCodeRate : int32_t [strong]
Type of session time code rate.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
STCRate_Unknown
STCR_Fps23976
Deprecated
Deprecated PTSLC_CPP::SessionTimeCodeRate::STCR_Fps23976 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionTimeCodeRate::STCRate_Fps23976
STCRate_Fps23976
STCR_Fps24
Deprecated
Deprecated PTSLC_CPP::SessionTimeCodeRate::STCR_Fps24 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionTimeCodeRate::STCRate_Fps24
STCRate_Fps24
STCR_Fps25
Deprecated
Deprecated PTSLC_CPP::SessionTimeCodeRate::STCR_Fps25 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionTimeCodeRate::STCRate_Fps25
STCRate_Fps25
STCR_Fps2997
Deprecated
Deprecated PTSLC_CPP::SessionTimeCodeRate::STCR_Fps2997 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionTimeCodeRate::STCRate_Fps2997
STCRate_Fps2997
STCR_Fps2997Drop
Deprecated
Deprecated PTSLC_CPP::SessionTimeCodeRate::STCR_Fps2997Drop is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionTimeCodeRate::STCRate_Fps2997Drop
STCRate_Fps2997Drop
STCR_Fps30
Deprecated
Deprecated PTSLC_CPP::SessionTimeCodeRate::STCR_Fps30 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionTimeCodeRate::STCRate_Fps30
STCRate_Fps30
STCR_Fps30Drop
Deprecated
Deprecated PTSLC_CPP::SessionTimeCodeRate::STCR_Fps30Drop is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionTimeCodeRate::STCRate_Fps30Drop
STCRate_Fps30Drop
STCR_Fps47952
Deprecated
Deprecated PTSLC_CPP::SessionTimeCodeRate::STCR_Fps47952 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionTimeCodeRate::STCRate_Fps47952
STCRate_Fps47952
STCR_Fps48
Deprecated
Deprecated PTSLC_CPP::SessionTimeCodeRate::STCR_Fps48 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionTimeCodeRate::STCRate_Fps48
STCRate_Fps48
STCR_Fps50
Deprecated
Deprecated PTSLC_CPP::SessionTimeCodeRate::STCR_Fps50 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionTimeCodeRate::STCRate_Fps50
STCRate_Fps50
STCR_Fps5994
Deprecated
Deprecated PTSLC_CPP::SessionTimeCodeRate::STCR_Fps5994 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionTimeCodeRate::STCRate_Fps5994
STCRate_Fps5994
STCR_Fps5994Drop
Deprecated
Deprecated PTSLC_CPP::SessionTimeCodeRate::STCR_Fps5994Drop is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionTimeCodeRate::STCRate_Fps5994Drop
STCRate_Fps5994Drop
STCR_Fps60
Deprecated
Deprecated PTSLC_CPP::SessionTimeCodeRate::STCR_Fps60 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionTimeCodeRate::STCRate_Fps60
STCRate_Fps60
STCR_Fps60Drop
Deprecated
Deprecated PTSLC_CPP::SessionTimeCodeRate::STCR_Fps60Drop is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionTimeCodeRate::STCRate_Fps60Drop
STCRate_Fps60Drop
STCR_Fps100
Deprecated
Deprecated PTSLC_CPP::SessionTimeCodeRate::STCR_Fps100 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionTimeCodeRate::STCRate_Fps100
STCRate_Fps100
STCR_Fps11988
Deprecated
Deprecated PTSLC_CPP::SessionTimeCodeRate::STCR_Fps11988 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionTimeCodeRate::STCRate_Fps11988
STCRate_Fps11988
STCR_Fps11988Drop
Deprecated
Deprecated PTSLC_CPP::SessionTimeCodeRate::STCR_Fps11988Drop is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionTimeCodeRate::STCRate_Fps11988Drop
STCRate_Fps11988Drop
STCR_Fps120
Deprecated
Deprecated PTSLC_CPP::SessionTimeCodeRate::STCR_Fps120 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionTimeCodeRate::STCRate_Fps120
STCRate_Fps120
STCR_Fps120Drop
Deprecated
Deprecated PTSLC_CPP::SessionTimeCodeRate::STCR_Fps120Drop is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionTimeCodeRate::STCRate_Fps120Drop
STCRate_Fps120Drop
SessionFeetFramesRate
enum class SessionFeetFramesRate : int32_t [strong]
Type of session feet+frames rate.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
SFFRate_Unknown
SFFR_Fps23976
Deprecated
Deprecated PTSLC_CPP::SessionFeetFramesRate::SFFR_Fps23976 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionFeetFramesRate::SFFRate_Fps23976
SFFRate_Fps23976
SFFR_Fps24
Deprecated
Deprecated PTSLC_CPP::SessionFeetFramesRate::SFFR_Fps24 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionFeetFramesRate::SFFRate_Fps24
SFFRate_Fps24
SFFR_Fps25
Deprecated
Deprecated PTSLC_CPP::SessionFeetFramesRate::SFFR_Fps25 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionFeetFramesRate::SFFRate_Fps25
SFFRate_Fps25
SessionRatePull
enum class SessionRatePull : int32_t [strong]
Type of session audio/video rate pull up/down.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
SRPull_Unknown
SRP_None
Deprecated
Deprecated PTSLC_CPP::SessionRatePull::SRP_None is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionRatePull::SRPull_None
SRPull_None
SRP_Up01
Deprecated
Deprecated PTSLC_CPP::SessionRatePull::SRP_Up01 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionRatePull::SRPull_Up01
SRPull_Up01
SRP_Down01
Deprecated
Deprecated PTSLC_CPP::SessionRatePull::SRP_Down01 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionRatePull::SRPull_Down01
SRPull_Down01
SRP_Up4
Deprecated
Deprecated PTSLC_CPP::SessionRatePull::SRP_Up4 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionRatePull::SRPull_Up4
SRPull_Up4
SRP_Up4Up01
Deprecated
Deprecated PTSLC_CPP::SessionRatePull::SRP_Up4Up01 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionRatePull::SRPull_Up4Up01
SRPull_Up4Up01
SRP_Up4Down01
Deprecated
Deprecated PTSLC_CPP::SessionRatePull::SRP_Up4Down01 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionRatePull::SRPull_Up4Down01
SRPull_Up4Down01
SRP_Down4
Deprecated
Deprecated PTSLC_CPP::SessionRatePull::SRP_Down4 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionRatePull::SRPull_Down4
SRPull_Down4
SRP_Down4Up01
Deprecated
Deprecated PTSLC_CPP::SessionRatePull::SRP_Down4Up01 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionRatePull::SRPull_Down4Up01
SRPull_Down4Up01
SRP_Down4Down01
Deprecated
Deprecated PTSLC_CPP::SessionRatePull::SRP_Down4Down01 is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SessionRatePull::SRPull_Down4Down01
SRPull_Down4Down01
VersionedPTSLComponents
enum class VersionedPTSLComponents : int32_t [strong]
We provide versioning of such kinds of PTSL components.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
VPTSLComponents_Unknown
Host
Deprecated
Deprecated PTSLC_CPP::VersionedPTSLComponents::Host is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::VersionedPTSLComponents::VPTSLComponents_Host
VPTSLComponents_Host
Client
Deprecated
Deprecated PTSLC_CPP::VersionedPTSLComponents::Client is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::VersionedPTSLComponents::VPTSLComponents_Client
VPTSLComponents_Client
ClientAPI
Deprecated
Deprecated PTSLC_CPP::VersionedPTSLComponents::ClientAPI is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::VersionedPTSLComponents::VPTSLComponents_ClientAPI
VPTSLComponents_ClientAPI
TransportState
enum class TransportState : int32_t [strong]
Types of the transport state.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
TState_Unknown
TS_TransportPlaying
Deprecated
Deprecated PTSLC_CPP::TS_TransportState::TS_TransportPlaying is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TransportState::TState_TransportPlaying
TState_TransportPlaying
TS_TransportStopped
Deprecated
Deprecated PTSLC_CPP::TS_TransportState::TS_TransportStopped is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TransportState::TState_TransportStopped
TState_TransportStopped
TS_TransportRecording
Deprecated
Deprecated PTSLC_CPP::TS_TransportState::TS_TransportRecording is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TransportState::TState_TransportRecording
TState_TransportRecording
TS_TransportPlayingHalfSpeed
Deprecated
Deprecated PTSLC_CPP::TS_TransportState::TS_TransportPlayingHalfSpeed is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TransportState::TState_TransportPlayingHalfSpeed
TState_TransportPlayingHalfSpeed
TS_TransportRecordingHalfSpeed
Deprecated
Deprecated PTSLC_CPP::TS_TransportState::TS_TransportRecordingHalfSpeed is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TransportState::TState_TransportRecordingHalfSpeed
TState_TransportRecordingHalfSpeed
TS_TransportFastForward
Deprecated
Deprecated PTSLC_CPP::TS_TransportState::TS_TransportFastForward is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TransportState::TState_TransportFastForward
TState_TransportFastForward
TS_TransportRewind
Deprecated
Deprecated PTSLC_CPP::TS_TransportState::TS_TransportRewind is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TransportState::TState_TransportRewind
TState_TransportRewind
TS_TransportScrub
Deprecated
Deprecated PTSLC_CPP::TS_TransportState::TS_TransportScrub is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TransportState::TState_TransportScrub
TState_TransportScrub
TS_TransportShuttle
Deprecated
Deprecated PTSLC_CPP::TS_TransportState::TS_TransportShuttle is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TransportState::TState_TransportShuttle
TState_TransportShuttle
TS_TransportPrimed
Deprecated
Deprecated PTSLC_CPP::TS_TransportState::TS_TransportPrimed is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TransportState::TState_TransportPrimed
TState_TransportPrimed
TS_TransportIsCueing
Deprecated
Deprecated PTSLC_CPP::TS_TransportState::TS_TransportIsCueing is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TransportState::TState_TransportIsCueing
TState_TransportIsCueing
TS_TransportIsCued
Deprecated
Deprecated PTSLC_CPP::TS_TransportState::TS_TransportIsCued is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TransportState::TState_TransportIsCued
TState_TransportIsCued
TS_TransportIsCuedForPreview
Deprecated
Deprecated PTSLC_CPP::TS_TransportState::TS_TransportIsCuedForPreview is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TransportState::TState_TransportIsCuedForPreview
TState_TransportIsCuedForPreview
TS_TransportIsStopping
Deprecated
Deprecated PTSLC_CPP::TS_TransportState::TS_TransportIsStopping is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TransportState::TState_TransportIsStopping
TState_TransportIsStopping
TS_TransportIsPreviewing
Deprecated
Deprecated PTSLC_CPP::TS_TransportState::TS_TransportIsPreviewing is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TransportState::TState_TransportIsPreviewing
TState_TransportIsPreviewing
ClipLocation
enum class ClipLocation : int32_t [strong]
Types of the clip locations.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
CLocation_Unknown
CL_ClipsList
Deprecated
Deprecated PTSLC_CPP::CL_ClipLocation::CL_ClipsList is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::ClipLocation::CLocation_ClipsList
CLocation_ClipsList
CL_Timeline
Deprecated
Deprecated PTSLC_CPP::CL_ClipLocation::CL_Timeline is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::ClipLocation::CLocation_Timeline
CLocation_Timeline
TimeProperties
enum class TimeProperties : int32_t [strong]
Type of time properties.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
TProperties_Unknown
TP_Marker
Deprecated
Deprecated PTSLC_CPP::TimeProperties::TP_Marker is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TimeProperties::TProperties_Marker
TProperties_Marker
TP_Selection
Deprecated
Deprecated PTSLC_CPP::TimeProperties::TP_Selection is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TimeProperties::TProperties_Selection
TProperties_Selection
TP_None
Deprecated
Deprecated PTSLC_CPP::TimeProperties::TP_None is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TimeProperties::TProperties_None
TProperties_None
MarkerLocation
enum class MarkerLocation : int32_t [strong]
Type of marker location.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
MLC_Unknown
Deprecated
Deprecated PTSLC_CPP::MarkerLocation::MLC_Unknown is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::MarkerLocation::MarkerLocation_Unknown
MarkerLocation_Unknown
MLC_MainRuler
Deprecated
Deprecated PTSLC_CPP::MarkerLocation::MLC_MainRuler is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::MarkerLocation::MarkerLocation_MainRuler
MarkerLocation_MainRuler
MLC_Track
Deprecated
Deprecated PTSLC_CPP::MarkerLocation::MLC_Track is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::MarkerLocation::MarkerLocation_Track
MarkerLocation_Track
MemoryLocationReference
enum class MemoryLocationReference : int32_t [strong]
Type of memory location reference.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
MLReference_Unknown
MLR_BarBeat
Deprecated
Deprecated PTSLC_CPP::MemoryLocationReference::MLR_BarBeat is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::MemoryLocationReference::MLReference_BarBeat
MLReference_BarBeat
MLR_Absolute
Deprecated
Deprecated PTSLC_CPP::MemoryLocationReference::MLR_Absolute is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::MemoryLocationReference::MLReference_Absolute
MLReference_Absolute
MLR_FollowTrackTimebase
Deprecated
Deprecated PTSLC_CPP::MemoryLocationReference::MLR_FollowTrackTimebase is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::MemoryLocationReference::MLReference_FollowTrackTimebase
MLReference_FollowTrackTimebase
TrackInsertionPoint
enum class TrackInsertionPoint [strong]
Enumeration that describes the position of the insertion point for creating new tracks.
Supported starting in Pro Tools 2024.06
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
TIPoint_Unknown Default value, the insertion point is determined by Pro Tools.
TIPoint_Before The insertion point is before the specified track.
TIPoint_After The insertion point is after the specified track.
TIPoint_First The insertion point is either the first track in the session or the first member track of the specified folder track.
TIPoint_Last The insertion point is either the last track in the session or the last member track of the specified folder track.
EditMode
enum class EditMode : int32_t [strong]
Type of edit mode.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
EMO_Unknown
Deprecated
Deprecated PTSLC_CPP::EditMode::EMO_Unknown is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditMode::EMode_Unknown
EMode_Unknown
EMO_Shuffle
Deprecated
Deprecated PTSLC_CPP::EditMode::EMO_Shuffle is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::MemoryLocationReference::EMode_Shuffle
EMode_Shuffle
EMO_Slip
Deprecated
Deprecated PTSLC_CPP::EditMode::EMO_Slip is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditMode::EMode_Slip
EMode_Slip
EMO_Spot
Deprecated
Deprecated PTSLC_CPP::EditMode::EMO_Spot is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditMode::EMode_Spot
EMode_Spot
EMO_GridAbsolute
Deprecated
Deprecated PTSLC_CPP::EditMode::EMO_GridAbsolute is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditMode::EMode_GridAbsolute
EMode_GridAbsolute
EMO_GridRelative
Deprecated
Deprecated PTSLC_CPP::EditMode::EMO_GridRelative is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditMode::EMode_GridRelative
EMode_GridRelative
EMO_ShuffleSnapToGridAbsolute
Deprecated
Deprecated PTSLC_CPP::EditMode::EMO_ShuffleSnapToGridAbsolute is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditMode::EMode_ShuffleSnapToGridAbsolute
EMode_ShuffleSnapToGridAbsolute
EMO_SlipSnapToGridAbsolute
Deprecated
Deprecated PTSLC_CPP::EditMode::EMO_SlipSnapToGridAbsolute is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditMode::EMode_SlipSnapToGridAbsolute
EMode_SlipSnapToGridAbsolute
EMO_SpotSnapToGridAbsolute
Deprecated
Deprecated PTSLC_CPP::EditMode::EMO_SpotSnapToGridAbsolute is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditMode::EMode_SpotSnapToGridAbsolute
EMode_SpotSnapToGridAbsolute
EMO_ShuffleSnapToGridRelative
Deprecated
Deprecated PTSLC_CPP::EditMode::EMO_ShuffleSnapToGridRelative is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditMode::EMode_ShuffleSnapToGridRelative
EMode_ShuffleSnapToGridRelative
EMO_SlipSnapToGridRelative
Deprecated
Deprecated PTSLC_CPP::EditMode::EMO_SlipSnapToGridRelative is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditMode::EMode_SlipSnapToGridRelative
EMode_SlipSnapToGridRelative
EMO_SpotSnapToGridRelative
Deprecated
Deprecated PTSLC_CPP::EditMode::EMO_SpotSnapToGridRelative is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditMode::EMode_SpotSnapToGridRelative
EMode_SpotSnapToGridRelative
EditTool
enum class EditTool : int32_t [strong]
Type of edit tool.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
ET_Unknown
Deprecated
Deprecated PTSLC_CPP::EditTool::ET_Unknown is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditTool::ETool_Unknown
ETool_Unknown
ET_ZoomNormal
Deprecated
Deprecated PTSLC_CPP::EditTool::ET_ZoomNormal is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditTool::ETool_ZoomNormal
ETool_ZoomNormal
ET_ZoomSingle
Deprecated
Deprecated PTSLC_CPP::EditTool::ET_ZoomSingle is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditTool::ETool_ZoomSingle
ETool_ZoomSingle
ET_TrimStandard
Deprecated
Deprecated PTSLC_CPP::EditTool::ET_TrimStandard is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditTool::ETool_TrimStandard
ETool_TrimStandard
ET_TrimTce
Deprecated
Deprecated PTSLC_CPP::EditTool::ET_TrimTce is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditTool::ETool_TrimTce
ETool_TrimTce
ET_TrimScrub
Deprecated
Deprecated PTSLC_CPP::EditTool::ET_TrimScrub is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditTool::ETool_TrimScrub
ETool_TrimScrub
ET_TrimLoop
Deprecated
Deprecated PTSLC_CPP::EditTool::ET_TrimLoop is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditTool::ETool_TrimLoop
ETool_TrimLoop
ET_Selector
Deprecated
Deprecated PTSLC_CPP::EditTool::ET_Selector is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditTool::ETool_Selector
ETool_Selector
ET_GrabberTime
Deprecated
Deprecated PTSLC_CPP::EditTool::ET_GrabberTime is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditTool::ETool_GrabberTime
ETool_GrabberTime
ET_GrabberSeparation
Deprecated
Deprecated PTSLC_CPP::EditTool::ET_GrabberSeparation is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditTool::ETool_GrabberSeparation
ETool_GrabberSeparation
ET_GrabberObject
Deprecated
Deprecated PTSLC_CPP::EditTool::ET_GrabberObject is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditTool::ETool_GrabberObject
ETool_GrabberObject
ET_SmartTool
Deprecated
Deprecated PTSLC_CPP::EditTool::ET_SmartTool is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditTool::ETool_SmartTool
ETool_SmartTool
ET_Scrubber
Deprecated
Deprecated PTSLC_CPP::EditTool::ET_Scrubber is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditTool::ETool_Scrubber
ETool_Scrubber
ET_PencilFreeHand
Deprecated
Deprecated PTSLC_CPP::EditTool::ET_PencilFreeHand is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditTool::ETool_PencilFreeHand
ETool_PencilFreeHand
ET_PencilLine
Deprecated
Deprecated PTSLC_CPP::EditTool::ET_PencilLine is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditTool::ETool_PencilLine
ETool_PencilLine
ET_PencilTriangle
Deprecated
Deprecated PTSLC_CPP::EditTool::ET_PencilTriangle is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditTool::ETool_PencilTriangle
ETool_PencilTriangle
ET_PencilSquare
Deprecated
Deprecated PTSLC_CPP::EditTool::ET_PencilSquare is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditTool::ETool_PencilSquare
ETool_PencilSquare
ET_PencilRandom
Deprecated
Deprecated PTSLC_CPP::EditTool::ET_PencilRandom is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditTool::ETool_PencilRandom
ETool_PencilRandom
ET_PencilParabolic
Deprecated
Deprecated PTSLC_CPP::EditTool::ET_PencilParabolic is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditTool::ETool_PencilParabolic
ETool_PencilParabolic
ET_PencilSCurve
Deprecated
Deprecated PTSLC_CPP::EditTool::ET_PencilSCurve is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::EditTool::ETool_PencilSCurve
ETool_PencilSCurve
TimelineUpdateVideo
enum class TimelineUpdateVideo : int32_t [strong]
Enumerator
TUV_Unknown
Deprecated
Deprecated PTSLC_CPP::TimelineUpdateVideo::TUV_Unknown is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TimelineUpdateVideo::TUVideo_Unknown
TUVideo_Unknown
TUV_None
Deprecated
Deprecated PTSLC_CPP::TimelineUpdateVideo::TUV_None is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TimelineUpdateVideo::TUVideo_None
TUVideo_None
TUV_In
Deprecated
Deprecated PTSLC_CPP::TimelineUpdateVideo::TUV_In is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TimelineUpdateVideo::TUVideo_In
TUVideo_In
TUV_Out
Deprecated
Deprecated PTSLC_CPP::TimelineUpdateVideo::TUV_Out is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::TimelineUpdateVideo::TUVideo_Out
TUVideo_Out
SelectionMode
enum class SelectionMode : int32_t [strong]
Type of the track's possible selection.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
SM_Unknown
Deprecated
Deprecated PTSLC_CPP::SelectionMode::SM_Unknown is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SelectionMode::SMode_Unknown
SMode_Unknown
SM_Replace
Deprecated
Deprecated PTSLC_CPP::SelectionMode::SM_Replace is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SelectionMode::SMode_Replace
SMode_Replace
SM_Add
Deprecated
Deprecated PTSLC_CPP::SelectionMode::SM_Add is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SelectionMode::SMode_Add
SMode_Add
SM_Subtract
Deprecated
Deprecated PTSLC_CPP::SelectionMode::SM_Subtract is deprecated starting in Pro Tools 2025.06 Replaced with PTSLC_CPP::SelectionMode::SMode_Subtract
SMode_Subtract
TrackFromClipGroupExclusionReason
enum class TrackFromClipGroupExclusionReason [strong]
Possible reasons why clip groups could not be created on specific tracks.
Supported starting in Pro Tools 2024.06
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
TCGEReason_Unknown Tech-only value returned when the reason is unknown.
TCGEReason_TrackTypeIsNotAllowed Clip groups cannot be created on particular track types (e.g. Aux Input, VCA or Master).
TCGEReason_TrackIsFrozen Clip groups cannot be created on frozen tracks.
TCGEReason_TrackIsClosed Clip groups cannot be created on closed Folder tracks.
TCGEReason_TrackIsLocked Clip groups cannot be created on locked Video tracks.
TCGEReason_TrackIsInPlaylistView Clip groups cannot be created on tracks in playlists view.
TCGEReason_TrackIsElasticAudioWithFades Clip groups with embedded fades are not supported on Elastic Audio-enabled tracks.
BasicTimeType
enum class BasicTimeType [strong]
One of the fundamental time units.
Deprecated
Deprecated All API-specific types in the C++ client lib are deprecated starting in Pro Tools 2024.10 since we introduced general JSON-based request/response.
Enumerator
BTType_Unknown
BTType_Samples
BTType_Ticks
BTType_Frames
Function Documentation
IsCancellationRequested()
bool IsCancellationRequested (const std::future< T > & cancellation)
Utility method that checks whether cancellation of Task (std::future<void>) is required.
Work with async tasks implemented by analogy with C#.
Referenced by CppPTSLClient::MakeStreamingRequest().
AsyncDelay()
void AsyncDelay (const std::future< T > & cancellation, std::chrono::milliseconds delay = std::chrono::milliseconds(1))
Utility method that asynchronously waits for the specified task to complete within a specified delay.
The method throws a TaskCancelledException when the wait completes. Implemented by analogy with C#'s Task.Delay.
AsyncWait()
std::shared_ptr< Response > AsyncWait (ClientFunctionPtr func, ClientPtr ptr, const Request & request)
Utility method that runs the function func asynchronously (potentially in a separate thread which might be a part of a thread pool) and waits for the result of this function, and returns the result.
Implemented by analogy with C#'s async/await.
AsyncWait2()
void AsyncWait2 (ClientPtr caller, ClientFunction callerFunc, Args &&... args)
encrypt()
std::vector< unsigned char > PTSLC_CPP_EXPORT encrypt (const std::string & text, const std::string & publicEncryptionKey)
Encrypts a text string with given RSA key.
Referenced by PtslCmdCommandRunner::RunCommand().
encodeBase64()
std::string PTSLC_CPP_EXPORT encodeBase64 (const std::vector< unsigned char > & data)
Encodes byte array into base 64 string.
Referenced by PtslCmdCommandRunner::RunCommand().
DefaultJsonWriteOptions()
static google::protobuf::util::JsonOptions DefaultJsonWriteOptions () [static]
Referenced by DefaultRequestHandler::ConvertRequestBodyToJson().
DefaultJsonParseOptions()
static google::protobuf::util::JsonParseOptions DefaultJsonParseOptions () [static]
Referenced by DefaultRequestHandler::ConvertJsonToResponseBody(), DefaultRequestHandler::ConvertJsonToResponseError(), and CppPTSLClient::HostReadyCheck().
Is()
bool Is (const Src * exc)
Utility method that checks object type.
Equivalent of C#'s 'is' operator.
GetStringFromEnum()
std::string GetStringFromEnum (const DescriptorT * descriptor, EnumT value)
Referenced by EnumToString< CommandStatusType >(), and EnumToString< TripleBool >().
GetEnumFromString()
std::optional< EnumT > GetEnumFromString (const DescriptorT * descriptor, const std::string & value)
EnumValuesToStrings()
PTSLC_CPP_EXPORT std::vector< std::string > EnumValuesToStrings (const std::string & enumTypeName)
Referenced by PrintHelpHelpers::PrintCommandListHelp().
DEFINE_PTSL_ENUM_CONVERSIONS() [1/9]
DEFINE_PTSL_ENUM_CONVERSIONS (CommandId)
DEFINE_PTSL_ENUM_CONVERSIONS() [2/9]
DEFINE_PTSL_ENUM_CONVERSIONS (CommandErrorType)
DEFINE_PTSL_ENUM_CONVERSIONS() [3/9]
DEFINE_PTSL_ENUM_CONVERSIONS (TrackType)
DEFINE_PTSL_ENUM_CONVERSIONS() [4/9]
DEFINE_PTSL_ENUM_CONVERSIONS (TrackFormat)
DEFINE_PTSL_ENUM_CONVERSIONS() [5/9]
DEFINE_PTSL_ENUM_CONVERSIONS (TrackTimebase)
DEFINE_PTSL_ENUM_CONVERSIONS() [6/9]
DEFINE_PTSL_ENUM_CONVERSIONS (TrackOffsetOptions)
DEFINE_PTSL_ENUM_CONVERSIONS() [7/9]
DEFINE_PTSL_ENUM_CONVERSIONS (TimelineUpdateVideo)
DEFINE_PTSL_ENUM_CONVERSIONS() [8/9]
DEFINE_PTSL_ENUM_CONVERSIONS (TrackFromClipGroupExclusionReason)
DEFINE_PTSL_ENUM_CONVERSIONS() [9/9]
DEFINE_PTSL_ENUM_CONVERSIONS (TrackInsertionPoint)
EnumToString< CommandStatusType >()
PTSLC_CPP_EXPORT std::string EnumToString< CommandStatusType > (CommandStatusType value)
References GetStringFromEnum().
StringToEnum< CommandStatusType >()
PTSLC_CPP_EXPORT std::optional< CommandStatusType > StringToEnum< CommandStatusType > (const std::string & value)
EnumToString< TripleBool >()
PTSLC_CPP_EXPORT std::string EnumToString< TripleBool > (TripleBool value)
References GetStringFromEnum().
StringToEnum< TripleBool >()
PTSLC_CPP_EXPORT std::optional< TripleBool > StringToEnum< TripleBool > (const std::string & value)
References TB_False, TB_None, and TB_True.
EnumToString()
std::string EnumToString (T value)
Referenced by PtslCmdCommandResult::PtslCmdCommandResult(), and TEST().
StringToEnum()
std::optional< T > StringToEnum (const std::string & value)
DECLARE_PTSL_ENUM_CONVERSIONS() [1/11]
DECLARE_PTSL_ENUM_CONVERSIONS (CommandId)
DECLARE_PTSL_ENUM_CONVERSIONS() [2/11]
DECLARE_PTSL_ENUM_CONVERSIONS (CommandStatusType)
DECLARE_PTSL_ENUM_CONVERSIONS() [3/11]
DECLARE_PTSL_ENUM_CONVERSIONS (CommandErrorType)
DECLARE_PTSL_ENUM_CONVERSIONS() [4/11]
DECLARE_PTSL_ENUM_CONVERSIONS (TrackType)
DECLARE_PTSL_ENUM_CONVERSIONS() [5/11]
DECLARE_PTSL_ENUM_CONVERSIONS (TrackFormat)
DECLARE_PTSL_ENUM_CONVERSIONS() [6/11]
DECLARE_PTSL_ENUM_CONVERSIONS (TrackTimebase)
DECLARE_PTSL_ENUM_CONVERSIONS() [7/11]
DECLARE_PTSL_ENUM_CONVERSIONS (TimelineUpdateVideo)
DECLARE_PTSL_ENUM_CONVERSIONS() [8/11]
DECLARE_PTSL_ENUM_CONVERSIONS (TripleBool)
DECLARE_PTSL_ENUM_CONVERSIONS() [9/11]
DECLARE_PTSL_ENUM_CONVERSIONS (TrackOffsetOptions)
DECLARE_PTSL_ENUM_CONVERSIONS() [10/11]
DECLARE_PTSL_ENUM_CONVERSIONS (TrackFromClipGroupExclusionReason)
DECLARE_PTSL_ENUM_CONVERSIONS() [11/11]
DECLARE_PTSL_ENUM_CONVERSIONS (TrackInsertionPoint)
ConvertProtoToCommandError()
static void ConvertProtoToCommandError (const ptsl::CommandError & in, CommandError & out) [static]
References CommandError::command_error_message, CommandError::command_error_type, CommandError::errorMessage, CommandError::errorType, CommandError::is_warning, and CommandError::isWarning.
Referenced by CppPTSLClient::ClearAllMemoryLocations(), CppPTSLClient::ClearMemoryLocation(), CppPTSLClient::CreateFade(), CppPTSLClient::CreateFadesBasedOnPreset(), CppPTSLClient::ExtendSelectionToTargetTracks(), DefaultRequestHandler::OnHasError(), CppPTSLClient::RefreshTargetAudioFiles(), and CppPTSLClient::SelectAllClipsOnTrack().
Variable Documentation
sTmpEmptyMessage
ptsl::EmptyMessage sTmpEmptyMessage = ptsl::EmptyMessage() [static]
PING_TIMEOUT
const int32_t PING_TIMEOUT = 5000