ptslcmd.cpp File Reference
#include <gtest/gtest.h>
#include <iostream>
#include <map>
#include <string>
#include <unordered_map>
#include <vector>
#include `CommandLineParser.h`
#include `Constants.h`
#include `PrintHelpHelpers.h`
#include `PtslCmdCommandRequest.h`
#include `PtslCmdCommandResult.h`
#include `PtslCmdCommandRunner.h`
#include `PTSLC_CPP/CppPTSLClient.h`
#include `PTSLC_CPP/CppPTSLCommonConversions.h`
Description
C++ PTSL client test application.
This application is used internally in Avid to test the PTSL Scripting SDK. You can use the application at your own risk to send Pro Tools commands without creating your own program. However, we can't guarantee that it won't be changed or removed in the future.
Please see usage information by running:
ptslcmd -help
Macros
#define NO_RESULT 0
#define RESET `\033[0m`
#define ORANGE `\033[38;5;214m`
#define BLUE `\033[38;5;33m`
Typedefs
using TaskQueue = vector< shared_ptr< CppPTSLResponse > >
Functions
static void PrintPtslCommandResults (const vector< PtslCmdCommandStreamResult > &cmdStreamResults)
static bool PrintHelpIfRequired (bool hasHelpParam, bool hasListParam, bool hasNoArgs)
int main (int argc, char *argv[])
TEST (Client, Result)
Variables
static TaskQueue s_CompletionTasksQueue
Macro Definition Documentation
NO_RESULT
#define NO_RESULT 0
RESET
#define RESET `\033[0m`
ORANGE
#define ORANGE `\033[38;5;214m`
BLUE
#define BLUE `\033[38;5;33m`
Typedef Documentation
TaskQueue
using TaskQueue = vector<shared_ptr<CppPTSLResponse> >
Function Documentation
PrintPtslCommandResults()
void PrintPtslCommandResults (const vector< PtslCmdCommandStreamResult > & cmdStreamResults) [static]
Referenced by main().
PrintHelpIfRequired()
bool PrintHelpIfRequired (bool hasHelpParam, bool hasListParam, bool hasNoArgs) [static]
References PrintHelpHelpers::PrintCommandListHelp(), and PrintHelpHelpers::PrintHelp().
Referenced by main().
main()
int main (int argc, char * argv[])
References Constants::ENCRYPTION_KEY_ARG, Constants::FILE_CMD_ARG, Constants::HELP_CMD_ARG, Constants::JSON_HEADER_CMD_ARG, Constants::JSON_REQUEST_CMD_ARG, Constants::LIST_CMD_ARG, NO_RESULT, CppPTSLClient::OnResponseReceived, Constants::PARAMETERLESS_ARGS_KEY, PrintHelpIfRequired(), PrintPtslCommandResults(), PtslCmdCommandRunner::RunCommand(), PtslCmdCommandRunner::RunFileScript(), s_CompletionTasksQueue, and Constants::SESSION_ID_CMD_ARG.
TEST()
TEST (Client , Result)
References BLUE, ptsl::Completed, ptsl::CompletedWithBadResponse, PTSLC_CPP::EnumToString(), ptsl::Failed, ptsl::FailedWithBadErrorResponse, ptsl::GetTaskStatus, ptsl::HostReadyCheck, ORANGE, RESET, and s_CompletionTasksQueue.
Variable Documentation
s_CompletionTasksQueue
TaskQueue s_CompletionTasksQueue [static]
Referenced by main(), and TEST().