DefaultRequestHandler
#include <CppPTSLC_DefaultRequest.h>
Description
Common request handler for processing specific grpc requests and responses.
Deprecated
Deprecated Deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead of using request handlers.
Classes
struct State
Public Member Functions
DefaultRequestHandler ()
virtual ~DefaultRequestHandler ()
bool ConvertRequestBodyToJson (std::string &requestBodyJSON)
std::tuple< bool, std::string > ConvertJsonToResponseBody (const std::string &responseBodyJSON)
std::tuple< bool, std::string > ConvertJsonToResponseError (const std::string &errorJSON)
void ConvertProtoToCommandError (const ptsl::CommandError &in, CommandError &out)
virtual void OnNextResponse ()
virtual void OnHasBody ()
virtual void OnNoBody ()
virtual bool IsResponseReceived () const
virtual void OnHasHeader (const ptsl::Response &response)
virtual void OnHasError ()
virtual void OnNoResponse (CommandId command)
virtual void SetResponseStatus (const TaskStatus &status, const std::string &statusTypeClarification=``)
virtual TaskStatus GetResponseStatus () const
virtual bool IsNeedToPingTaskStatus () const
virtual std::string GetRequestName () const =0
virtual void CreateState ()
virtual void MakeResponse ()
virtual std::shared_ptr< CommandResponse > GetResponse () const
Protected Member Functions
virtual google::protobuf::Message & GetRequestBodyRef ()
virtual google::protobuf::Message & GetResponseBodyRef ()
Protected Attributes
ptsl::ResponseError mGrpcResponseError
std::shared_ptr< State > mState
std::shared_ptr< CommandResponse > mResponse
Constructor & Destructor Documentation
DefaultRequestHandler()
DefaultRequestHandler () [inline]
 DefaultRequestHandler()
virtual ~DefaultRequestHandler () [inline], [virtual]
Member Function Documentation
ConvertRequestBodyToJson()
bool ConvertRequestBodyToJson (std::string & requestBodyJSON) [inline]
References PTSLC_CPP::DefaultJsonWriteOptions().
ConvertJsonToResponseBody()
std::tuple< bool, std::string > ConvertJsonToResponseBody (const std::string & responseBodyJSON) [inline]
References PTSLC_CPP::DefaultJsonParseOptions().
ConvertJsonToResponseError()
std::tuple< bool, std::string > ConvertJsonToResponseError (const std::string & errorJSON) [inline]
References PTSLC_CPP::DefaultJsonParseOptions().
ConvertProtoToCommandError()
void ConvertProtoToCommandError (const ptsl::CommandError & in, CommandError & out) [inline]
References CommandError::command_error_message, CommandError::command_error_type, CommandError::errorMessage, CommandError::errorType, CommandError::is_warning, and CommandError::isWarning.
OnNextResponse()
virtual void OnNextResponse () [inline], [virtual]
OnHasBody()
virtual void OnHasBody () [inline], [virtual]
OnNoBody()
virtual void OnNoBody () [inline], [virtual]
IsResponseReceived()
virtual bool IsResponseReceived () const [inline], [virtual]
OnHasHeader()
virtual void OnHasHeader (const ptsl::Response & response) [inline], [virtual]
References ResponseHeader::command, Response::header, ResponseHeader::progress, Response::response_body_json, Response::response_error_json, ResponseHeader::status, ResponseHeader::task_id, ResponseHeader::version, ResponseHeader::version_minor, and ResponseHeader::version_revision.
OnHasError()
virtual void OnHasError () [inline], [virtual]
References PTSLC_CPP::ConvertProtoToCommandError().
OnNoResponse()
virtual void OnNoResponse (CommandId command) [inline], [virtual]
References PTSLC_CPP::TStatus_NoResponseReceived.
SetResponseStatus()
virtual void SetResponseStatus (const TaskStatus & status, const std::string & statusTypeClarification = ``) [inline], [virtual]
GetResponseStatus()
virtual TaskStatus GetResponseStatus () const [inline], [virtual]
References PTSLC_CPP::TStatus_NoResponseReceived.
IsNeedToPingTaskStatus()
virtual bool IsNeedToPingTaskStatus () const [inline], [virtual]
GetRequestName()
virtual std::string GetRequestName () const [pure virtual]
CreateState()
virtual void CreateState () [inline], [virtual]
MakeResponse()
virtual void MakeResponse () [inline], [virtual]
GetResponse()
virtual std::shared_ptr< CommandResponse > GetResponse () const [inline], [virtual]
GetRequestBodyRef()
virtual google::protobuf::Message & GetRequestBodyRef () [inline], [protected], [virtual]
GetResponseBodyRef()
virtual google::protobuf::Message & GetResponseBodyRef () [inline], [protected], [virtual]
Member Data Documentation
mGrpcResponseError
ptsl::ResponseError mGrpcResponseError [protected]
mState
std::shared_ptr<State> mState [protected]
mResponse
std::shared_ptr<CommandResponse> mResponse [protected]
The documentation for this struct was generated from the following files:
CppPTSLC_DefaultRequest.h
CppPTSLC_DefaultRequest.cpp