CppPTSLClient
#include <CppPTSLClient.h>
Description
Async C++ client wrapper for handling gRPC async streaming requests and receiving responses.
Classes
struct InternalData
CppPTSLClient data which can't be used in public headers.
Public Member Functions
CppPTSLClient (const ClientConfig &config)
Client constructor.
virtual ~CppPTSLClient ()
Client destructor.
virtual bool LaunchProTools ()
Launches the Pro Tools application.
void MakeRequest (std::shared_ptr< DefaultRequestHandler > handler, CommandId commandType)
Internal common method for handling different types of requests and responses.
void MakeStreamingRequest (std::shared_ptr< DefaultRequestHandler > handler, CommandId commandType)
Internal common method for handling different types of requests and responses via grpc async streaming.
std::string GetSessionId () const
Returns the id of the established session.
void SetSessionId (const std::string &sessionId)
Sets the session id manually if the session was already established before with RegisterConnection.
std::future< CppPTSLResponse > SendRequest (CppPTSLRequest request, std::function< void(const CppPTSLResponse &)> responseCallback=nullptr)
Sends a JSON-based request to Pro Tools.
void CancelRequests (bool waitForCancel=true)
Cancels all requests that are currently in progress.
virtual std::shared_ptr< GetTaskStatusResponse > GetTaskStatus (const GetTaskStatusRequest &request)
virtual std::shared_ptr< CommandResponse > CreateSession (const CreateSessionRequest &request)
virtual std::shared_ptr< CommandResponse > OpenSession (const OpenSessionRequest &request)
virtual std::shared_ptr< ImportResponse > Import (const ImportRequest &request)
virtual std::shared_ptr< GetTrackListResponse > GetTrackList (const GetTrackListRequest &request)
virtual std::shared_ptr< CommandResponse > SelectAllClipsOnTrack (const SelectAllClipsOnTrackRequest &request)
virtual std::shared_ptr< CommandResponse > ExtendSelectionToTargetTracks (const ExtendSelectionToTargetTracksRequest &request)
virtual std::shared_ptr< CommandResponse > TrimToSelection (const CommandRequest &request)
virtual std::shared_ptr< CommandResponse > CreateFade (const CreateFadesBasedOnPresetRequest &request)
virtual std::shared_ptr< CommandResponse > RenameTrack (const RenameTargetTrackRequest &request)
virtual std::shared_ptr< CommandResponse > ConsolidateClip (const CommandRequest &request)
virtual std::shared_ptr< CommandResponse > ExportClipsAsFiles (const ExportClipsAsFilesRequest &request)
virtual std::shared_ptr< CommandResponse > ExportSelectedTracksAsAAFOMF (const ExportSelectedTracksAsAAFOMFRequest &request)
virtual std::shared_ptr< RefreshTargetAudioFilesResponse > RefreshTargetAudioFiles (const RefreshTargetAudioFilesRequest &request)
virtual std::shared_ptr< CommandResponse > RefreshAllModifiedAudioFiles (const CommandRequest &request)
virtual std::shared_ptr< GetFileLocationResponse > GetFileLocation (const GetFileLocationRequest &request)
virtual std::shared_ptr< CommandResponse > CloseSession (const CloseSessionRequest &request)
virtual std::shared_ptr< CommandResponse > SaveSession (const CommandRequest &request)
virtual std::shared_ptr< CommandResponse > SaveSessionAs (const SaveSessionAsRequest &request)
virtual std::shared_ptr< CommandResponse > Cut (const CommandRequest &request)
virtual std::shared_ptr< CommandResponse > Copy (const CommandRequest &request)
virtual std::shared_ptr< CommandResponse > Paste (const CommandRequest &request)
virtual std::shared_ptr< CommandResponse > Clear (const CommandRequest &request)
virtual std::shared_ptr< CommandResponse > CutSpecial (const CutSpecialRequest &request)
virtual std::shared_ptr< CommandResponse > CopySpecial (const CopySpecialRequest &request)
virtual std::shared_ptr< CommandResponse > ClearSpecial (const ClearSpecialRequest &request)
virtual std::shared_ptr< CommandResponse > PasteSpecial (const PasteSpecialRequest &request)
virtual std::shared_ptr< GetEditModeResponse > GetEditMode (const CommandRequest &request)
virtual std::shared_ptr< CommandResponse > SetEditMode (const SetEditModeRequest &request)
virtual std::shared_ptr< GetEditToolResponse > GetEditTool (const CommandRequest &request)
virtual std::shared_ptr< CommandResponse > SetEditTool (const SetEditToolRequest &request)
virtual std::shared_ptr< CommandResponse > RecallZoomPreset (const RecallZoomPresetRequest &request)
virtual std::shared_ptr< GetEditModeOptionsResponse > GetEditModeOptions (const CommandRequest &request)
virtual std::shared_ptr< CommandResponse > SetEditModeOptions (const SetEditModeOptionsRequest &request)
virtual std::shared_ptr< CommandResponse > ExportMix (const ExportMixRequest &request)
Render all or part of the session to one or more files.
virtual std::shared_ptr< GetDynamicPropertiesResponse > GetDynamicProperties (const GetDynamicPropertiesRequest &request)
virtual std::shared_ptr< CommandResponse > Spot (const SpotRequest &request)
virtual std::shared_ptr< ExportSessionInfoAsTextResponse > ExportSessionInfoAsText (const ExportSessionInfoAsTextRequest &request)
virtual std::shared_ptr< SetPlaybackModeResponse > SetPlaybackMode (const SetPlaybackModeRequest &request)
virtual std::shared_ptr< SetRecordModeResponse > SetRecordMode (const SetRecordModeRequest &request)
virtual std::shared_ptr< GetSessionAudioFormatResponse > GetSessionAudioFormat (const CommandRequest &request)
virtual std::shared_ptr< GetSessionSampleRateResponse > GetSessionSampleRate (const CommandRequest &request)
virtual std::shared_ptr< GetSessionBitDepthResponse > GetSessionBitDepth (const CommandRequest &request)
virtual std::shared_ptr< GetSessionInterleavedStateResponse > GetSessionInterleavedState (const CommandRequest &request)
virtual std::shared_ptr< GetSessionTimeCodeRateResponse > GetSessionTimeCodeRate (const CommandRequest &request)
virtual std::shared_ptr< GetSessionFeetFramesRateResponse > GetSessionFeetFramesRate (const CommandRequest &request)
virtual std::shared_ptr< GetSessionAudioRatePullSettingsResponse > GetSessionAudioRatePullSettings (const CommandRequest &request)
virtual std::shared_ptr< GetSessionVideoRatePullSettingsResponse > GetSessionVideoRatePullSettings (const CommandRequest &request)
virtual std::shared_ptr< GetSessionNameResponse > GetSessionName (const CommandRequest &request)
virtual std::shared_ptr< GetSessionPathResponse > GetSessionPath (const CommandRequest &request)
virtual std::shared_ptr< GetSessionStartTimeResponse > GetSessionStartTime (const CommandRequest &request)
virtual std::shared_ptr< GetSessionLengthResponse > GetSessionLength (const CommandRequest &request)
virtual std::shared_ptr< CommandResponse > SetSessionAudioFormat (const SetSessionAudioFormatRequest &request)
virtual std::shared_ptr< CommandResponse > SetSessionBitDepth (const SetSessionBitDepthRequest &request)
virtual std::shared_ptr< CommandResponse > SetSessionInterleavedState (const SetSessionInterleavedStateRequest &request)
virtual std::shared_ptr< CommandResponse > SetSessionTimeCodeRate (const SetSessionTimeCodeRateRequest &request)
virtual std::shared_ptr< CommandResponse > SetSessionFeetFramesRate (const SetSessionFeetFramesRateRequest &request)
virtual std::shared_ptr< CommandResponse > SetSessionAudioRatePullSettings (const SetSessionAudioRatePullSettingsRequest &request)
virtual std::shared_ptr< CommandResponse > SetSessionVideoRatePullSettings (const SetSessionVideoRatePullSettingsRequest &request)
virtual std::shared_ptr< CommandResponse > SetSessionStartTime (const SetSessionStartTimeRequest &request)
virtual std::shared_ptr< CommandResponse > SetSessionLength (const SetSessionLengthRequest &request)
virtual std::shared_ptr< GetPTSLVersionResponse > GetPTSLVersion (const GetPTSLVersionRequest &request)
virtual std::shared_ptr< GetPlaybackModeResponse > GetPlaybackMode (const CommandRequest &request)
virtual std::shared_ptr< GetRecordModeResponse > GetRecordMode (const CommandRequest &request)
virtual std::shared_ptr< GetTransportArmedResponse > GetTransportArmed (const CommandRequest &request)
virtual std::shared_ptr< GetTransportStateResponse > GetTransportState (const CommandRequest &request)
virtual std::shared_ptr< ClearMemoryLocationResponse > ClearMemoryLocation (const ClearMemoryLocationRequest &request)
virtual std::shared_ptr< CommandResponse > RenameSelectedClip (const RenameSelectedClipRequest &request)
virtual std::shared_ptr< CommandResponse > RenameTargetClip (const RenameTargetClipRequest &request)
virtual std::shared_ptr< CommandResponse > TogglePlayState (const CommandRequest &request)
virtual std::shared_ptr< CommandResponse > ToggleRecordEnable (const CommandRequest &request)
virtual std::shared_ptr< CommandResponse > PlayHalfSpeed (const CommandRequest &request)
virtual std::shared_ptr< CommandResponse > RecordHalfSpeed (const CommandRequest &request)
virtual std::shared_ptr< CommandResponse > EditMemoryLocation (const EditMemoryLocationRequest &request)
virtual std::shared_ptr< CommandResponse > CreateMemoryLocation (const CreateMemoryLocationRequest &request)
virtual std::shared_ptr< GetMemoryLocationsResponse > GetMemoryLocations (const GetMemoryLocationsRequest &request)
virtual std::shared_ptr< RegisterConnectionResponse > RegisterConnection (const RegisterConnectionRequest &request)
virtual std::shared_ptr< CommandResponse > CreateFadesBasedOnPreset (const CreateFadesBasedOnPresetRequest &request)
virtual std::shared_ptr< CommandResponse > RenameTargetTrack (const RenameTargetTrackRequest &request)
virtual std::shared_ptr< CreateNewTracksResponse > CreateNewTracks (const CreateNewTracksRequest &request)
virtual std::shared_ptr< CommandResponse > SetTimelineSelection (const SetTimelineSelectionRequest &request)
virtual std::shared_ptr< GetTimelineSelectionResponse > GetTimelineSelection (const GetTimelineSelectionRequest &request)
virtual std::shared_ptr< SelectTracksByNameResponse > SelectTracksByName (const SelectTracksByNameRequest &request)
virtual std::shared_ptr< ImportVideoResponse > ImportVideo (const ImportVideoRequest &request)
virtual std::shared_ptr< CommandResponse > SelectMemoryLocation (const SelectMemoryLocationRequest &request)
virtual std::shared_ptr< CommandResponse > SetTrackMuteState (const SetTrackMuteStateRequest &request)
virtual std::shared_ptr< CommandResponse > SetTrackSoloState (const SetTrackSoloStateRequest &request)
virtual std::shared_ptr< CommandResponse > SetTrackSoloSafeState (const SetTrackSoloSafeStateRequest &request)
virtual std::shared_ptr< CommandResponse > SetTrackRecordEnableState (const SetTrackRecordEnableStateRequest &request)
virtual std::shared_ptr< CommandResponse > SetTrackRecordSafeEnableState (const SetTrackRecordSafeEnableStateRequest &request)
virtual std::shared_ptr< CommandResponse > SetTrackInputMonitorState (const SetTrackInputMonitorStateRequest &request)
virtual std::shared_ptr< CommandResponse > SetTrackSmartDspState (const SetTrackSmartDspStateRequest &request)
virtual std::shared_ptr< CommandResponse > SetTrackHiddenState (const SetTrackHiddenStateRequest &request)
virtual std::shared_ptr< CommandResponse > SetTrackInactiveState (const SetTrackInactiveStateRequest &request)
virtual std::shared_ptr< CommandResponse > SetTrackFrozenState (const SetTrackFrozenStateRequest &request)
virtual std::shared_ptr< CommandResponse > SetTrackOnlineState (const SetTrackOnlineStateRequest &request)
virtual std::shared_ptr< CommandResponse > SetTrackOpenState (const SetTrackOpenStateRequest &request)
virtual std::shared_ptr< GetSessionIDsResponse > GetSessionIDs (const CommandRequest &request)
virtual std::shared_ptr< GetMemoryLocationsManageModeResponse > GetMemoryLocationsManageMode (const CommandRequest &request)
virtual std::shared_ptr< CommandResponse > SetMemoryLocationsManageMode (const SetMemoryLocationsManageModeRequest &request)
virtual std::shared_ptr< CommandResponse > SetMainCounterFormat (const SetMainCounterFormatRequest &request)
virtual std::shared_ptr< CommandResponse > SetSubCounterFormat (const SetSubCounterFormatRequest &request)
virtual std::shared_ptr< GetMainCounterFormatResponse > GetMainCounterFormat (const CommandRequest &request)
virtual std::shared_ptr< GetSubCounterFormatResponse > GetSubCounterFormat (const CommandRequest &request)
virtual std::shared_ptr< UndoResponse > Undo (const UndoRequest &request)
virtual std::shared_ptr< RedoResponse > Redo (const RedoRequest &request)
virtual std::shared_ptr< UndoAllResponse > UndoAll (const CommandRequest &request)
virtual std::shared_ptr< RedoAllResponse > RedoAll (const CommandRequest &request)
virtual std::shared_ptr< CommandResponse > ClearUndoQueue (const CommandRequest &request)
virtual std::shared_ptr< CommandResponse > SetTrackDSPModeSafeState (const SetTrackDSPModeSafeStateRequest &request)
virtual std::shared_ptr< GetSessionSystemDelayInfoResponse > GetSessionSystemDelayInfo (const CommandRequest &request)
virtual std::shared_ptr< CommandResponse > GroupClips (const CommandRequest &request)
virtual std::shared_ptr< CommandResponse > UngroupClips (const CommandRequest &request)
virtual std::shared_ptr< CommandResponse > UngroupAllClips (const CommandRequest &request)
virtual std::shared_ptr< CommandResponse > RegroupClips (const CommandRequest &request)
virtual std::shared_ptr< HostReadyCheckResponse > HostReadyCheck (const CommandRequest &request)
Checks to see if the Pro Tools application is fully loaded and ready to execute PTSL commands.
virtual std::shared_ptr< CommandResponse > RepeatSelection (const RepeatSelectionRequest &request)
virtual std::shared_ptr< CommandResponse > DuplicateSelection (const CommandRequest &request)
virtual std::shared_ptr< ClearAllMemoryLocationsResponse > ClearAllMemoryLocations (const CommandRequest &request)
Clears all the memory locations in the session.
Public Attributes
std::function< void(std::shared_ptr< CppPTSLResponse >)> OnResponseReceived
Client's callback event for returning responses on requests.
std::function< void(std::shared_ptr< CommandResponse >)> OnResponseReceived_V1_Deprecated
Client's callback event for returning responses on requests.
Protected Member Functions
void Init ()
Used for initialization client, starting PT and host (if required) and checking if host ready.
void Free ()
Used to free up client resources.
void HostReadyCheck ()
Internal client wrapper utility function called by the constructor, PTSLC_CPP::CppPTSLClient::CppPTSLClient and checks to see if the Pro Tools application is ready to execute PTSL commands.
Constructor & Destructor Documentation
CppPTSLClient()
CppPTSLClient (const ClientConfig & config) [explicit]
Client constructor.
Used for initialization of gRPC Client and client's config.
References ClientConfig::address, and CppPTSLClient::Init().
 CppPTSLClient()
~CppPTSLClient () [virtual]
Client destructor.
References CppPTSLClient::CancelRequests(), and CppPTSLClient::Free().
Member Function Documentation
LaunchProTools()
bool LaunchProTools () [virtual]
Launches the Pro Tools application.
Launches Pro Tools application.
Referenced by CppPTSLClient::Init().
MakeRequest()
void MakeRequest (std::shared_ptr< DefaultRequestHandler > handler, CommandId commandType)
Internal common method for handling different types of requests and responses.
Deprecated
Deprecated MakeRequest is deprecated starting in Pro Tools 2024.10. Replaced with SendRequest
References PTSLC_CPP::CId_HostReadyCheck, CppPTSLClient::OnResponseReceived_V1_Deprecated, PTSLC_CPP::SDK_Error, PTSLC_CPP::TStatus_CompletedWithBadResponse, PTSLC_CPP::TStatus_Failed, and PTSLC_CPP::TStatus_FailedWithBadErrorResponse.
MakeStreamingRequest()
void MakeStreamingRequest (std::shared_ptr< DefaultRequestHandler > handler, CommandId commandType)
Internal common method for handling different types of requests and responses via grpc async streaming.
Internal common method for handling different types of requests and responses.
Deprecated
Deprecated MakeStreamingRequest is deprecated starting in Pro Tools 2024.10. Replaced with SendRequest
References PTSLC_CPP::CId_HostReadyCheck, PTSLC_CPP::IsCancellationRequested(), CppPTSLClient::OnResponseReceived_V1_Deprecated, PTSLC_CPP::SDK_Error, PTSLC_CPP::TStatus_Completed, PTSLC_CPP::TStatus_CompletedWithBadResponse, PTSLC_CPP::TStatus_Failed, PTSLC_CPP::TStatus_FailedWithBadErrorResponse, and PTSLC_CPP::TStatus_Queued.
Referenced by CppPTSLClient::RegisterConnection().
GetSessionId()
std::string GetSessionId () const
Returns the id of the established session.
Referenced by CppPTSLClient::SendRequest().
SetSessionId()
void SetSessionId (const std::string & sessionId)
Sets the session id manually if the session was already established before with RegisterConnection.
Referenced by CppPTSLClient::SendRequest().
SendRequest()
std::future< CppPTSLResponse > SendRequest (CppPTSLRequest request, std::function< void(const CppPTSLResponse &)> responseCallback = nullptr)
Sends a JSON-based request to Pro Tools.
responseCallback provides an ability to process all respones (both intermediate and final) in realtime. The callback is called from the service thread.
References PTSLC_CPP::CEType_SDK_GrpcGeneric, PTSLC_CPP::CEType_SDK_SessionIdParseError, ResponseHeader::command, ptsl::Failed, CppPTSLRequest::GetCommandId(), CppPTSLRequest::GetRequestBodyJson(), CppPTSLClient::GetSessionId(), CppPTSLRequest::GetSessionId(), CppPTSLRequest::GetVersion(), CppPTSLRequest::GetVersionedRequestHeaderJson(), CppPTSLRequest::GetVersionMinor(), CppPTSLRequest::GetVersionRevision(), Response::header, PTSLC_CPP::HostReadyCheck, CppPTSLClient::OnResponseReceived, ResponseHeader::progress, PTSL_VERSION_MAJOR, PTSL_VERSION_MINOR, PTSL_VERSION_REVISION, PTSLC_CPP::RegisterConnection, Response::response_body_json, Response::response_error_json, CppPTSLClient::SetSessionId(), CppPTSLResponse::SetStatus(), ResponseHeader::status, ResponseHeader::task_id, ResponseHeader::version, ResponseHeader::version_minor, ResponseHeader::version_revision, and ResponseHeader::versioned_response_header_json.
Referenced by CppPTSLClient::HostReadyCheck(), and PtslCmdCommandRunner::RunCommand().
CancelRequests()
void CancelRequests (bool waitForCancel = true)
Cancels all requests that are currently in progress.
Referenced by CppPTSLClient::~CppPTSLClient().
GetTaskStatus()
std::shared_ptr< GetTaskStatusResponse > GetTaskStatus (const GetTaskStatusRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get task execution status
Only returns the status of the task that is currently in progress. So it should be called asynchronously in parallel to the requested PTSL Command like it is implemented in PTSLC_CPP::CppPTSLClient::PingTaskStatus.
Returns
task execution status
References CppPTSLClient::GetTaskStatus(), INIT_HNDLR_OVRD, MAKE_REQUEST, MAKE_RESP_OVRD, and GetTaskStatusRequest::requestedTaskId.
Referenced by CppPTSLClient::GetTaskStatus().
CreateSession()
std::shared_ptr< CommandResponse > CreateSession (const CreateSessionRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Create a new Pro Tools session
Returns
task execution status
References CreateSessionRequest::bitDepth, CreateSessionRequest::createFromAAF, CreateSessionRequest::createFromTemplate, CppPTSLClient::CreateSession(), CreateSessionRequest::fileType, INIT_HNDLR_OVRD, CreateSessionRequest::inputOutputSettings, CreateSessionRequest::isCloudProject, CreateSessionRequest::isInterleaved, MAKE_REQUEST, CreateSessionRequest::pathToAAF, CreateSessionRequest::sampleRate, CreateSessionRequest::sessionLocation, CreateSessionRequest::sessionName, CreateSessionRequest::templateGroup, and CreateSessionRequest::templateName.
Referenced by CppPTSLClient::CreateSession().
OpenSession()
std::shared_ptr< CommandResponse > OpenSession (const OpenSessionRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Open a Pro Tools session
Returns
task execution status
References INIT_HNDLR_OVRD, MAKE_REQUEST, CppPTSLClient::OpenSession(), and OpenSessionRequest::sessionPath.
Referenced by CppPTSLClient::OpenSession().
Import()
std::shared_ptr< ImportResponse > Import (const ImportRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Import existing Pro Tools session
Returns
task execution status
References ImportRequest::adjustSessionStartTimeToMatchSource, ImportRequest::audioData, ImportRequest::audioHandleSize, AudioData::audioOperations, ImportRequest::audioOptions, ImportRequest::clipGain, ImportRequest::clipsAndMedia, AudioData::destination, AudioData::destinationPath, AudioData::filesList, CppPTSLClient::Import(), ImportRequest::importType, INIT_HNDLR_OVRD, ptsl::IType_Audio, AudioData::location, ImportRequest::locationOptions, ImportRequest::locationType, ImportRequest::locationValue, MAKE_REQUEST, MAKE_RESP_OVRD, ImportRequest::matchOptions, ImportRequest::playlistOptions, ImportRequest::sessionPath, ImportRequest::timeCodeMappingStartTime, ImportRequest::timeCodeMappingUnits, ImportRequest::trackDataPresetPath, ImportRequest::videoOptions, and ImportRequest::volumeAutomation.
Referenced by CppPTSLClient::Import().
GetTrackList()
std::shared_ptr< GetTrackListResponse > GetTrackList (const GetTrackListRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get list of tracks from session
Returns
track list and task execution status
References Track::color, TrackAttributes::contains_automation, TrackAttributes::contains_clips, TrackAttributes::containsAutomation, TrackAttributes::containsClips, Track::format, CppPTSLClient::GetTrackList(), Track::id, Track::id_compressed, Track::index, INIT_HNDLR_OVRD, TrackAttributes::is_frozen, TrackAttributes::is_hidden, TrackAttributes::is_inactive, TrackAttributes::is_input_monitoring_on, TrackAttributes::is_locked, TrackAttributes::is_muted, TrackAttributes::is_online, TrackAttributes::is_open, TrackAttributes::is_record_enabled, TrackAttributes::is_record_enabled_safe, TrackAttributes::is_selected, TrackAttributes::is_smart_dsp_on, TrackAttributes::is_smart_dsp_on_safe, TrackAttributes::is_soloed, TrackAttributes::is_soloed_safe, GetTrackListRequest::isFilterListAdditive, TrackAttributes::isFrozen, TrackAttributes::isHidden, TrackAttributes::isInactive, TrackAttributes::isInputMonitoringOn, TrackAttributes::isLocked, TrackAttributes::isMuted, TrackAttributes::isOnline, TrackAttributes::isOpen, TrackAttributes::isRecordEnabled, TrackAttributes::isRecordEnabledSafe, TrackAttributes::isSelected, TrackAttributes::isSmartDspOn, TrackAttributes::isSmartDspOnSafe, TrackAttributes::isSoloed, TrackAttributes::isSoloedSafe, PaginationRequest::limit, MAKE_REQUEST, MAKE_RESP_OVRD, Track::name, PaginationRequest::offset, GetTrackListRequest::paginationRequest, Track::parent_folder_id, Track::parent_folder_name, Track::timebase, Track::track_attributes, GetTrackListRequest::trackFilters, and Track::type.
Referenced by CppPTSLClient::GetTrackList().
SelectAllClipsOnTrack()
std::shared_ptr< CommandResponse > SelectAllClipsOnTrack (const SelectAllClipsOnTrackRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Select all clips on the selected track
Returns
task execution status
References PTSLC_CPP::ConvertProtoToCommandError(), INIT_HNDLR_OVRD, MAKE_REQUEST, CppPTSLClient::SelectAllClipsOnTrack(), and SelectAllClipsOnTrackRequest::trackName.
Referenced by CppPTSLClient::SelectAllClipsOnTrack().
ExtendSelectionToTargetTracks()
std::shared_ptr< CommandResponse > ExtendSelectionToTargetTracks (const ExtendSelectionToTargetTracksRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Extend selection to target tracks
Returns
track list and task execution status
References PTSLC_CPP::ConvertProtoToCommandError(), CppPTSLClient::ExtendSelectionToTargetTracks(), INIT_HNDLR_OVRD, MAKE_REQUEST, and ExtendSelectionToTargetTracksRequest::tracksToExtendTo.
Referenced by CppPTSLClient::ExtendSelectionToTargetTracks().
TrimToSelection()
std::shared_ptr< CommandResponse > TrimToSelection (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Trim clips to selection
Returns
task execution status
References INIT_HNDLR, MAKE_REQUEST, and CppPTSLClient::TrimToSelection().
Referenced by CppPTSLClient::TrimToSelection().
CreateFade()
std::shared_ptr< CommandResponse > CreateFade (const CreateFadesBasedOnPresetRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Create fades on clips from specified preset
Deprecated
Deprecated CreateFade is deprecated starting in Pro Tools 2023.09. Replaced with CreateFadesBasedOnPreset
Returns
task execution status
References CreateFadesBasedOnPresetRequest::autoAdjustBounds, PTSLC_CPP::ConvertProtoToCommandError(), CppPTSLClient::CreateFadesBasedOnPreset(), CreateFadesBasedOnPresetRequest::fadePresetName, INIT_HNDLR_OVRD, and MAKE_REQUEST.
RenameTrack()
std::shared_ptr< CommandResponse > RenameTrack (const RenameTargetTrackRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Rename selected track
Deprecated
Deprecated RenameTrack is deprecated starting in Pro Tools 2023.09. Replaced with RenameTargetTrack
Returns
task execution status
References RenameTargetTrackRequest::currentTrackName, INIT_HNDLR_OVRD, MAKE_REQUEST, RenameTargetTrackRequest::newTrackName, CppPTSLClient::RenameTargetTrack(), and RenameTargetTrackRequest::trackId.
ConsolidateClip()
std::shared_ptr< CommandResponse > ConsolidateClip (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Consolidate selected clips
Returns
task execution status
References CppPTSLClient::ConsolidateClip(), INIT_HNDLR, and MAKE_REQUEST.
Referenced by CppPTSLClient::ConsolidateClip().
ExportClipsAsFiles()
std::shared_ptr< CommandResponse > ExportClipsAsFiles (const ExportClipsAsFilesRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Export selected clips as files
Returns
task execution status
References ExportClipsAsFilesRequest::bitDepth, ExportClipsAsFilesRequest::duplicateNames, ExportClipsAsFilesRequest::enforceAvidCompatibility, CppPTSLClient::ExportClipsAsFiles(), ExportClipsAsFilesRequest::filePath, ExportClipsAsFilesRequest::fileType, ExportClipsAsFilesRequest::format, INIT_HNDLR_OVRD, MAKE_REQUEST, and ExportClipsAsFilesRequest::sampleRateCustom.
Referenced by CppPTSLClient::ExportClipsAsFiles().
ExportSelectedTracksAsAAFOMF()
std::shared_ptr< CommandResponse > ExportSelectedTracksAsAAFOMF (const ExportSelectedTracksAsAAFOMFRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Export selected clips as AAF/OMF
Returns
task execution status
References ExportSelectedTracksAsAAFOMFRequest::assetFileLocation, ExportSelectedTracksAsAAFOMFRequest::bitDepth, ExportSelectedTracksAsAAFOMFRequest::comments, ExportSelectedTracksAsAAFOMFRequest::containerFileLocation, ExportSelectedTracksAsAAFOMFRequest::containerFileName, ExportSelectedTracksAsAAFOMFRequest::copyOption, ExportSelectedTracksAsAAFOMFRequest::enforceMediaComposerCompatibility, CppPTSLClient::ExportSelectedTracksAsAAFOMF(), ExportSelectedTracksAsAAFOMFRequest::exportStereoAsMultichannel, ExportSelectedTracksAsAAFOMFRequest::fileType, INIT_HNDLR_OVRD, MAKE_REQUEST, ExportSelectedTracksAsAAFOMFRequest::quantizeEditsToFrameBoundaries, and ExportSelectedTracksAsAAFOMFRequest::sequenceName.
Referenced by CppPTSLClient::ExportSelectedTracksAsAAFOMF().
RefreshTargetAudioFiles()
std::shared_ptr< RefreshTargetAudioFilesResponse > RefreshTargetAudioFiles (const RefreshTargetAudioFilesRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Force rescan the file list or force recalculate waveforms for the specific files
Returns
task execution status and count of successfully and unsuccessfully scanned files
References PTSLC_CPP::ConvertProtoToCommandError(), RefreshTargetAudioFilesRequest::filesList, INIT_HNDLR_OVRD, MAKE_REQUEST, MAKE_RESP_OVRD, and CppPTSLClient::RefreshTargetAudioFiles().
Referenced by CppPTSLClient::RefreshTargetAudioFiles().
RefreshAllModifiedAudioFiles()
std::shared_ptr< CommandResponse > RefreshAllModifiedAudioFiles (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Refresh modified files in the session
Returns
task execution status
References INIT_HNDLR, MAKE_REQUEST, and CppPTSLClient::RefreshAllModifiedAudioFiles().
Referenced by CppPTSLClient::RefreshAllModifiedAudioFiles().
GetFileLocation()
std::shared_ptr< GetFileLocationResponse > GetFileLocation (const GetFileLocationRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get an optionally filtered list of the media files referenced by the session.
Returns
task execution status
References GetFileLocationRequest::fileFilters, CppPTSLClient::GetFileLocation(), INIT_HNDLR_OVRD, PaginationRequest::limit, MAKE_REQUEST, MAKE_RESP_OVRD, PaginationRequest::offset, GetFileLocationRequest::paginationRequest, and FileLocation::path.
Referenced by CppPTSLClient::GetFileLocation().
CloseSession()
std::shared_ptr< CommandResponse > CloseSession (const CloseSessionRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Close a Pro Tools session
Returns
task execution status
References CppPTSLClient::CloseSession(), INIT_HNDLR_OVRD, MAKE_REQUEST, and CloseSessionRequest::saveOnClose.
Referenced by CppPTSLClient::CloseSession().
SaveSession()
std::shared_ptr< CommandResponse > SaveSession (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Save a Pro Tools session
Returns
task execution status
References INIT_HNDLR, MAKE_REQUEST, and CppPTSLClient::SaveSession().
Referenced by CppPTSLClient::SaveSession().
SaveSessionAs()
std::shared_ptr< CommandResponse > SaveSessionAs (const SaveSessionAsRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Save Pro Tools session as a new session
Returns
task execution status
References INIT_HNDLR_OVRD, MAKE_REQUEST, CppPTSLClient::SaveSessionAs(), SaveSessionAsRequest::sessionLocation, and SaveSessionAsRequest::sessionName.
Referenced by CppPTSLClient::SaveSessionAs().
Cut()
std::shared_ptr< CommandResponse > Cut (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Cut data on track
Returns
task execution status
References CppPTSLClient::Cut(), INIT_HNDLR, and MAKE_REQUEST.
Referenced by CppPTSLClient::Cut().
Copy()
std::shared_ptr< CommandResponse > Copy (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Copy data on track
Returns
task execution status
References CppPTSLClient::Copy(), INIT_HNDLR, and MAKE_REQUEST.
Referenced by CppPTSLClient::Copy().
Paste()
std::shared_ptr< CommandResponse > Paste (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Paste data on track
Returns
task execution status
References INIT_HNDLR, MAKE_REQUEST, and CppPTSLClient::Paste().
Referenced by CppPTSLClient::Paste().
Clear()
std::shared_ptr< CommandResponse > Clear (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Clear data on track
Returns
task execution status
References CppPTSLClient::Clear(), INIT_HNDLR, and MAKE_REQUEST.
Referenced by CppPTSLClient::Clear().
CutSpecial()
std::shared_ptr< CommandResponse > CutSpecial (const CutSpecialRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Cut data on track by filtering data type
Returns
task execution status
References CutSpecialRequest::automationDataOption, CppPTSLClient::CutSpecial(), INIT_HNDLR_OVRD, and MAKE_REQUEST.
Referenced by CppPTSLClient::CutSpecial().
CopySpecial()
std::shared_ptr< CommandResponse > CopySpecial (const CopySpecialRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Copy data on track by filtering data type
Returns
task execution status
References CopySpecialRequest::automationDataOption, CppPTSLClient::CopySpecial(), INIT_HNDLR_OVRD, and MAKE_REQUEST.
Referenced by CppPTSLClient::CopySpecial().
ClearSpecial()
std::shared_ptr< CommandResponse > ClearSpecial (const ClearSpecialRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Clear data on track by filtering data type
Returns
task execution status
References ClearSpecialRequest::automationDataOption, CppPTSLClient::ClearSpecial(), INIT_HNDLR_OVRD, and MAKE_REQUEST.
Referenced by CppPTSLClient::ClearSpecial().
PasteSpecial()
std::shared_ptr< CommandResponse > PasteSpecial (const PasteSpecialRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Pasting data on track by filtering data type
Returns
task execution status
References INIT_HNDLR_OVRD, MAKE_REQUEST, CppPTSLClient::PasteSpecial(), and PasteSpecialRequest::pasteSpecialOption.
Referenced by CppPTSLClient::PasteSpecial().
GetEditMode()
std::shared_ptr< GetEditModeResponse > GetEditMode (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get edit mode.
References CppPTSLClient::GetEditMode(), INIT_HNDLR, MAKE_REQUEST, and MAKE_RESP_OVRD.
Referenced by CppPTSLClient::GetEditMode().
SetEditMode()
std::shared_ptr< CommandResponse > SetEditMode (const SetEditModeRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set edit mode.
References SetEditModeRequest::editMode, INIT_HNDLR_OVRD, MAKE_REQUEST, and CppPTSLClient::SetEditMode().
Referenced by CppPTSLClient::SetEditMode().
GetEditTool()
std::shared_ptr< GetEditToolResponse > GetEditTool (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get current edit tool.
References CppPTSLClient::GetEditTool(), INIT_HNDLR, MAKE_REQUEST, and MAKE_RESP_OVRD.
Referenced by CppPTSLClient::GetEditTool().
SetEditTool()
std::shared_ptr< CommandResponse > SetEditTool (const SetEditToolRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set edit tool.
References SetEditToolRequest::editTool, INIT_HNDLR_OVRD, MAKE_REQUEST, and CppPTSLClient::SetEditTool().
Referenced by CppPTSLClient::SetEditTool().
RecallZoomPreset()
std::shared_ptr< CommandResponse > RecallZoomPreset (const RecallZoomPresetRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Recall zoom preset.
References INIT_HNDLR_OVRD, MAKE_REQUEST, CppPTSLClient::RecallZoomPreset(), and RecallZoomPresetRequest::zoomPreset.
Referenced by CppPTSLClient::RecallZoomPreset().
GetEditModeOptions()
std::shared_ptr< GetEditModeOptionsResponse > GetEditModeOptions (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get current edit mode options.
References EditModeOptions::automationFollowsEdit, CppPTSLClient::GetEditModeOptions(), INIT_HNDLR, EditModeOptions::insertionFollowsPlayback, EditModeOptions::layeredEditing, EditModeOptions::linkTimelineAndEditSelection, EditModeOptions::linkTrackAndEditSelection, MAKE_REQUEST, MAKE_RESP_OVRD, EditModeOptions::markersFollowEdit, EditModeOptions::mirroredMidiEditing, and EditModeOptions::tabToTransients.
Referenced by CppPTSLClient::GetEditModeOptions().
SetEditModeOptions()
std::shared_ptr< CommandResponse > SetEditModeOptions (const SetEditModeOptionsRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set edit mode options.
References EditModeOptions::automationFollowsEdit, SetEditModeOptionsRequest::editModeOptions, INIT_HNDLR_OVRD, EditModeOptions::insertionFollowsPlayback, EditModeOptions::layeredEditing, EditModeOptions::linkTimelineAndEditSelection, EditModeOptions::linkTrackAndEditSelection, MAKE_REQUEST, EditModeOptions::markersFollowEdit, EditModeOptions::mirroredMidiEditing, CppPTSLClient::SetEditModeOptions(), and EditModeOptions::tabToTransients.
Referenced by CppPTSLClient::SetEditModeOptions().
ExportMix()
std::shared_ptr< CommandResponse > ExportMix (const ExportMixRequest & request) [virtual]
Render all or part of the session to one or more files.
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Export Mix (Bounce Mix) can export an entire mix, including sub-mixes, to multiple file formats without having to create extra dedicated audio tracks in the session for bus recording. Different options and settings are available depending on the selected FileType. The options are organized in sections including Audio, Video, Location, and Dolby Atmos. Here's a breakdown of how the sections are used for each FileType:
WAV
has no Video section
has a unique field called DeliveryFormat (only shown if Interleaved is selected as the file format and there are multiple mix sources)
AIF
has no Video section
MP3
has no Video section
does not allow multiple mix sources
does not allow mix sources greater than 0
does not allow specifying Bit Depth value (always a 16Bit)
Sample Rate is limited to 48k and 44.1k
Import after Bounce is not available
MXF OPAtom
has no Video section
File format is multi-mono
Bit Depth is only 16Bit and 24Bit
Sample Rate is limited to 48k and 44.1k
Pad to frame boundary is hard-coded to ON
WAV (Dolby Atmos ADM BWF)
has no Audio section
has no Video section
has Dolby Atmos section (unique to this format)
has FFOA (bool) default to False
if FFOA is true then there's an option to enter TimeCode value
TimeCode value will match the session frame rate
Frame rate will always be 23.976 and 30 non-drop (if Frame rate is 60 -> it will still be 30)
has Embed Program-level Metadata
Returns
Task execution status
References ExportMixRequest::audioInfo, EM_AudioInfo::bitDepth, EM_ImportOptions::clearDestinationVideoTrackPlaylist, EM_VideoInfo::codecInfo, EM_CodecInfo::codecName, EM_AudioInfo::compressionType, EM_AudioInfo::deliveryFormat, EM_LocationInfo::directory, ExportMixRequest::dolbyAtmosInfo, PTSLC_CPP::EMFType_MP3, PTSLC_CPP::EMFType_MXFOPAtom, PTSLC_CPP::EMFType_WAVADM, EM_AudioInfo::exportFormat, CppPTSLClient::ExportMix(), EM_LocationInfo::fileDestination, ExportMixRequest::fileName, ExportMixRequest::filesList, ExportMixRequest::fileType, EM_DolbyAtmosInfo::firstFrameOfAction, EM_DolbyAtmosInfo::frameRate, EM_ImportOptions::gapsBetweenClips, EM_LocationInfo::importAfterBounce, EM_ImportOptions::importAudioFromFile, EM_ImportOptions::importDestination, EM_ImportOptions::importLocation, EM_LocationInfo::importOptions, EM_VideoInfo::includeVideo, INIT_HNDLR_OVRD, ExportMixRequest::locationInfo, MAKE_REQUEST, ExportMixRequest::mixSourceList, ExportMixRequest::offlineBounce, EM_AudioInfo::padToFrameBoundary, ExportMixRequest::presetPath, EM_CodecInfo::propertyList, EM_DolbyAtmosInfo::propertyList, EM_ImportOptions::removeExistingVideoClips, EM_ImportOptions::removeExistingVideoTracks, EM_VideoInfo::replaceTimeCodeTrack, EM_AudioInfo::sampleRate, EM_AudioInfo::sampleRateCustom, EM_DolbyAtmosInfo::timeCodeValue, EM_VideoInfo::videoExportOptions, and ExportMixRequest::videoInfo.
Referenced by CppPTSLClient::ExportMix().
GetDynamicProperties()
std::shared_ptr< GetDynamicPropertiesResponse > GetDynamicProperties (const GetDynamicPropertiesRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get dynamic properties from the host application
Use dynamic properties to query the application about its support for features such as codecs that are not directly bound to a particular version of the API or host application.
See also
DynamicPropertyType
References PropertyDescriptor::acceptedValues, PropertyDescriptor::description, CppPTSLClient::GetDynamicProperties(), INIT_HNDLR_OVRD, GetDynamicPropertiesGroup::keyList, MAKE_REQUEST, MAKE_RESP_OVRD, PropertyDescriptor::maxValue, PropertyDescriptor::minValue, PropertyDescriptor::name, PropertyContainer::name, PropertyDescriptor::objectType, GetDynamicPropertiesGroup::propertyList, GetDynamicPropertiesRequest::propertyType, PropertyDescriptor::required, PropertyContainer::type, PropertyDescriptor::units, PropertyContainer::value, and PropertyDescriptor::valueType.
Referenced by CppPTSLClient::GetDynamicProperties().
Spot()
std::shared_ptr< CommandResponse > Spot (const SpotRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Place clips at exact locations
Returns
task execution status
References INIT_HNDLR_OVRD, SpotLocationData::locationOptions, SpotRequest::locationOptions, SpotLocationData::locationType, SpotRequest::locationType, SpotLocationData::locationValue, SpotRequest::locationValue, MAKE_REQUEST, CppPTSLClient::Spot(), and SpotRequest::spotLocationData.
Referenced by CppPTSLClient::Spot().
ExportSessionInfoAsText()
std::shared_ptr< ExportSessionInfoAsTextResponse > ExportSessionInfoAsText (const ExportSessionInfoAsTextRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Provide session data as text
Returns
task execution status
References CppPTSLClient::ExportSessionInfoAsText(), ExportSessionInfoAsTextRequest::fadeHandlingType, ExportSessionInfoAsTextRequest::includeClipList, ExportSessionInfoAsTextRequest::includeFileList, ExportSessionInfoAsTextRequest::includeMarkers, ExportSessionInfoAsTextRequest::includePluginList, ExportSessionInfoAsTextRequest::includeTrackEDLs, ExportSessionInfoAsTextRequest::includeUserTimestamps, INIT_HNDLR_OVRD, MAKE_REQUEST, MAKE_RESP_OVRD, ExportSessionInfoAsTextRequest::outputPath, ExportSessionInfoAsTextRequest::outputType, ExportSessionInfoAsTextRequest::showSubFrames, ExportSessionInfoAsTextRequest::textAsFileFormat, ExportSessionInfoAsTextRequest::trackListType, and ExportSessionInfoAsTextRequest::trackOffsetOptions.
Referenced by CppPTSLClient::ExportSessionInfoAsText().
SetPlaybackMode()
std::shared_ptr< SetPlaybackModeResponse > SetPlaybackMode (const SetPlaybackModeRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set playback mode
Returns
task execution status
References INIT_HNDLR_OVRD, MAKE_REQUEST, MAKE_RESP_OVRD, SetPlaybackModeRequest::playbackMode, and CppPTSLClient::SetPlaybackMode().
Referenced by CppPTSLClient::SetPlaybackMode().
SetRecordMode()
std::shared_ptr< SetRecordModeResponse > SetRecordMode (const SetRecordModeRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set record mode
Returns
task execution status
References INIT_HNDLR_OVRD, MAKE_REQUEST, MAKE_RESP_OVRD, SetRecordModeRequest::recordArmTransport, SetRecordModeRequest::recordMode, and CppPTSLClient::SetRecordMode().
Referenced by CppPTSLClient::SetRecordMode().
GetSessionAudioFormat()
std::shared_ptr< GetSessionAudioFormatResponse > GetSessionAudioFormat (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get current session audio files format
References CppPTSLClient::GetSessionAudioFormat(), INIT_HNDLR, MAKE_REQUEST, and MAKE_RESP_OVRD.
Referenced by CppPTSLClient::GetSessionAudioFormat().
GetSessionSampleRate()
std::shared_ptr< GetSessionSampleRateResponse > GetSessionSampleRate (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get current session sample rate
References CppPTSLClient::GetSessionSampleRate(), INIT_HNDLR, MAKE_REQUEST, and MAKE_RESP_OVRD.
Referenced by CppPTSLClient::GetSessionSampleRate().
GetSessionBitDepth()
std::shared_ptr< GetSessionBitDepthResponse > GetSessionBitDepth (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get current session bit depth
References CppPTSLClient::GetSessionBitDepth(), INIT_HNDLR, MAKE_REQUEST, and MAKE_RESP_OVRD.
Referenced by CppPTSLClient::GetSessionBitDepth().
GetSessionInterleavedState()
std::shared_ptr< GetSessionInterleavedStateResponse > GetSessionInterleavedState (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get current session interleaved state
References CppPTSLClient::GetSessionInterleavedState(), INIT_HNDLR, MAKE_REQUEST, and MAKE_RESP_OVRD.
Referenced by CppPTSLClient::GetSessionInterleavedState().
GetSessionTimeCodeRate()
std::shared_ptr< GetSessionTimeCodeRateResponse > GetSessionTimeCodeRate (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get current session time code rate
References CppPTSLClient::GetSessionTimeCodeRate(), INIT_HNDLR, MAKE_REQUEST, and MAKE_RESP_OVRD.
Referenced by CppPTSLClient::GetSessionTimeCodeRate().
GetSessionFeetFramesRate()
std::shared_ptr< GetSessionFeetFramesRateResponse > GetSessionFeetFramesRate (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get current session feet+frames rate
References CppPTSLClient::GetSessionFeetFramesRate(), INIT_HNDLR, MAKE_REQUEST, and MAKE_RESP_OVRD.
Referenced by CppPTSLClient::GetSessionFeetFramesRate().
GetSessionAudioRatePullSettings()
std::shared_ptr< GetSessionAudioRatePullSettingsResponse > GetSessionAudioRatePullSettings (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get current session audio rate pull up/down
References CppPTSLClient::GetSessionAudioRatePullSettings(), INIT_HNDLR, MAKE_REQUEST, and MAKE_RESP_OVRD.
Referenced by CppPTSLClient::GetSessionAudioRatePullSettings().
GetSessionVideoRatePullSettings()
std::shared_ptr< GetSessionVideoRatePullSettingsResponse > GetSessionVideoRatePullSettings (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get current session video rate pull up/down
References CppPTSLClient::GetSessionVideoRatePullSettings(), INIT_HNDLR, MAKE_REQUEST, and MAKE_RESP_OVRD.
Referenced by CppPTSLClient::GetSessionVideoRatePullSettings().
GetSessionName()
std::shared_ptr< GetSessionNameResponse > GetSessionName (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get current session name
References CppPTSLClient::GetSessionName(), INIT_HNDLR, MAKE_REQUEST, and MAKE_RESP_OVRD.
Referenced by CppPTSLClient::GetSessionName().
GetSessionPath()
std::shared_ptr< GetSessionPathResponse > GetSessionPath (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get current session path
References CppPTSLClient::GetSessionPath(), FileLocation::info, INIT_HNDLR, MAKE_REQUEST, MAKE_RESP_OVRD, and FileLocation::path.
Referenced by CppPTSLClient::GetSessionPath().
GetSessionStartTime()
std::shared_ptr< GetSessionStartTimeResponse > GetSessionStartTime (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get current session start time
References CppPTSLClient::GetSessionStartTime(), INIT_HNDLR, MAKE_REQUEST, and MAKE_RESP_OVRD.
Referenced by CppPTSLClient::GetSessionStartTime().
GetSessionLength()
std::shared_ptr< GetSessionLengthResponse > GetSessionLength (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get current session length
References CppPTSLClient::GetSessionLength(), INIT_HNDLR, MAKE_REQUEST, and MAKE_RESP_OVRD.
Referenced by CppPTSLClient::GetSessionLength().
SetSessionAudioFormat()
std::shared_ptr< CommandResponse > SetSessionAudioFormat (const SetSessionAudioFormatRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set current session audio files format
References SetSessionAudioFormatRequest::audioFormat, INIT_HNDLR_OVRD, MAKE_REQUEST, and CppPTSLClient::SetSessionAudioFormat().
Referenced by CppPTSLClient::SetSessionAudioFormat().
SetSessionBitDepth()
std::shared_ptr< CommandResponse > SetSessionBitDepth (const SetSessionBitDepthRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set current session bit depth
References SetSessionBitDepthRequest::bitDepth, INIT_HNDLR_OVRD, MAKE_REQUEST, and CppPTSLClient::SetSessionBitDepth().
Referenced by CppPTSLClient::SetSessionBitDepth().
SetSessionInterleavedState()
std::shared_ptr< CommandResponse > SetSessionInterleavedState (const SetSessionInterleavedStateRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set current session interleaved state
References INIT_HNDLR_OVRD, SetSessionInterleavedStateRequest::interleavedState, MAKE_REQUEST, and CppPTSLClient::SetSessionInterleavedState().
Referenced by CppPTSLClient::SetSessionInterleavedState().
SetSessionTimeCodeRate()
std::shared_ptr< CommandResponse > SetSessionTimeCodeRate (const SetSessionTimeCodeRateRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set current session time code rate
References INIT_HNDLR_OVRD, MAKE_REQUEST, CppPTSLClient::SetSessionTimeCodeRate(), and SetSessionTimeCodeRateRequest::timeCodeRate.
Referenced by CppPTSLClient::SetSessionTimeCodeRate().
SetSessionFeetFramesRate()
std::shared_ptr< CommandResponse > SetSessionFeetFramesRate (const SetSessionFeetFramesRateRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set current session feet+frames rate
References SetSessionFeetFramesRateRequest::feetFramesRate, INIT_HNDLR_OVRD, MAKE_REQUEST, and CppPTSLClient::SetSessionFeetFramesRate().
Referenced by CppPTSLClient::SetSessionFeetFramesRate().
SetSessionAudioRatePullSettings()
std::shared_ptr< CommandResponse > SetSessionAudioRatePullSettings (const SetSessionAudioRatePullSettingsRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set current session audio rate pull up/down
References SetSessionAudioRatePullSettingsRequest::audioRatePull, INIT_HNDLR_OVRD, MAKE_REQUEST, and CppPTSLClient::SetSessionAudioRatePullSettings().
Referenced by CppPTSLClient::SetSessionAudioRatePullSettings().
SetSessionVideoRatePullSettings()
std::shared_ptr< CommandResponse > SetSessionVideoRatePullSettings (const SetSessionVideoRatePullSettingsRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set current session video rate pull up/down
References INIT_HNDLR_OVRD, MAKE_REQUEST, CppPTSLClient::SetSessionVideoRatePullSettings(), and SetSessionVideoRatePullSettingsRequest::videoRatePull.
Referenced by CppPTSLClient::SetSessionVideoRatePullSettings().
SetSessionStartTime()
std::shared_ptr< CommandResponse > SetSessionStartTime (const SetSessionStartTimeRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set current session start time
References INIT_HNDLR_OVRD, SetSessionStartTimeRequest::maintainRelativePosition, MAKE_REQUEST, SetSessionStartTimeRequest::sessionStartTime, CppPTSLClient::SetSessionStartTime(), and SetSessionStartTimeRequest::trackOffsetOpts.
Referenced by CppPTSLClient::SetSessionStartTime().
SetSessionLength()
std::shared_ptr< CommandResponse > SetSessionLength (const SetSessionLengthRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set current session length
References INIT_HNDLR_OVRD, MAKE_REQUEST, SetSessionLengthRequest::sessionLength, and CppPTSLClient::SetSessionLength().
Referenced by CppPTSLClient::SetSessionLength().
GetPTSLVersion()
std::shared_ptr< GetPTSLVersionResponse > GetPTSLVersion (const GetPTSLVersionRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get current version of PTSL Host, Client or Client's API Methods
References PTSLC_CPP::CId_GetPTSLVersion, CppPTSLClient::GetPTSLVersion(), INIT_HNDLR, MAKE_REQUEST, MAKE_RESP_OVRD, PTSL_CLIENT_API_VERSIONS, PTSL_VERSION_MAJOR, GetPTSLVersionRequest::ptslComponent, PTSLC_CPP::TStatus_Completed, PTSLC_CPP::VPTSLComponents_Client, PTSLC_CPP::VPTSLComponents_ClientAPI, and PTSLC_CPP::VPTSLComponents_Host.
Referenced by CppPTSLClient::GetPTSLVersion().
GetPlaybackMode()
std::shared_ptr< GetPlaybackModeResponse > GetPlaybackMode (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get current playback mode
References CppPTSLClient::GetPlaybackMode(), INIT_HNDLR, MAKE_REQUEST, and MAKE_RESP_OVRD.
Referenced by CppPTSLClient::GetPlaybackMode().
GetRecordMode()
std::shared_ptr< GetRecordModeResponse > GetRecordMode (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get current record mode
References CppPTSLClient::GetRecordMode(), INIT_HNDLR, MAKE_REQUEST, and MAKE_RESP_OVRD.
Referenced by CppPTSLClient::GetRecordMode().
GetTransportArmed()
std::shared_ptr< GetTransportArmedResponse > GetTransportArmed (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get transport armed
References CppPTSLClient::GetTransportArmed(), INIT_HNDLR, MAKE_REQUEST, and MAKE_RESP_OVRD.
Referenced by CppPTSLClient::GetTransportArmed().
GetTransportState()
std::shared_ptr< GetTransportStateResponse > GetTransportState (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get current transport state
References CppPTSLClient::GetTransportState(), INIT_HNDLR, MAKE_REQUEST, and MAKE_RESP_OVRD.
Referenced by CppPTSLClient::GetTransportState().
ClearMemoryLocation()
std::shared_ptr< ClearMemoryLocationResponse > ClearMemoryLocation (const ClearMemoryLocationRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Removes memory locations corresponding to the numbers provided in the list. Memory location enumeration should start with 1 (using 0 or negative numbers may result in undefined behavior).
Returns
task execution status and count of successfully and unsuccessfully cleared memory locations
References CppPTSLClient::ClearMemoryLocation(), PTSLC_CPP::ConvertProtoToCommandError(), INIT_HNDLR_OVRD, ClearMemoryLocationRequest::locationList, MAKE_REQUEST, and MAKE_RESP_OVRD.
Referenced by CppPTSLClient::ClearMemoryLocation().
RenameSelectedClip()
std::shared_ptr< CommandResponse > RenameSelectedClip (const RenameSelectedClipRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Renames a clip that was selected in the Pro Tools.
References RenameSelectedClipRequest::clipLocation, INIT_HNDLR_OVRD, MAKE_REQUEST, RenameSelectedClipRequest::newName, RenameSelectedClipRequest::renameFile, RenameSelectedClipRequest::renameFileExplicitly, and CppPTSLClient::RenameSelectedClip().
Referenced by CppPTSLClient::RenameSelectedClip().
RenameTargetClip()
std::shared_ptr< CommandResponse > RenameTargetClip (const RenameTargetClipRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Renames a clip by its name.
References RenameTargetClipRequest::clipName, INIT_HNDLR_OVRD, MAKE_REQUEST, RenameTargetClipRequest::newName, RenameTargetClipRequest::renameFile, RenameTargetClipRequest::renameFileExplicitly, and CppPTSLClient::RenameTargetClip().
Referenced by CppPTSLClient::RenameTargetClip().
TogglePlayState()
std::shared_ptr< CommandResponse > TogglePlayState (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Toggles current play state (behaves the same as the button press)
Returns
task execution status
References INIT_HNDLR, MAKE_REQUEST, and CppPTSLClient::TogglePlayState().
Referenced by CppPTSLClient::TogglePlayState().
ToggleRecordEnable()
std::shared_ptr< CommandResponse > ToggleRecordEnable (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Toggles current record enable (behaves the same as the button press)
Returns
task execution status
References INIT_HNDLR, MAKE_REQUEST, and CppPTSLClient::ToggleRecordEnable().
Referenced by CppPTSLClient::ToggleRecordEnable().
PlayHalfSpeed()
std::shared_ptr< CommandResponse > PlayHalfSpeed (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Plays with half speed
Returns
task execution status
References INIT_HNDLR, MAKE_REQUEST, and CppPTSLClient::PlayHalfSpeed().
Referenced by CppPTSLClient::PlayHalfSpeed().
RecordHalfSpeed()
std::shared_ptr< CommandResponse > RecordHalfSpeed (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Records with half speed
Returns
task execution status
References INIT_HNDLR, MAKE_REQUEST, and CppPTSLClient::RecordHalfSpeed().
Referenced by CppPTSLClient::RecordHalfSpeed().
EditMemoryLocation()
std::shared_ptr< CommandResponse > EditMemoryLocation (const EditMemoryLocationRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Edit memory location.
References EditMemoryLocationRequest::colorIndex, EditMemoryLocationRequest::comments, CppPTSLClient::EditMemoryLocation(), EditMemoryLocationRequest::endTime, EditMemoryLocationRequest::generalProperties, MemoryLocationProperties::groupEnables, INIT_HNDLR_OVRD, EditMemoryLocationRequest::location, MAKE_REQUEST, EditMemoryLocationRequest::name, EditMemoryLocationRequest::number, MemoryLocationProperties::prePostRollTimes, EditMemoryLocationRequest::reference, EditMemoryLocationRequest::startTime, EditMemoryLocationRequest::timeProperties, MemoryLocationProperties::trackHeights, EditMemoryLocationRequest::trackName, MemoryLocationProperties::trackVisibility, MemoryLocationProperties::venueSnapshotIndex, MemoryLocationProperties::venueSnapshotName, MemoryLocationProperties::windowConfiguration, MemoryLocationProperties::windowConfigurationIndex, and MemoryLocationProperties::zoomSettings.
Referenced by CppPTSLClient::EditMemoryLocation().
CreateMemoryLocation()
std::shared_ptr< CommandResponse > CreateMemoryLocation (const CreateMemoryLocationRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Create memory location.
References CreateMemoryLocationRequest::colorIndex, CreateMemoryLocationRequest::comments, CppPTSLClient::CreateMemoryLocation(), CreateMemoryLocationRequest::endTime, CreateMemoryLocationRequest::generalProperties, MemoryLocationProperties::groupEnables, INIT_HNDLR_OVRD, CreateMemoryLocationRequest::location, MAKE_REQUEST, CreateMemoryLocationRequest::name, CreateMemoryLocationRequest::number, MemoryLocationProperties::prePostRollTimes, CreateMemoryLocationRequest::reference, CreateMemoryLocationRequest::startTime, CreateMemoryLocationRequest::timeProperties, MemoryLocationProperties::trackHeights, CreateMemoryLocationRequest::trackName, MemoryLocationProperties::trackVisibility, MemoryLocationProperties::venueSnapshotIndex, MemoryLocationProperties::venueSnapshotName, MemoryLocationProperties::windowConfiguration, MemoryLocationProperties::windowConfigurationIndex, and MemoryLocationProperties::zoomSettings.
Referenced by CppPTSLClient::CreateMemoryLocation().
GetMemoryLocations()
std::shared_ptr< GetMemoryLocationsResponse > GetMemoryLocations (const GetMemoryLocationsRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get memory locations.
References MemoryLocation::colorIndex, MemoryLocation::comments, MemoryLocation::endTime, MemoryLocation::generalProperties, CppPTSLClient::GetMemoryLocations(), MemoryLocationProperties::groupEnables, INIT_HNDLR_OVRD, PaginationRequest::limit, MemoryLocation::location, MAKE_REQUEST, MAKE_RESP_OVRD, MemoryLocation::name, MemoryLocation::number, PaginationRequest::offset, GetMemoryLocationsRequest::paginationRequest, MemoryLocationProperties::prePostRollTimes, MemoryLocation::reference, MemoryLocation::startTime, MemoryLocation::timeProperties, MemoryLocationProperties::trackHeights, MemoryLocation::trackName, MemoryLocationProperties::trackVisibility, MemoryLocationProperties::venueSnapshotIndex, MemoryLocationProperties::venueSnapshotName, MemoryLocationProperties::windowConfiguration, MemoryLocationProperties::windowConfigurationIndex, MemoryLocationProperties::windowConfigurationName, and MemoryLocationProperties::zoomSettings.
Referenced by CppPTSLClient::GetMemoryLocations().
RegisterConnection()
std::shared_ptr< RegisterConnectionResponse > RegisterConnection (const RegisterConnectionRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Submit registration information to create a new connection
References RegisterConnectionRequest::applicationName, PTSLC_CPP::CId_RegisterConnection, RegisterConnectionRequest::companyName, CommandRequest::directJsonBody, MAKE_RESP_OVRD, CppPTSLClient::MakeStreamingRequest(), and CppPTSLClient::RegisterConnection().
Referenced by CppPTSLClient::RegisterConnection().
CreateFadesBasedOnPreset()
std::shared_ptr< CommandResponse > CreateFadesBasedOnPreset (const CreateFadesBasedOnPresetRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Create fades on clips from specified preset
Returns
task execution status
References CreateFadesBasedOnPresetRequest::autoAdjustBounds, PTSLC_CPP::ConvertProtoToCommandError(), CppPTSLClient::CreateFadesBasedOnPreset(), CreateFadesBasedOnPresetRequest::fadePresetName, INIT_HNDLR_OVRD, and MAKE_REQUEST.
Referenced by CppPTSLClient::CreateFade(), and CppPTSLClient::CreateFadesBasedOnPreset().
RenameTargetTrack()
std::shared_ptr< CommandResponse > RenameTargetTrack (const RenameTargetTrackRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Rename selected track
Returns
task execution status
References RenameTargetTrackRequest::currentTrackName, INIT_HNDLR_OVRD, MAKE_REQUEST, RenameTargetTrackRequest::newTrackName, CppPTSLClient::RenameTargetTrack(), and RenameTargetTrackRequest::trackId.
Referenced by CppPTSLClient::RenameTargetTrack(), and CppPTSLClient::RenameTrack().
CreateNewTracks()
std::shared_ptr< CreateNewTracksResponse > CreateNewTracks (const CreateNewTracksRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Create new tracks
Returns
task execution status
References CppPTSLClient::CreateNewTracks(), INIT_HNDLR_OVRD, CreateNewTracksRequest::insertionPointPosition, CreateNewTracksRequest::insertionPointTrackName, PaginationRequest::limit, MAKE_REQUEST, MAKE_RESP_OVRD, CreateNewTracksRequest::numberOfTracks, PaginationRequest::offset, CreateNewTracksRequest::paginationRequest, CreateNewTracksRequest::trackFormat, CreateNewTracksRequest::trackName, CreateNewTracksRequest::trackTimebase, and CreateNewTracksRequest::trackType.
Referenced by CppPTSLClient::CreateNewTracks().
SetTimelineSelection()
std::shared_ptr< CommandResponse > SetTimelineSelection (const SetTimelineSelectionRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set timeline selection
Returns
task execution status
References INIT_HNDLR_OVRD, SetTimelineSelectionRequest::inTime, MAKE_REQUEST, SetTimelineSelectionRequest::outTime, SetTimelineSelectionRequest::playStartMarkerTime, SetTimelineSelectionRequest::postRollEnabled, SetTimelineSelectionRequest::postRollStopTime, SetTimelineSelectionRequest::preRollEnabled, SetTimelineSelectionRequest::preRollStartTime, SetTimelineSelectionRequest::propagateToSatellites, CppPTSLClient::SetTimelineSelection(), and SetTimelineSelectionRequest::updateVideoTo.
Referenced by CppPTSLClient::SetTimelineSelection().
GetTimelineSelection()
std::shared_ptr< GetTimelineSelectionResponse > GetTimelineSelection (const GetTimelineSelectionRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Get timeline selection.
References CppPTSLClient::GetTimelineSelection(), INIT_HNDLR_OVRD, MAKE_REQUEST, MAKE_RESP_OVRD, and GetTimelineSelectionRequest::timeScale.
Referenced by CppPTSLClient::GetTimelineSelection().
SelectTracksByName()
std::shared_ptr< SelectTracksByNameResponse > SelectTracksByName (const SelectTracksByNameRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Select tracks by specified names without using wildcards.
References Track::color, TrackAttributes::contains_automation, TrackAttributes::contains_clips, TrackAttributes::containsAutomation, TrackAttributes::containsClips, Track::format, Track::id, Track::id_compressed, Track::index, INIT_HNDLR_OVRD, TrackAttributes::is_frozen, TrackAttributes::is_hidden, TrackAttributes::is_inactive, TrackAttributes::is_input_monitoring_on, TrackAttributes::is_locked, TrackAttributes::is_muted, TrackAttributes::is_online, TrackAttributes::is_open, TrackAttributes::is_record_enabled, TrackAttributes::is_record_enabled_safe, TrackAttributes::is_selected, TrackAttributes::is_smart_dsp_on, TrackAttributes::is_smart_dsp_on_safe, TrackAttributes::is_soloed, TrackAttributes::is_soloed_safe, TrackAttributes::isFrozen, TrackAttributes::isHidden, TrackAttributes::isInactive, TrackAttributes::isInputMonitoringOn, TrackAttributes::isLocked, TrackAttributes::isMuted, TrackAttributes::isOnline, TrackAttributes::isOpen, TrackAttributes::isRecordEnabled, TrackAttributes::isRecordEnabledSafe, TrackAttributes::isSelected, TrackAttributes::isSmartDspOn, TrackAttributes::isSmartDspOnSafe, TrackAttributes::isSoloed, TrackAttributes::isSoloedSafe, PaginationRequest::limit, MAKE_REQUEST, MAKE_RESP_OVRD, Track::name, PaginationRequest::offset, SelectTracksByNameRequest::paginationRequest, SelectTracksByNameRequest::selectionMode, CppPTSLClient::SelectTracksByName(), Track::timebase, Track::track_attributes, SelectTracksByNameRequest::trackNames, and Track::type.
Referenced by CppPTSLClient::SelectTracksByName().
ImportVideo()
std::shared_ptr< ImportVideoResponse > ImportVideo (const ImportVideoRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Import Video file(s) into the session
References ImportVideoRequest::audioDestinationPath, ImportVideoRequest::clearDestinationVideoTrackPlaylist, ImportVideoRequest::destination, ImportVideoRequest::gapsBetweenClips, ImportVideoRequest::importAudioFromFile, CppPTSLClient::ImportVideo(), INIT_HNDLR_OVRD, ImportVideoRequest::location, SpotLocationData::locationOptions, SpotLocationData::locationType, SpotLocationData::locationValue, MAKE_REQUEST, MAKE_RESP_OVRD, ImportVideoRequest::removeExistingVideoClips, ImportVideoRequest::removeExistingVideoTracks, ImportVideoRequest::spotLocationData, and ImportVideoRequest::videoFilesList.
Referenced by CppPTSLClient::ImportVideo().
SelectMemoryLocation()
std::shared_ptr< CommandResponse > SelectMemoryLocation (const SelectMemoryLocationRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Select the memory location specified
References INIT_HNDLR_OVRD, MAKE_REQUEST, SelectMemoryLocationRequest::number, and CppPTSLClient::SelectMemoryLocation().
Referenced by CppPTSLClient::SelectMemoryLocation().
SetTrackMuteState()
std::shared_ptr< CommandResponse > SetTrackMuteState (const SetTrackMuteStateRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set the mute state of the specified tracks (except Video and MasterFader types of tracks)
References SetTrackMuteStateRequest::enabled, INIT_HNDLR_OVRD, MAKE_REQUEST, CppPTSLClient::SetTrackMuteState(), and SetTrackMuteStateRequest::trackNames.
Referenced by CppPTSLClient::SetTrackMuteState().
SetTrackSoloState()
std::shared_ptr< CommandResponse > SetTrackSoloState (const SetTrackSoloStateRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set the solo state of the specified tracks (except Video and MasterFader types of tracks)
References SetTrackSoloStateRequest::enabled, INIT_HNDLR_OVRD, MAKE_REQUEST, CppPTSLClient::SetTrackSoloState(), and SetTrackSoloStateRequest::trackNames.
Referenced by CppPTSLClient::SetTrackSoloState().
SetTrackSoloSafeState()
std::shared_ptr< CommandResponse > SetTrackSoloSafeState (const SetTrackSoloSafeStateRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set the solo safe state of the specified tracks (except Video and MasterFader types of tracks)
References SetTrackSoloSafeStateRequest::enabled, INIT_HNDLR_OVRD, MAKE_REQUEST, CppPTSLClient::SetTrackSoloSafeState(), and SetTrackSoloSafeStateRequest::trackNames.
Referenced by CppPTSLClient::SetTrackSoloSafeState().
SetTrackRecordEnableState()
std::shared_ptr< CommandResponse > SetTrackRecordEnableState (const SetTrackRecordEnableStateRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set the record enable state of the specified tracks (Audio, Instrument, Midi and VCA types of tracks only)
References SetTrackRecordEnableStateRequest::enabled, INIT_HNDLR_OVRD, MAKE_REQUEST, CppPTSLClient::SetTrackRecordEnableState(), and SetTrackRecordEnableStateRequest::trackNames.
Referenced by CppPTSLClient::SetTrackRecordEnableState().
SetTrackRecordSafeEnableState()
std::shared_ptr< CommandResponse > SetTrackRecordSafeEnableState (const SetTrackRecordSafeEnableStateRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set the record safe enable state of the specified tracks (Audio, Instrument, Midi and VCA types of tracks only)
References SetTrackRecordSafeEnableStateRequest::enabled, INIT_HNDLR_OVRD, MAKE_REQUEST, CppPTSLClient::SetTrackRecordSafeEnableState(), and SetTrackRecordSafeEnableStateRequest::trackNames.
Referenced by CppPTSLClient::SetTrackRecordSafeEnableState().
SetTrackInputMonitorState()
std::shared_ptr< CommandResponse > SetTrackInputMonitorState (const SetTrackInputMonitorStateRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set the input monitor state of the specified tracks (Audio and VCA types of tracks only)
References SetTrackInputMonitorStateRequest::enabled, INIT_HNDLR_OVRD, MAKE_REQUEST, CppPTSLClient::SetTrackInputMonitorState(), and SetTrackInputMonitorStateRequest::trackNames.
Referenced by CppPTSLClient::SetTrackInputMonitorState().
SetTrackSmartDspState()
std::shared_ptr< CommandResponse > SetTrackSmartDspState (const SetTrackSmartDspStateRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set the smart DSP state of the specified tracks (except Video, Midi, VCA and Basic Folder types of tracks)
References SetTrackSmartDspStateRequest::enabled, INIT_HNDLR_OVRD, MAKE_REQUEST, CppPTSLClient::SetTrackSmartDspState(), and SetTrackSmartDspStateRequest::trackNames.
Referenced by CppPTSLClient::SetTrackSmartDspState().
SetTrackHiddenState()
std::shared_ptr< CommandResponse > SetTrackHiddenState (const SetTrackHiddenStateRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set the hidden state of the specified tracks
References SetTrackHiddenStateRequest::enabled, INIT_HNDLR_OVRD, MAKE_REQUEST, CppPTSLClient::SetTrackHiddenState(), and SetTrackHiddenStateRequest::trackNames.
Referenced by CppPTSLClient::SetTrackHiddenState().
SetTrackInactiveState()
std::shared_ptr< CommandResponse > SetTrackInactiveState (const SetTrackInactiveStateRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set the inactive state of the specified tracks (except Video tracks)
References SetTrackInactiveStateRequest::enabled, INIT_HNDLR_OVRD, MAKE_REQUEST, CppPTSLClient::SetTrackInactiveState(), and SetTrackInactiveStateRequest::trackNames.
Referenced by CppPTSLClient::SetTrackInactiveState().
SetTrackFrozenState()
std::shared_ptr< CommandResponse > SetTrackFrozenState (const SetTrackFrozenStateRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set the frozen state of the specified tracks (Audio, Instrument, AuxInput and Routing Folder types of tracks only)
References SetTrackFrozenStateRequest::enabled, INIT_HNDLR_OVRD, MAKE_REQUEST, CppPTSLClient::SetTrackFrozenState(), and SetTrackFrozenStateRequest::trackNames.
Referenced by CppPTSLClient::SetTrackFrozenState().
SetTrackOnlineState()
std::shared_ptr< CommandResponse > SetTrackOnlineState (const SetTrackOnlineStateRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set the online state of the specified tracks (Video tracks only)
References SetTrackOnlineStateRequest::enabled, INIT_HNDLR_OVRD, MAKE_REQUEST, CppPTSLClient::SetTrackOnlineState(), and SetTrackOnlineStateRequest::trackName.
Referenced by CppPTSLClient::SetTrackOnlineState().
SetTrackOpenState()
std::shared_ptr< CommandResponse > SetTrackOpenState (const SetTrackOpenStateRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Set the open state of the specified tracks (Folder tracks only)
References SetTrackOpenStateRequest::enabled, INIT_HNDLR_OVRD, MAKE_REQUEST, CppPTSLClient::SetTrackOpenState(), and SetTrackOpenStateRequest::trackNames.
Referenced by CppPTSLClient::SetTrackOpenState().
GetSessionIDs()
std::shared_ptr< GetSessionIDsResponse > GetSessionIDs (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Returns originId, instanceId and parentId of the current opened session:
originId is the main ID of the session (or project), and it remains the same in all variations of the session through Save As, Save Copy In, etc.
instanceId is unique for each session variation. In a new/original session file, the instanceId is equal to originId. When variants are introduced via Save As, Save Copy In, and several others, instanceId is set to a new unique ID.
parentId is set to the instanceId of the source session for sessions based off of a previous session. For new/original sessions, the parentId is set to zeros. That means parentId is equal to originId for first-generation variants, and is different for second and later generation variations.
References CppPTSLClient::GetSessionIDs(), INIT_HNDLR, MAKE_REQUEST, and MAKE_RESP_OVRD.
Referenced by CppPTSLClient::GetSessionIDs().
GetMemoryLocationsManageMode()
std::shared_ptr< GetMemoryLocationsManageModeResponse > GetMemoryLocationsManageMode (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Returns the Memory Locations Manage Mode state (see menu Window -> Memory Locations in the UI).
References CppPTSLClient::GetMemoryLocationsManageMode(), INIT_HNDLR, MAKE_REQUEST, and MAKE_RESP_OVRD.
Referenced by CppPTSLClient::GetMemoryLocationsManageMode().
SetMemoryLocationsManageMode()
std::shared_ptr< CommandResponse > SetMemoryLocationsManageMode (const SetMemoryLocationsManageModeRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Sets the Memory Locations Manage Mode (see menu Window -> Memory Locations in the UI).
References SetMemoryLocationsManageModeRequest::enabled, INIT_HNDLR_OVRD, MAKE_REQUEST, and CppPTSLClient::SetMemoryLocationsManageMode().
Referenced by CppPTSLClient::SetMemoryLocationsManageMode().
SetMainCounterFormat()
std::shared_ptr< CommandResponse > SetMainCounterFormat (const SetMainCounterFormatRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Sets the time format of the Main Counter.
References INIT_HNDLR_OVRD, MAKE_REQUEST, CppPTSLClient::SetMainCounterFormat(), and SetMainCounterFormatRequest::timeScale.
Referenced by CppPTSLClient::SetMainCounterFormat().
SetSubCounterFormat()
std::shared_ptr< CommandResponse > SetSubCounterFormat (const SetSubCounterFormatRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Sets the time format of the Sub Counter.
References INIT_HNDLR_OVRD, MAKE_REQUEST, CppPTSLClient::SetSubCounterFormat(), and SetSubCounterFormatRequest::timeScale.
Referenced by CppPTSLClient::SetSubCounterFormat().
GetMainCounterFormat()
std::shared_ptr< GetMainCounterFormatResponse > GetMainCounterFormat (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Returns the time format of the Main Counter.
References CppPTSLClient::GetMainCounterFormat(), INIT_HNDLR, MAKE_REQUEST, and MAKE_RESP_OVRD.
Referenced by CppPTSLClient::GetMainCounterFormat().
GetSubCounterFormat()
std::shared_ptr< GetSubCounterFormatResponse > GetSubCounterFormat (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Returns the time format of the Sub Counter.
References CppPTSLClient::GetSubCounterFormat(), INIT_HNDLR, MAKE_REQUEST, and MAKE_RESP_OVRD.
Referenced by CppPTSLClient::GetSubCounterFormat().
Undo()
std::shared_ptr< UndoResponse > Undo (const UndoRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Undoes the last N operations. Successfully undone operations are returned in the response.
References UndoHistoryOperation::details, INIT_HNDLR_OVRD, UndoRequest::levels, MAKE_REQUEST, MAKE_RESP_OVRD, UndoHistoryOperation::operation, UndoHistoryOperation::time, and CppPTSLClient::Undo().
Referenced by CppPTSLClient::Undo().
Redo()
std::shared_ptr< RedoResponse > Redo (const RedoRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Redoes the last N operations. Successfully redone operations are returned in the response.
References UndoHistoryOperation::details, INIT_HNDLR_OVRD, RedoRequest::levels, MAKE_REQUEST, MAKE_RESP_OVRD, UndoHistoryOperation::operation, CppPTSLClient::Redo(), and UndoHistoryOperation::time.
Referenced by CppPTSLClient::Redo().
UndoAll()
std::shared_ptr< UndoAllResponse > UndoAll (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Undoes all operations listed in Undo History.
References UndoHistoryOperation::details, INIT_HNDLR, MAKE_REQUEST, MAKE_RESP_OVRD, UndoHistoryOperation::operation, UndoHistoryOperation::time, and CppPTSLClient::UndoAll().
Referenced by CppPTSLClient::UndoAll().
RedoAll()
std::shared_ptr< RedoAllResponse > RedoAll (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Redoes all operations listed in Undo History.
References UndoHistoryOperation::details, INIT_HNDLR, MAKE_REQUEST, MAKE_RESP_OVRD, UndoHistoryOperation::operation, CppPTSLClient::RedoAll(), and UndoHistoryOperation::time.
Referenced by CppPTSLClient::RedoAll().
ClearUndoQueue()
std::shared_ptr< CommandResponse > ClearUndoQueue (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Clears the undo queue.
References CppPTSLClient::ClearUndoQueue(), INIT_HNDLR, and MAKE_REQUEST.
Referenced by CppPTSLClient::ClearUndoQueue().
SetTrackDSPModeSafeState()
std::shared_ptr< CommandResponse > SetTrackDSPModeSafeState (const SetTrackDSPModeSafeStateRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Sets the DSP Mode Safe state for the specified tracks.
References SetTrackDSPModeSafeStateRequest::enabled, INIT_HNDLR_OVRD, MAKE_REQUEST, CppPTSLClient::SetTrackDSPModeSafeState(), and SetTrackDSPModeSafeStateRequest::trackNames.
Referenced by CppPTSLClient::SetTrackDSPModeSafeState().
GetSessionSystemDelayInfo()
std::shared_ptr< GetSessionSystemDelayInfoResponse > GetSessionSystemDelayInfo (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Provides the System Delay value and the Delay Compensation state of the current session.
References CppPTSLClient::GetSessionSystemDelayInfo(), INIT_HNDLR, MAKE_REQUEST, and MAKE_RESP_OVRD.
Referenced by CppPTSLClient::GetSessionSystemDelayInfo().
GroupClips()
std::shared_ptr< CommandResponse > GroupClips (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Creates a new clip group based on the Edit selection made across tracks.
References CppPTSLClient::GroupClips(), INIT_HNDLR, and MAKE_REQUEST.
Referenced by CppPTSLClient::GroupClips().
UngroupClips()
std::shared_ptr< CommandResponse > UngroupClips (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Reveals all underlying clips and any nested clip groups within a selected clip group, making them independent and editable. Note: Only the front-most top-level clip group will be ungrouped; any underlying clip groups will be preserved.
References INIT_HNDLR, MAKE_REQUEST, and CppPTSLClient::UngroupClips().
Referenced by CppPTSLClient::UngroupClips().
UngroupAllClips()
std::shared_ptr< CommandResponse > UngroupAllClips (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Reveals all clips within a selected clip group and any of its nested clip groups, making them independent and editable.
References INIT_HNDLR, MAKE_REQUEST, and CppPTSLClient::UngroupAllClips().
Referenced by CppPTSLClient::UngroupAllClips().
RegroupClips()
std::shared_ptr< CommandResponse > RegroupClips (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Reassembles a previously ungrouped clip group, including any nested clip groups, restoring its original structure.
References INIT_HNDLR, MAKE_REQUEST, and CppPTSLClient::RegroupClips().
Referenced by CppPTSLClient::RegroupClips().
HostReadyCheck() [1/2]
std::shared_ptr< HostReadyCheckResponse > HostReadyCheck (const CommandRequest & request) [virtual]
Checks to see if the Pro Tools application is fully loaded and ready to execute PTSL commands.
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Checks to see if the Pro Tools application is fully loaded and ready to execute PTSL commands. Called by internal client wrapper utility function PTSLC_CPP::CppPTSLClient::HostReadyCheck.
Returns
the status of the PTSL host
Called by internal client wrapper utility function PTSLC_CPP::CppPTSLClient::HostReadyCheck.
References CppPTSLClient::HostReadyCheck(), INIT_HNDLR, MAKE_REQUEST, MAKE_RESP_OVRD, and PTSLC_CPP::TStatus_Completed.
RepeatSelection()
std::shared_ptr< CommandResponse > RepeatSelection (const RepeatSelectionRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Lets you specify the number of times the selected material is duplicated.
Returns
task execution status
References INIT_HNDLR_OVRD, MAKE_REQUEST, RepeatSelectionRequest::numRepeats, and CppPTSLClient::RepeatSelection().
Referenced by CppPTSLClient::RepeatSelection().
DuplicateSelection()
std::shared_ptr< CommandResponse > DuplicateSelection (const CommandRequest & request) [virtual]
Deprecated
Deprecated All the API-specific functions (commands) are deprecated starting in Pro Tools 2024.10. Please use a general JSON-based SendRequest function instead.
Copies a selection and places it immediately after the end of the selection.
Returns
task execution status
References CppPTSLClient::DuplicateSelection(), INIT_HNDLR, and MAKE_REQUEST.
Referenced by CppPTSLClient::DuplicateSelection().
ClearAllMemoryLocations()
std::shared_ptr< ClearAllMemoryLocationsResponse > ClearAllMemoryLocations (const CommandRequest & request) [virtual]
Clears all the memory locations in the session.
References CppPTSLClient::ClearAllMemoryLocations(), PTSLC_CPP::ConvertProtoToCommandError(), INIT_HNDLR, MAKE_REQUEST, and MAKE_RESP_OVRD.
Referenced by CppPTSLClient::ClearAllMemoryLocations().
Init()
void Init () [protected]
Used for initialization client, starting PT and host (if required) and checking if host ready.
References CppPTSLClient::HostReadyCheck(), CppPTSLClient::LaunchProTools(), ClientConfig::serverMode, ClientConfig::skipHostLaunch, PTSLC_CPP::Standalone, and PTSLC_CPP::Yes.
Referenced by CppPTSLClient::CppPTSLClient().
Free()
void Free () [protected]
Used to free up client resources.
References ClientConfig::serverMode, and PTSLC_CPP::Standalone.
Referenced by CppPTSLClient::~CppPTSLClient().
HostReadyCheck() [2/2]
void HostReadyCheck () [protected]
Internal client wrapper utility function called by the constructor, PTSLC_CPP::CppPTSLClient::CppPTSLClient and checks to see if the Pro Tools application is ready to execute PTSL commands.
References PTSLC_CPP::CId_HostReadyCheck, ptsl::Completed, PTSLC_CPP::DefaultJsonParseOptions(), HostReadyCheckResponseBody::is_host_ready, and CppPTSLClient::SendRequest().
Referenced by CppPTSLClient::HostReadyCheck(), and CppPTSLClient::Init().
Member Data Documentation
OnResponseReceived
std::function<void(std::shared_ptr<CppPTSLResponse>)> OnResponseReceived
Client's callback event for returning responses on requests.
(Current Version)
Referenced by main(), and CppPTSLClient::SendRequest().
OnResponseReceived_V1_Deprecated
std:: function<void(std::shared_ptr<CommandResponse>)> OnResponseReceived_V1_Deprecated
Client's callback event for returning responses on requests.
(Legacy Version)
Deprecated
Deprecated This version of the function is deprecated and may be removed in future versions. Users are encouraged to use the OnResponseReceived function instead.
Referenced by CppPTSLClient::MakeRequest(), and CppPTSLClient::MakeStreamingRequest().
The documentation for this class was generated from the following files:
CppPTSLClient.h
CppPTSLC_DefaultRequest.cpp
CppPTSLClient.cpp
CppPTSLC_Clear.cpp
CppPTSLC_ClearAllMemoryLocations.cpp
CppPTSLC_ClearMemoryLocation.cpp
CppPTSLC_ClearSpecial.cpp
CppPTSLC_ClearUndoQueue.cpp
CppPTSLC_CloseSession.cpp
CppPTSLC_ConsolidateClip.cpp
CppPTSLC_Copy.cpp
CppPTSLC_CopySpecial.cpp
CppPTSLC_CreateFade.cpp
CppPTSLC_CreateFadesBasedOnPreset.cpp
CppPTSLC_CreateMemoryLocation.cpp
CppPTSLC_CreateNewTracks.cpp
CppPTSLC_CreateSession.cpp
CppPTSLC_Cut.cpp
CppPTSLC_CutSpecial.cpp
CppPTSLC_DuplicateSelection.cpp
CppPTSLC_EditMemoryLocation.cpp
CppPTSLC_ExportClipsAsFiles.cpp
CppPTSLC_ExportMix.cpp
CppPTSLC_ExportSelectedTracksAsAAFOMF.cpp
CppPTSLC_ExportSessionInfoAsText.cpp
CppPTSLC_ExtendSelectionToTargetTracks.cpp
CppPTSLC_GetDynamicProperties.cpp
CppPTSLC_GetEditMode.cpp
CppPTSLC_GetEditModeOptions.cpp
CppPTSLC_GetEditTool.cpp
CppPTSLC_GetFileLocation.cpp
CppPTSLC_GetMainCounterFormat.cpp
CppPTSLC_GetMemoryLocations.cpp
CppPTSLC_GetMemoryLocationsManageMode.cpp
CppPTSLC_GetPlaybackMode.cpp
CppPTSLC_GetPTSLVersion.cpp
CppPTSLC_GetRecordMode.cpp
CppPTSLC_GetSessionAudioFormat.cpp
CppPTSLC_GetSessionAudioRatePullSettings.cpp
CppPTSLC_GetSessionBitDepth.cpp
CppPTSLC_GetSessionFeetFramesRate.cpp
CppPTSLC_GetSessionIDs.cpp
CppPTSLC_GetSessionInterleavedState.cpp
CppPTSLC_GetSessionLength.cpp
CppPTSLC_GetSessionName.cpp
CppPTSLC_GetSessionPath.cpp
CppPTSLC_GetSessionSampleRate.cpp
CppPTSLC_GetSessionStartTime.cpp
CppPTSLC_GetSessionSystemDelayInfo.cpp
CppPTSLC_GetSessionTimeCodeRate.cpp
CppPTSLC_GetSessionVideoRatePullSettings.cpp
CppPTSLC_GetSubCounterFormat.cpp
CppPTSLC_GetTaskStatus.cpp
CppPTSLC_GetTimelineSelection.cpp
CppPTSLC_GetTrackList.cpp
CppPTSLC_GetTransportArmed.cpp
CppPTSLC_GetTransportState.cpp
CppPTSLC_GroupClips.cpp
CppPTSLC_HostReadyCheck.cpp
CppPTSLC_Import.cpp
CppPTSLC_ImportVideo.cpp
CppPTSLC_OpenSession.cpp
CppPTSLC_Paste.cpp
CppPTSLC_PasteSpecial.cpp
CppPTSLC_PlayHalfSpeed.cpp
CppPTSLC_RecallZoomPreset.cpp
CppPTSLC_RecordHalfSpeed.cpp
CppPTSLC_Redo.cpp
CppPTSLC_RedoAll.cpp
CppPTSLC_RefreshAllModifiedAudioFiles.cpp
CppPTSLC_RefreshTargetAudioFiles.cpp
CppPTSLC_RegisterConnection.cpp
CppPTSLC_RegroupClips.cpp
CppPTSLC_RenameSelectedClip.cpp
CppPTSLC_RenameTargetClip.cpp
CppPTSLC_RenameTargetTrack.cpp
CppPTSLC_RenameTrack.cpp
CppPTSLC_RepeatSelection.cpp
CppPTSLC_SaveSession.cpp
CppPTSLC_SaveSessionAs.cpp
CppPTSLC_SelectAllClipsOnTrack.cpp
CppPTSLC_SelectMemoryLocation.cpp
CppPTSLC_SelectTracksByName.cpp
CppPTSLC_SetEditMode.cpp
CppPTSLC_SetEditModeOptions.cpp
CppPTSLC_SetEditTool.cpp
CppPTSLC_SetMainCounterFormat.cpp
CppPTSLC_SetMemoryLocationsManageMode.cpp
CppPTSLC_SetPlaybackMode.cpp
CppPTSLC_SetRecordMode.cpp
CppPTSLC_SetSessionAudioFormat.cpp
CppPTSLC_SetSessionAudioRatePullSettings.cpp
CppPTSLC_SetSessionBitDepth.cpp
CppPTSLC_SetSessionFeetFramesRate.cpp
CppPTSLC_SetSessionInterleavedState.cpp
CppPTSLC_SetSessionLength.cpp
CppPTSLC_SetSessionStartTime.cpp
CppPTSLC_SetSessionTimeCodeRate.cpp
CppPTSLC_SetSessionVideoRatePullSettings.cpp
CppPTSLC_SetSubCounterFormat.cpp
CppPTSLC_SetTimelineSelection.cpp
CppPTSLC_SetTrackDSPModeSafeState.cpp
CppPTSLC_SetTrackFrozenState.cpp
CppPTSLC_SetTrackHiddenState.cpp
CppPTSLC_SetTrackInactiveState.cpp
CppPTSLC_SetTrackInputMonitorState.cpp
CppPTSLC_SetTrackMuteState.cpp
CppPTSLC_SetTrackOnlineState.cpp
CppPTSLC_SetTrackOpenState.cpp
CppPTSLC_SetTrackRecordEnableState.cpp
CppPTSLC_SetTrackRecordSafeEnableState.cpp
CppPTSLC_SetTrackSmartDspState.cpp
CppPTSLC_SetTrackSoloSafeState.cpp
CppPTSLC_SetTrackSoloState.cpp
CppPTSLC_Spot.cpp
CppPTSLC_TogglePlayState.cpp
CppPTSLC_ToggleRecordEnable.cpp
CppPTSLC_TrimToSelection.cpp
CppPTSLC_Undo.cpp
CppPTSLC_UndoAll.cpp
CppPTSLC_UngroupAllClips.cpp
CppPTSLC_UngroupClips.cpp