CppPTSLResponse
#include <CppPTSLResponse.h>
Public Member Functions
CppPTSLResponse ()=default
CppPTSLResponse (CommandId commandId, const std::string &responseBodyJson=``, const std::string &responseErrorJson=``)
std::string GetTaskId () const
void SetTaskId (const std::string &taskId)
CommandId GetCommandId () const
void SetCommandId (const CommandId &commandId)
CommandStatusType GetStatus () const
void SetStatus (const CommandStatusType &status)
int32_t GetProgress () const
void SetProgress (const int32_t progress)
std::string GetResponseBodyJson () const
void SetResponseBodyJson (const std::string &responseBodyJson)
std::string GetResponseErrorJson () const
void SetResponseErrorJson (const std::string &responseErrorJson)
ResponseError GetResponseErrorList () const
int32_t GetVersion () const
void SetVersion (const int32_t version)
int32_t GetVersionMinor () const
void SetVersionMinor (const int32_t versionMinor)
int32_t GetVersionRevision () const
void SetVersionRevision (const int32_t versionRevision)
std::string GetVersionedResponseHeaderJson () const
void SetVersionedResponseHeaderJson (const std::string &versionedRequestHeaderJson)
Constructor & Destructor Documentation
CppPTSLResponse() [1/2]
CppPTSLResponse () [default]
CppPTSLResponse() [2/2]
CppPTSLResponse (CommandId commandId, const std::string & responseBodyJson = ``, const std::string & responseErrorJson = ``)
Member Function Documentation
GetTaskId()
std::string GetTaskId () const
Referenced by PtslCmdCommandResult::PtslCmdCommandResult().
SetTaskId()
void SetTaskId (const std::string & taskId)
GetCommandId()
CommandId GetCommandId () const
Referenced by PtslCmdCommandResult::PtslCmdCommandResult().
SetCommandId()
void SetCommandId (const CommandId & commandId)
GetStatus()
CommandStatusType GetStatus () const
Referenced by PtslCmdCommandResult::PtslCmdCommandResult().
SetStatus()
void SetStatus (const CommandStatusType & status)
Referenced by CppPTSLClient::SendRequest().
GetProgress()
int32_t GetProgress () const
Referenced by PtslCmdCommandResult::PtslCmdCommandResult().
SetProgress()
void SetProgress (const int32_t progress)
GetResponseBodyJson()
std::string GetResponseBodyJson () const
SetResponseBodyJson()
void SetResponseBodyJson (const std::string & responseBodyJson)
GetResponseErrorJson()
std::string GetResponseErrorJson () const
SetResponseErrorJson()
void SetResponseErrorJson (const std::string & responseErrorJson)
GetResponseErrorList()
ResponseError GetResponseErrorList () const
GetVersion()
int32_t GetVersion () const
Referenced by PtslCmdCommandResult::PtslCmdCommandResult().
SetVersion()
void SetVersion (const int32_t version)
GetVersionMinor()
int32_t GetVersionMinor () const
Referenced by PtslCmdCommandResult::PtslCmdCommandResult().
SetVersionMinor()
void SetVersionMinor (const int32_t versionMinor)
GetVersionRevision()
int32_t GetVersionRevision () const
Referenced by PtslCmdCommandResult::PtslCmdCommandResult().
SetVersionRevision()
void SetVersionRevision (const int32_t versionRevision)
GetVersionedResponseHeaderJson()
std::string GetVersionedResponseHeaderJson () const
Referenced by PtslCmdCommandResult::PtslCmdCommandResult().
SetVersionedResponseHeaderJson()
void SetVersionedResponseHeaderJson (const std::string & versionedRequestHeaderJson)
The documentation for this class was generated from the following files:
CppPTSLResponse.h
CppPTSLResponse.cpp