CppPTSLRequest
#include <CppPTSLRequest.h>
Public Member Functions
CppPTSLRequest ()=delete
CppPTSLRequest (CommandId commandId, const std::string &requestBodyJson=``)
CommandId GetCommandId () const
void SetCommandId (const CommandId &commandId)
int32_t GetVersion () const
void SetVersion (const int32_t version)
int32_t GetVersionMinor () const
void SetVersionMinor (const int32_t versionMinor)
int32_t GetVersionRevision () const
void SetVersionRevision (const int32_t versionRevision)
std::string GetSessionId () const
void SetSessionId (const std::string &sessionId)
std::string GetVersionedRequestHeaderJson () const
void SetVersionedRequestHeaderJson (const std::string &versionedRequestHeaderJson)
std::string GetRequestBodyJson () const
void SetRequestBodyJson (const std::string &requestBodyJson)
Constructor & Destructor Documentation
CppPTSLRequest() [1/2]
CppPTSLRequest () [delete]
CppPTSLRequest() [2/2]
CppPTSLRequest (CommandId commandId, const std::string & requestBodyJson = ``)
Member Function Documentation
GetCommandId()
CommandId GetCommandId () const
Referenced by CppPTSLClient::SendRequest().
SetCommandId()
void SetCommandId (const CommandId & commandId)
GetVersion()
int32_t GetVersion () const
Referenced by CppPTSLClient::SendRequest().
SetVersion()
void SetVersion (const int32_t version)
Referenced by PtslCmdCommandRunner::RunCommand().
GetVersionMinor()
int32_t GetVersionMinor () const
Referenced by CppPTSLClient::SendRequest().
SetVersionMinor()
void SetVersionMinor (const int32_t versionMinor)
Referenced by PtslCmdCommandRunner::RunCommand().
GetVersionRevision()
int32_t GetVersionRevision () const
Referenced by CppPTSLClient::SendRequest().
SetVersionRevision()
void SetVersionRevision (const int32_t versionRevision)
Referenced by PtslCmdCommandRunner::RunCommand().
GetSessionId()
std::string GetSessionId () const
Referenced by CppPTSLClient::SendRequest().
SetSessionId()
void SetSessionId (const std::string & sessionId)
GetVersionedRequestHeaderJson()
std::string GetVersionedRequestHeaderJson () const
Referenced by CppPTSLClient::SendRequest().
SetVersionedRequestHeaderJson()
void SetVersionedRequestHeaderJson (const std::string & versionedRequestHeaderJson)
Referenced by PtslCmdCommandRunner::RunCommand().
GetRequestBodyJson()
std::string GetRequestBodyJson () const
Referenced by CppPTSLClient::SendRequest().
SetRequestBodyJson()
void SetRequestBodyJson (const std::string & requestBodyJson)
Referenced by PtslCmdCommandRunner::RunCommand().
The documentation for this class was generated from the following files:
CppPTSLRequest.h
CppPTSLRequest.cpp