CommandLineParser
#include <CommandLineParser.h>
Description
Parses command line arguments into internal structure of parameters and arguments.
Following terms are used in the context of this class:
'parameter' ('param') is a value that starts with a paramSymbol (e.g., `-`) – e.g., `-file`;
'argument' ('arg') is a value that follows a parameter – e.g., `script.txt`. Parameters can have single, multiple or no arguments.
Public Member Functions
CommandLineParser ()=delete
CommandLineParser (int argc, char *argv[], bool skipFirstParam=true)
CommandLineParser (std::vector< std::string > commandArguments, bool skipFirstParam=true)
const ParamsArgsMap & GetParamsWithArgs () const
Returns the map of parameters with their arguments.
bool IsEmpty () const
Checks if the command line arguments are empty.
bool HasParam (const std::string &param) const
Checks if the given parameter is present in the command line arguments.
std::optional< std::vector< std::string > > GetArgsForParam (const std::string &param) const
Returns all arguments for the given parameter.
std::string FirstOrDefault (const std::string &param, const std::string &defaultValue) const
Returns the first argument for the given parameter.
std::string operator[] (const std::string &param) const
Constructor & Destructor Documentation
CommandLineParser() [1/3]
CommandLineParser () [delete]
CommandLineParser() [2/3]
CommandLineParser (int argc, char * argv[], bool skipFirstParam = true)
CommandLineParser() [3/3]
CommandLineParser (std::vector< std::string > commandArguments, bool skipFirstParam = true)
Member Function Documentation
GetParamsWithArgs()
const ParamsArgsMap & GetParamsWithArgs () const [inline]
Returns the map of parameters with their arguments.
The special key Constants::PARAMETERLESS_ARGS_KEY is used for arguments without a parameter.
IsEmpty()
bool IsEmpty () const
Checks if the command line arguments are empty.
HasParam()
bool HasParam (const std::string & param) const
Checks if the given parameter is present in the command line arguments.
Referenced by GetArgsForParam().
GetArgsForParam()
optional< vector< string > > GetArgsForParam (const std::string & param) const
Returns all arguments for the given parameter.
If the parameter is a modifier (i.e., it does not have arguments), returns an empty vector. If the parameter is not present, returns nullopt.
References HasParam().
Referenced by FirstOrDefault().
FirstOrDefault()
string FirstOrDefault (const std::string & param, const std::string & defaultValue) const
Returns the first argument for the given parameter.
If the parameter is not present or has no arguments, returns the default value.
References GetArgsForParam().
Referenced by operator[]().
operator[]()
string operator[] (const std::string & param) const
References FirstOrDefault().
The documentation for this class was generated from the following files:
CommandLineParser.h
CommandLineParser.cpp