PtslCmdCommandResult
#include <PtslCmdCommandResult.h>
Public Member Functions
PtslCmdCommandResult (const PTSLC_CPP::CppPTSLResponse &clientResponse)
virtual ~PtslCmdCommandResult ()=default
virtual std::string ToString () const
operator bool () const
Static Public Member Functions
static PtslCmdCommandResult CreateCannotParseArgsResult (const std::string &reason, const std::string &cmdName=``)
Public Attributes
bool gotResponse = false
std::string commandName = ``
std::string jsonHeader = ``
std::string jsonBody = ``
std::string jsonError = ``
std::optional< std::string > cannotParseArgsReason = std::nullopt
Constructor & Destructor Documentation
PtslCmdCommandResult()
PtslCmdCommandResult (const PTSLC_CPP::CppPTSLResponse & clientResponse) [inline], [explicit]
References PTSLC_CPP::EnumToString(), CppPTSLResponse::GetCommandId(), CppPTSLResponse::GetProgress(), CppPTSLResponse::GetStatus(), CppPTSLResponse::GetTaskId(), CppPTSLResponse::GetVersion(), CppPTSLResponse::GetVersionedResponseHeaderJson(), CppPTSLResponse::GetVersionMinor(), CppPTSLResponse::GetVersionRevision(), jsonHeader, Constants::RESPONSE_HEADER_COMMAND, Constants::RESPONSE_HEADER_PROGRESS, Constants::RESPONSE_HEADER_STATUS, Constants::RESPONSE_HEADER_TASK_ID, Constants::RESPONSE_HEADER_VERSION, Constants::RESPONSE_HEADER_VERSION_MINOR, Constants::RESPONSE_HEADER_VERSION_REVISION, and Constants::RESPONSE_HEADER_VERSIONED_RESPONSE_HEADER_JSON.
 PtslCmdCommandResult()
virtual ~PtslCmdCommandResult () [virtual], [default]
Member Function Documentation
CreateCannotParseArgsResult()
static PtslCmdCommandResult CreateCannotParseArgsResult (const std::string & reason, const std::string & cmdName = ``) [inline], [static]
Referenced by PtslCmdCommandRunner::RunCommand(), PtslCmdCommandRunner::RunFileScript(), and PtslCmdCommandRunner::RunScript().
ToString()
virtual std::string ToString () const [inline], [virtual]
References gotResponse, jsonBody, jsonError, jsonHeader, Constants::RESPONSE_BODY, Constants::RESPONSE_ERROR, and Constants::RESPONSE_HEADER.
operator bool()
operator bool () const [inline]
References gotResponse.
Member Data Documentation
gotResponse
bool gotResponse = false
Referenced by operator bool(), and ToString().
commandName
std::string commandName = ``
jsonHeader
std::string jsonHeader = ``
Referenced by PtslCmdCommandResult(), and ToString().
jsonBody
std::string jsonBody = ``
Referenced by ToString().
jsonError
std::string jsonError = ``
Referenced by ToString().
cannotParseArgsReason
std::optional<std::string> cannotParseArgsReason = std::nullopt
The documentation for this struct was generated from the following file:
PtslCmdCommandResult.h