PrintHelpHelpers
#include <PrintHelpHelpers.h>
Description
Helper class for printing help/usage information.
Static Public Member Functions
static void PrintHelp ()
Prints PTSL Cmd usage.
static void PrintCommandListHelp ()
Prints a list of PTSL API commands.
Member Function Documentation
PrintHelp()
void PrintHelp () [static]
Prints PTSL Cmd usage.
Referenced by PrintHelpIfRequired().
PrintCommandListHelp()
void PrintCommandListHelp () [static]
Prints a list of PTSL API commands.
References PTSLC_CPP::EnumValuesToStrings().
Referenced by PrintHelpIfRequired().
The documentation for this class was generated from the following files:
PrintHelpHelpers.h
PrintHelpHelpers.cpp