PtslCmdCommandRunner
#include <PtslCmdCommandRunner.h>
Public Member Functions
PtslCmdCommandRunner (PTSLC_CPP::CppPTSLClient &client)
virtual ~PtslCmdCommandRunner ()=default
PtslCmdCommandStreamResult RunCommand (const PtslCmdCommandRequest &ptslCmdRequest)
std::vector< PtslCmdCommandStreamResult > RunScript (const std::string &scriptJson)
std::vector< PtslCmdCommandStreamResult > RunFileScript (const std::string &fileName)
Constructor & Destructor Documentation
PtslCmdCommandRunner()
PtslCmdCommandRunner (PTSLC_CPP::CppPTSLClient & client) [inline], [explicit]
 PtslCmdCommandRunner()
virtual ~PtslCmdCommandRunner () [virtual], [default]
Member Function Documentation
RunCommand()
PtslCmdCommandStreamResult RunCommand (const PtslCmdCommandRequest & ptslCmdRequest)
References ptsl::CId_EnableAPI, PtslCmdCommandRequest::CommandName, PtslCmdCommandResult::CreateCannotParseArgsResult(), PTSLC_CPP::encodeBase64(), PTSLC_CPP::encrypt(), PtslCmdCommandRequest::EncryptionKey, PtslCmdCommandRequest::RequestBodyJson, PtslCmdCommandStreamResult::results, CppPTSLClient::SendRequest(), CppPTSLRequest::SetRequestBodyJson(), CppPTSLRequest::SetVersion(), CppPTSLRequest::SetVersionedRequestHeaderJson(), CppPTSLRequest::SetVersionMinor(), CppPTSLRequest::SetVersionRevision(), PtslCmdCommandRequest::Version, and PtslCmdCommandRequest::VersionedHeader.
Referenced by main(), and RunScript().
RunScript()
vector< PtslCmdCommandStreamResult > RunScript (const std::string & scriptJson)
References PtslCmdCommandResult::CreateCannotParseArgsResult(), FileScriptParser::Parse(), and RunCommand().
Referenced by RunFileScript().
RunFileScript()
vector< PtslCmdCommandStreamResult > RunFileScript (const std::string & fileName)
References PtslCmdCommandResult::CreateCannotParseArgsResult(), and RunScript().
Referenced by main().
The documentation for this class was generated from the following files:
PtslCmdCommandRunner.h
PtslCmdCommandRunner.cpp