import type { CrmData } from "./types";

export const seedCrmData: CrmData = {
  clients: [
    {
      id: "client-1",
      name: "Ava Monroe",
      status: "active",
      primaryContact: "Ava Monroe",
      email: "ava@midnightelectric.co",
      phone: "+1 (310) 555-0148",
      ratePerHour: 85,
      tags: ["Album", "Mixing", "Vocal"],
      lastContactAt: "2026-02-01T16:10:00Z",
      nextSessionAt: "2026-02-05T20:00:00Z",
      notes: "Focus on vocal tone and stereo width on choruses.",
    },
    {
      id: "client-2",
      name: "The Velvet Horns",
      status: "active",
      primaryContact: "Marco Lewis",
      email: "marco@velvethorns.com",
      phone: "+1 (212) 555-0192",
      ratePerHour: 95,
      tags: ["Brass", "Stem Delivery"],
      lastContactAt: "2026-02-02T09:25:00Z",
      nextSessionAt: "2026-02-04T18:30:00Z",
      notes: "Need alt mixes for live broadcast and streaming.",
    },
    {
      id: "client-3",
      name: "DJ Kael",
      status: "at-risk",
      primaryContact: "Kael Ramos",
      email: "kael@lowfreq.fm",
      phone: "+1 (646) 555-0133",
      ratePerHour: 75,
      tags: ["EDM", "Mastering"],
      lastContactAt: "2026-01-30T14:45:00Z",
      notes: "Waiting on final approval for master tweaks.",
    },
    {
      id: "client-4",
      name: "Sierra Wells",
      status: "inactive",
      primaryContact: "Sierra Wells",
      email: "sierra@quietthunder.io",
      phone: "+1 (415) 555-0177",
      ratePerHour: 80,
      tags: ["Acoustic", "Delivery"],
      lastContactAt: "2026-01-20T11:15:00Z",
      notes: "Project delivered, follow up for credits.",
    },
  ],
  clientProjects: [
    {
      id: "cproj-1",
      clientId: "client-1",
      name: "Midnight Electric",
      status: "mixing",
      protoolsProjectId: "proj-1",
      dueDate: "2026-02-12",
      lastSessionAt: "2026-02-01T19:00:00Z",
      totalLoggedMinutes: 420,
    },
    {
      id: "cproj-2",
      clientId: "client-2",
      name: "Brass & Bones",
      status: "active",
      protoolsProjectId: "proj-2",
      dueDate: "2026-02-08",
      lastSessionAt: "2026-02-02T18:00:00Z",
      totalLoggedMinutes: 310,
    },
    {
      id: "cproj-3",
      clientId: "client-3",
      name: "Low Frequency",
      status: "review",
      protoolsProjectId: "proj-3",
      dueDate: "2026-02-10",
      lastSessionAt: "2026-01-29T21:00:00Z",
      totalLoggedMinutes: 255,
    },
    {
      id: "cproj-4",
      clientId: "client-4",
      name: "Quiet Thunder",
      status: "delivered",
      protoolsProjectId: "proj-4",
      dueDate: "2026-01-18",
      lastSessionAt: "2026-01-19T18:20:00Z",
      totalLoggedMinutes: 390,
    },
  ],
  clientSessions: [
    {
      id: "sess-1",
      clientId: "client-1",
      projectId: "cproj-1",
      type: "mixing",
      startTime: "2026-02-01T19:00:00Z",
      endTime: "2026-02-01T22:30:00Z",
      durationMinutes: 210,
      billableRate: 85,
      notes: "Mix pass v2, automation on choruses.",
    },
    {
      id: "sess-2",
      clientId: "client-2",
      projectId: "cproj-2",
      type: "recording",
      startTime: "2026-02-02T17:30:00Z",
      endTime: "2026-02-02T20:15:00Z",
      durationMinutes: 165,
      billableRate: 95,
      notes: "Horn section overdubs and comping.",
    },
    {
      id: "sess-3",
      clientId: "client-3",
      projectId: "cproj-3",
      type: "mastering",
      startTime: "2026-01-29T20:00:00Z",
      endTime: "2026-01-29T22:00:00Z",
      durationMinutes: 120,
      billableRate: 75,
      notes: "Mastering tweaks for low-end translation.",
    },
  ],
  clientTasks: [
    {
      id: "task-1",
      clientId: "client-1",
      projectId: "cproj-1",
      title: "Print alt vocal mix (radio edit)",
      status: "in-progress",
      dueAt: "2026-02-04",
      assignee: "Rezmo",
    },
    {
      id: "task-2",
      clientId: "client-1",
      projectId: "cproj-1",
      title: "Prep stems for mastering review",
      status: "todo",
      dueAt: "2026-02-06",
      assignee: "Rezmo",
    },
    {
      id: "task-3",
      clientId: "client-2",
      projectId: "cproj-2",
      title: "Send brass stems for live mix",
      status: "todo",
      dueAt: "2026-02-05",
      assignee: "Rezmo",
    },
  ],
  clientCorrespondence: [
    {
      id: "msg-1",
      clientId: "client-1",
      channel: "email",
      direction: "inbound",
      subject: "Mix notes v2",
      summary: "Warm the low end, widen choruses, keep vocal present.",
      occurredAt: "2026-02-01T16:10:00Z",
      participants: ["Ava Monroe"],
    },
    {
      id: "msg-2",
      clientId: "client-2",
      channel: "sms",
      direction: "outbound",
      subject: "Session confirmation",
      summary: "Confirmed tracking time for Tuesday 6:30p.",
      occurredAt: "2026-02-02T09:25:00Z",
      participants: ["Marco Lewis"],
    },
    {
      id: "msg-3",
      clientId: "client-3",
      channel: "email",
      direction: "outbound",
      subject: "Master revisions",
      summary: "Shared master v3 with alternate limiter settings.",
      occurredAt: "2026-01-30T14:45:00Z",
      participants: ["Kael Ramos"],
    },
  ],
};
